import type { LevelInput } from '../types'
import { FIGURA_PNG } from './figuraPng'

/** Nivel 1 · Documento de calidad — al terminar, producís documentos prolijos solo. */
export const nivel1 = {
  level: 1,
  title: 'Documento de calidad',
  summary:
    'Configuración, tipografía, matemática, tablas, figuras, navegación. Con esto ya producís documentos de calidad por tu cuenta.',
  lessons: [
    // ── Módulo: Configuración ─────────────────────────────────────────────
    {
      id: 'l1-preambulo',
      level: 1,
      title: 'El preámbulo y los paquetes',
      capa: 'infraestructura',
      module: 'Configuración',
      objective: 'configurar el documento con paquetes y armar una portada con título.',
      prerequisites: ['l0-primer-documento'],
      content: [
        {
          kind: 'prose',
          markdown:
            'El **preámbulo** es todo lo que va entre `\\documentclass` y `\\begin{document}`. Ahí no escribís contenido visible: **configurás**. La herramienta principal es `\\usepackage`, que carga **paquetes** (extensiones que agregan comandos o cambian el comportamiento).',
        },
        {
          kind: 'prose',
          markdown:
            'La `\\documentclass` también acepta **opciones** entre corchetes: `\\documentclass[11pt,a4paper]{article}` fija el cuerpo de letra y el papel. Y los metadatos de la portada (`\\title`, `\\author`, `\\date`) se **declaran** en el preámbulo, pero se **imprimen** dentro del documento con `\\maketitle`.',
        },
        {
          kind: 'commands',
          title: 'Comandos clave',
          items: [
            { cmd: '\\documentclass[op]{clase}', desc: 'Tipo de documento, con opciones (11pt, a4paper…).' },
            { cmd: '\\usepackage[op]{pkg}', desc: 'Carga un paquete, con opciones opcionales entre [ ].' },
            { cmd: '\\title{...}', desc: 'Define el título (en el preámbulo).' },
            { cmd: '\\author{...}', desc: 'Define el/los autores.' },
            { cmd: '\\date{\\today}', desc: 'Fecha (o \\today para la de hoy).' },
            { cmd: '\\maketitle', desc: 'Imprime la portada. Va dentro del document.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Los `\\usepackage` van **siempre en el preámbulo**. Si LaTeX dice *“Can be used only in preamble”*, moviste algo adentro del `document`. Y `\\maketitle` es al revés: va **dentro** del `document`.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Buena práctica: agrupá los `\\usepackage` por tema (idioma, matemática, tablas…) y comentá por qué está cada uno. Podés cargar varios juntos: `\\usepackage{amsmath,amssymb}`. Un preámbulo ordenado se mantiene solo.',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            'Hay un conjunto de paquetes que conviene tener **siempre** (un “piso”) y otros que se agregan según el contenido. Eso lo vemos en detalle en **El canon del preámbulo**, más adelante en este nivel.',
        },
      ],
      example: [
        '\\documentclass[11pt,a4paper]{article}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '',
        '% --- Idioma y fuente ---',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '',
        '% --- Matemática ---',
        '\\usepackage{amsmath}',
        '',
        '% --- Metadatos de la portada ---',
        '\\title{Informe de laboratorio}',
        '\\author{Estudiante}',
        '\\date{\\today}',
        '',
        '\\begin{document}',
        '\\maketitle   % imprime la portada con los metadatos de arriba',
        '',
        '\\section{Introducción}',
        'El preámbulo configuró idioma, fuente y matemática; \\maketitle imprimió',
        'la portada con el título, el autor y la fecha.',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt:
          'Completá los dos TODO: definí \\title y \\author en el preámbulo, e imprimí la portada con \\maketitle dentro del documento.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage{microtype}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '% TODO (1): definí \\title{...} y \\author{...} acá, en el preámbulo.',
          '',
          '\\begin{document}',
          '% TODO (2): imprimí la portada con \\maketitle.',
          '',
          'Contenido del documento.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\title', '\\author', '\\maketitle'],
        hints: ['\\title y \\author van en el preámbulo; \\maketitle, dentro del document.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage{microtype}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\title{Mi informe}',
          '\\author{Estudiante}',
          '',
          '\\begin{document}',
          '\\maketitle',
          'Contenido del documento.',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Idioma y codificación', 'Documentos largos'],
    },
    {
      id: 'l1-idioma-codificacion',
      level: 1,
      title: 'Idioma y codificación',
      capa: 'infraestructura',
      module: 'Configuración',
      objective: 'configurar el español, los acentos y las comillas correctamente.',
      prerequisites: ['l1-preambulo'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Tres cosas para escribir bien en español: **babel** (cortes de palabra y nombres como “Índice” o “Cuadro”), la **codificación de fuente** con `fontenc` (acentos que copian y se buscan bien en el PDF), y **csquotes** para comillas según el idioma. La entrada del `.tex` ya se asume UTF-8.',
        },
        {
          kind: 'prose',
          markdown:
            'El **orden** importa: cargá `fontenc` (y una fuente como `lmodern`) **antes** que `babel`. Con eso, los acentos no solo se ven bien sino que se copian como un solo carácter.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\usepackage[T1]{fontenc}', desc: 'Codificación de fuente: acentos correctos.' },
            { cmd: '\\usepackage{lmodern}', desc: 'Fuente vectorial nítida (evita acentos borrosos).' },
            { cmd: '\\usepackage[spanish,es-noshorthands]{babel}', desc: 'Idioma español (guiones, etiquetas) + apaga los shorthands.' },
            { cmd: '\\usepackage{csquotes}  →  \\enquote{...}', desc: 'Comillas correctas según el idioma.' },
            { cmd: '\\today', desc: 'La fecha actual, escrita en el idioma activo.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Con `babel` en español, los caracteres `"`, `~` o `.` pasan a ser **“shorthands”** (activos) y rompen URLs, TikZ, `siunitx` y tablas con errores misteriosos. Por eso en esta plataforma `babel` **siempre** va con `es-noshorthands`: `\\usepackage[spanish,es-noshorthands]{babel}`. Es gratis y te ahorra horas de depurar.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Buenas prácticas: usá `\\enquote{...}` en vez de teclear comillas a mano (se adaptan al idioma), y dejá este bloque de cuatro paquetes como base fija de todos tus documentos en español.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage{microtype}',
        '\\usepackage[T1]{fontenc}    % acentos que copian bien',
        '\\usepackage{lmodern}        % fuente vectorial nítida',
        '\\usepackage[spanish,es-noshorthands]{babel} % idioma: guiones y etiquetas en español',
        '\\usepackage{csquotes}       % comillas según el idioma',
        '',
        '\\begin{document}',
        '',
        'Acentuación correcta: árbol, ñandú, función, pingüino.',
        '',
        'Una cita con comillas tipográficas: \\enquote{el método es directo}.',
        '',
        'Y la fecha de hoy, en español: \\today.',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt:
          'Configurá el documento en español: cargá fontenc T1 y, después, babel en español con la opción es-noshorthands (en ese orden).',
        starter: [
          '\\documentclass{article}',
          '\\usepackage{lmodern}',
          '\\usepackage{microtype}',
          '% TODO: cargá \\usepackage[T1]{fontenc} y luego \\usepackage[spanish,es-noshorthands]{babel}.',
          '',
          '\\begin{document}',
          'Acentos: árbol, función, pingüino.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['[spanish,es-noshorthands]{babel}', '[T1]{fontenc}'],
        hints: ['Cargá fontenc antes que babel.', 'La opción va entre corchetes: [spanish,es-noshorthands].'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage{lmodern}',
          '\\usepackage{microtype}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '',
          '\\begin{document}',
          'Acentos: árbol, función, pingüino.',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Énfasis y tipografía', 'El canon del preámbulo'],
    },
    {
      id: 'l1-canon-preambulo',
      level: 1,
      title: 'El canon del preámbulo',
      capa: 'infraestructura',
      module: 'Configuración',
      objective:
        'armar un preámbulo de primer nivel: distinguir el PISO (siempre) de lo EXTRA (según el contenido) y respetar el orden canónico.',
      prerequisites: ['l1-preambulo', 'l1-idioma-codificacion'],
      content: [
        {
          kind: 'prose',
          markdown:
            'El preámbulo —todo lo que va entre `\\documentclass` y `\\begin{document}`— es donde se decide la **calidad** del documento. La regla que usamos en esta plataforma es **PISO vs EXTRA**: hay un piso que va **siempre** (es gratis y evita bugs) y, encima, paquetes que se agregan **solo si el contenido los usa**. Cargar paquetes que no usás *también* es un anti-patrón.',
        },
        {
          kind: 'commands',
          title: 'El PISO (en todo documento en español)',
          items: [
            { cmd: '\\usepackage[T1]{fontenc}', desc: 'Acentos que se copian y guionado correcto.' },
            { cmd: '\\usepackage{lmodern}', desc: 'Fuentes vectoriales nítidas (requisito de microtype).' },
            { cmd: '\\usepackage[spanish,es-noshorthands]{babel}', desc: 'Idioma + apaga los shorthands que rompen tikz/siunitx/URLs.' },
            { cmd: '\\usepackage{microtype}', desc: 'Pulido tipográfico casi gratis. El estándar lo pide siempre.' },
            { cmd: '\\usepackage{csquotes}', desc: 'Comillas por idioma con \\enquote{...} (recomendado).' },
          ],
        },
        {
          kind: 'code',
          caption: 'Base MÍNIMA: lo que casi todo documento debería tener',
          latex: [
            '\\documentclass[11pt,a4paper]{article}',
            '\\usepackage[T1]{fontenc}',
            '\\usepackage{lmodern}',
            '\\usepackage[spanish,es-noshorthands]{babel}',
            '\\usepackage{microtype}',
            '\\usepackage{amsmath,amssymb}',
            '\\usepackage{hyperref}',
          ].join('\n'),
        },
        {
          kind: 'prose',
          markdown:
            'Lo **EXTRA** se agrega por tema: matemática seria (`mathtools` —no solo `amsmath`—, `amssymb`, `amsthm`, `siunitx`, `bm`), tablas (`booktabs`, `tabularx`), gráficos (`graphicx`, `pgfplots` con `\\pgfplotsset{compat=1.18}`) y navegación (`hyperref` + `cleveref`). Hay un **orden** que importa: `hyperref` va **casi al final** y `cleveref` **después** de él (es la única excepción a “hyperref último”).',
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Dos errores típicos: **(1)** cargar `amsmath` *y* `mathtools` a la vez (mathtools ya incluye amsmath; cargá solo `mathtools`); **(2)** poner `cleveref` antes que `hyperref` (tiene que ir después). Y recordá: `[spanish]{babel}` sin `es-noshorthands` es media configuración.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Tené tu **base guardada** y arrancá cada documento copiándola; después sacás lo que no uses. “Base máxima” no significa cargar todo siempre, sino el **superconjunto recomendado** del que elegís el subconjunto que el contenido pide.',
        },
      ],
      example: [
        '\\documentclass[11pt,a4paper]{article}',
        '',
        '% ── PISO (siempre, en español) ──',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{csquotes}',
        '',
        '% ── EXTRA: solo lo que este documento usa ──',
        '\\usepackage{mathtools}   % superconjunto de amsmath',
        '\\usepackage{amssymb}     % \\mathbb, \\leq, ...',
        '\\usepackage{amsthm}      % entornos de teorema',
        '\\usepackage{siunitx}     % \\num, \\qty',
        '\\usepackage[a4paper,margin=2.5cm]{geometry}',
        '',
        '% ── Navegación: hyperref casi al final; cleveref DESPUÉS ──',
        '\\usepackage[hidelinks]{hyperref}',
        '\\usepackage[spanish,capitalise,nameinlink]{cleveref}',
        '',
        '\\theoremstyle{plain}',
        '\\newtheorem{teo}{Teorema}[section]',
        '\\DeclareMathOperator{\\sen}{sen}',
        '',
        '\\begin{document}',
        '',
        '\\section{Una base que se usa}',
        'La regla de oro: cargá el \\emph{piso} siempre y lo demás \\enquote{según lo',
        'que el contenido pida}. Acá usamos cada paquete que cargamos.',
        '',
        '\\begin{teo}\\label{teo:no-negativo}',
        '  Para todo $x \\in \\mathbb{R}$ se cumple $x^2 \\ge 0$.',
        '\\end{teo}',
        '',
        'Por el \\cref{teo:no-negativo}, si $x = \\num{3}$ entonces $x^2 = \\num{9} \\ge 0$.',
        'Además $\\sen(\\pi/2) = 1$.',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt:
          'Completá el PISO de este preámbulo en español: faltan fontenc T1, lmodern, babel con es-noshorthands y microtype. El cuerpo ya usa acentos y \\enquote.',
        starter: [
          '\\documentclass[11pt,a4paper]{article}',
          '\\usepackage{csquotes}',
          '% TODO: agregá el PISO (fontenc T1, lmodern, babel[spanish,es-noshorthands], microtype).',
          '',
          '\\begin{document}',
          'Función, árbol, pingüino. Una cita: \\enquote{el piso va siempre}.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: [
          '[T1]{fontenc}',
          '\\usepackage{lmodern}',
          'es-noshorthands]{babel}',
          '\\usepackage{microtype}',
        ],
        hints: [
          'El PISO son cuatro líneas; cargá fontenc antes que babel.',
          'babel canónico: \\usepackage[spanish,es-noshorthands]{babel}.',
        ],
        solution: [
          '\\documentclass[11pt,a4paper]{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{csquotes}',
          '',
          '\\begin{document}',
          'Función, árbol, pingüino. Una cita: \\enquote{el piso va siempre}.',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Idioma y codificación', 'Matemática con amsmath', 'Tablas con booktabs'],
    },
    {
      id: 'l1-tipografia',
      level: 1,
      title: 'Énfasis y tipografía',
      capa: 'carpinteria',
      module: 'Configuración',
      objective: 'resaltar texto con negrita y énfasis, y mejorar el gris tipográfico.',
      prerequisites: ['l0-estructura-texto'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Para resaltar, separá el **qué** del **cómo**: en vez de “poné cursiva”, decí “esto va con énfasis”. Por eso `\\emph` es preferible a `\\textit`: es semántico y, además, **alterna** (si anidás énfasis dentro de énfasis, vuelve a redonda para que se note).',
        },
        {
          kind: 'prose',
          markdown:
            'Por dentro, una fuente tiene tres ejes independientes que se combinan: **familia** (con serifa `\\textrm`, palo seco `\\textsf`, monoespacio `\\texttt`), **serie** (peso: normal o negrita `\\textbf`) y **forma** (redonda, cursiva `\\textit`, versalita `\\textsc`). Cada `\\textXX{...}` afecta a su argumento; para tramos largos existe la forma **declarativa** (`\\bfseries`, `\\itshape`), que se acota con llaves `{\\bfseries ...}`.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\textbf{...}', desc: 'Negrita.' },
            { cmd: '\\emph{...}', desc: 'Énfasis (recomendado: alterna si se anida).' },
            { cmd: '\\textit{...}', desc: 'Cursiva “a la fuerza”, sin semántica.' },
            { cmd: '\\textsc{...}', desc: 'Versalitas (small caps), útil para siglas.' },
            { cmd: '\\texttt{...}', desc: 'Monoespaciada, para código o nombres de archivo.' },
            { cmd: '\\small \\large \\Large \\huge', desc: 'Tamaños relativos (declaraciones; acotalos con llaves).' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'No abuses del resaltado: si todo está en negrita, nada resalta. Evitá subrayar (`\\underline`) para enfatizar (es herencia de la máquina de escribir). Y nunca uses los comandos viejos `\\bf`, `\\it`, `\\rm`: son obsoletos (los vemos en “Anti-patrones”).',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Buenas prácticas: preferí `\\emph` sobre `\\textit`, usá `\\textsc` para siglas (UNESCO) y `\\texttt` para nombres de archivo, y cargá `microtype` en **todos** tus documentos: es casi gratis y mejora el gris de la página.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}   % mejora sutil del gris y la justificación',
        '',
        '\\begin{document}',
        '',
        'Esto es \\textbf{importante}, esto va con \\emph{énfasis}, y notá cómo',
        '\\emph{el énfasis \\emph{anidado} alterna a redonda} para distinguirse.',
        '',
        'Versalitas para siglas: \\textsc{unesco}. Monoespaciada para un archivo:',
        '\\texttt{informe.tex}.',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá la oración usando \\textbf para una palabra y \\emph para otra.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '% TODO: resaltá la palabra clave con \\textbf y la palabra contexto con \\emph.',
          'La palabra clave es decisiva, pero el contexto la define.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\textbf', '\\emph'],
        hints: ['\\textbf{texto} para negrita; \\emph{texto} para énfasis.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          'La palabra \\textbf{clave} es decisiva, pero el \\emph{contexto} la define.',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Diseño de página y párrafos'],
    },
    {
      id: 'l1-diseno-pagina',
      level: 1,
      title: 'Diseño de página y párrafos',
      capa: 'carpinteria',
      module: 'Configuración',
      objective: 'ajustar márgenes, el espaciado entre párrafos y el interlineado.',
      prerequisites: ['l1-preambulo'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Tres palancas de carpintería: **geometry** (márgenes y papel), **parskip** (separar párrafos con espacio en vez de sangría) y **setspace** (interlineado 1,5 o doble). No toques `\\textwidth` ni `\\hoffset` a mano: geometry coordina todo de forma consistente.',
        },
        {
          kind: 'prose',
          markdown:
            'Por defecto, LaTeX **sangra** la primera línea de cada párrafo (estilo libro/paper) y no deja espacio entre ellos: así marca dónde empieza uno nuevo sin gastar lugar. `parskip` cambia ese estilo al de **informe** (sin sangría, con un espacio entre párrafos). Son dos convenciones válidas; elegí una y **no las mezcles**.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\usepackage[a4paper,margin=2.5cm]{geometry}', desc: 'Papel y márgenes consistentes.' },
            { cmd: '\\usepackage{parskip}', desc: 'Párrafos separados por espacio (look “moderno”, sin sangría).' },
            { cmd: '\\usepackage{setspace}', desc: 'Habilita comandos de interlineado.' },
            { cmd: '\\onehalfspacing', desc: 'Interlineado 1,5 (o \\doublespacing).' },
            { cmd: '\\newgeometry / \\restoregeometry', desc: 'Cambiar el margen en una zona puntual (apaisado, etc.).' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Si la cátedra pide “interlineado doble y márgenes de 3 cm”, eso es **carpintería**: se resuelve con `geometry` y `setspace`, no metiendo `\\vspace` o `\\\\` a mano entre párrafos. Forzar el espaciado renglón por renglón es frágil y se nota.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Definí la geometría **una vez** en el preámbulo y no la “corrijas” página por página: la consistencia es lo que hace que un documento se vea profesional.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage[a4paper,margin=2.5cm]{geometry} % papel y márgenes',
        '\\usepackage{parskip}                         % párrafos con espacio, sin sangría',
        '\\usepackage{setspace}',
        '\\onehalfspacing                              % interlineado 1,5',
        '',
        '\\begin{document}',
        '\\section{Con diseño a medida}',
        'A4, 2,5 cm de margen, interlineado 1,5 y párrafos separados por espacio.',
        '',
        'Este segundo párrafo no lleva sangría: se distingue por el espacio vertical',
        'que dejó parskip. Todo coordinado desde el preámbulo.',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Cargá geometry con un margen y parskip para separar los párrafos por espacio.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '% TODO: cargá geometry con margin=2.5cm y luego parskip.',
          '',
          '\\begin{document}',
          'Primer párrafo.',
          '',
          'Segundo párrafo, que debería separarse con espacio.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['{geometry}', '{parskip}'],
        hints: ['\\usepackage[margin=2.5cm]{geometry} y \\usepackage{parskip}.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage[margin=2.5cm]{geometry}',
          '\\usepackage{parskip}',
          '',
          '\\begin{document}',
          'Primer párrafo.',
          '',
          'Segundo párrafo, separado por espacio.',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Encabezados y pies', 'Documentos largos'],
    },
    {
      id: 'l1-fancyhdr',
      level: 1,
      title: 'Encabezados y pies',
      capa: 'carpinteria',
      module: 'Configuración',
      objective: 'poner encabezados y pies de página personalizados.',
      prerequisites: ['l1-diseno-pagina'],
      content: [
        {
          kind: 'prose',
          markdown:
            'El paquete **fancyhdr** controla el encabezado y el pie. Activás su estilo con `\\pagestyle{fancy}` y definís qué va a la izquierda `[L]`, al centro `[C]` y a la derecha `[R]`. Conviene empezar con `\\fancyhf{}` para **limpiar** los valores por defecto.',
        },
        {
          kind: 'prose',
          markdown:
            'Más allá de texto fijo, el encabezado puede mostrar **lo que cambia con la página**: `\\leftmark` trae el título de la sección (o capítulo) actual y `\\rightmark` el de la subsección —ideal para que el lector sepa siempre en qué parte está—. La línea bajo el encabezado se regula con `\\renewcommand{\\headrulewidth}{0.4pt}` (ponela en `0pt` para sacarla).',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\usepackage{fancyhdr}', desc: 'Carga el paquete.' },
            { cmd: '\\pagestyle{fancy}', desc: 'Activa encabezado/pie personalizados.' },
            { cmd: '\\fancyhf{}', desc: 'Limpia encabezado y pie antes de definirlos.' },
            { cmd: '\\fancyhead[L]{...}', desc: 'Encabezado izquierdo (L/C/R).' },
            { cmd: '\\fancyfoot[C]{\\thepage}', desc: 'Pie central con el número de página.' },
            { cmd: '\\leftmark / \\rightmark', desc: 'Título de la sección/subsección actual.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Si no llamás a `\\fancyhf{}` primero, fancyhdr deja su contenido por defecto (por ejemplo, el título de sección en el encabezado) y se mezcla con lo tuyo.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Para “Página X de Y”, el paquete `lastpage` da el total: `\\thepage\\ de \\pageref{LastPage}`. Y con clases KOMA (`scrartcl`, `scrreprt`) se usa `scrlayer-scrpage` en lugar de fancyhdr.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{fancyhdr}',
        '\\pagestyle{fancy}',
        '\\fancyhf{}                 % limpia encabezado y pie',
        '\\fancyhead[L]{Informe de laboratorio}',
        '\\fancyhead[R]{\\today}',
        '\\fancyfoot[C]{\\thepage}    % número de página, centrado en el pie',
        '',
        '\\begin{document}',
        '\\section{Resultados}',
        'Mirá el encabezado (a izquierda y derecha) y el pie con el número de página.',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Activá fancyhdr (\\pagestyle{fancy}) y poné un \\fancyfoot con el número de página.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{fancyhdr}',
          '% TODO: activá \\pagestyle{fancy} y definí \\fancyfoot[C]{\\thepage}.',
          '',
          '\\begin{document}',
          'Una página con pie personalizado.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\pagestyle{fancy}', '\\fancyfoot'],
        hints: ['\\fancyfoot[C]{\\thepage} pone el número centrado en el pie.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{fancyhdr}',
          '\\pagestyle{fancy}',
          '\\fancyhf{}',
          '\\fancyfoot[C]{\\thepage}',
          '',
          '\\begin{document}',
          'Una página con pie personalizado.',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Diseño de página y párrafos'],
    },
    // ── Módulo: Matemática ────────────────────────────────────────────────
    {
      id: 'l1-amsmath',
      level: 1,
      title: 'Matemática con amsmath',
      capa: 'semantica',
      module: 'Matemática',
      objective:
        'componer matemática profesional: elegir el entorno correcto, alinear y partir ecuaciones, y usar texto y fracciones grandes dentro de fórmulas.',
      prerequisites: ['l0-matematica-basica'],
      content: [
        {
          kind: 'prose',
          markdown:
            '**amsmath** es el paquete estándar de matemática: lo vas a cargar casi siempre. Sobre la base de `$...$` y `\\[ ... \\]`, agrega **entornos** para varias ecuaciones, mejor espaciado, numeración prolija y comandos como `\\text` o `\\dfrac`. (Y reemplaza a los viejos `$$...$$`, que **no** conviene usar.)',
        },
        {
          kind: 'prose',
          markdown:
            'La clave es **elegir el entorno según el caso**:\n\n- `equation` — **una** ecuación, numerada.\n- `align` — **varias** ecuaciones alineadas por un punto (el `=`).\n- `align*` — igual que align pero **sin numerar** (ideal para los pasos de una cuenta).\n- `gather` — varias ecuaciones **centradas**, sin alinear.\n- `multline` — **una** ecuación larga partida en varias líneas.\n- `cases` — definición **por tramos** (con la llave `{`).',
        },
        {
          kind: 'commands',
          title: 'Comandos y entornos clave',
          items: [
            { cmd: '\\begin{equation}', desc: 'Una ecuación numerada.' },
            { cmd: '\\begin{align} ... \\end{align}', desc: 'Varias ecuaciones; & alinea, \\\\ separa renglones.' },
            { cmd: '\\begin{align*}', desc: 'Igual, pero sin número.' },
            { cmd: '\\begin{gather}', desc: 'Ecuaciones centradas (sin punto de alineación).' },
            { cmd: '\\begin{cases}', desc: 'Definición por casos.' },
            { cmd: '\\text{...}', desc: 'Texto normal dentro del modo math.' },
            { cmd: '\\dfrac{a}{b}', desc: 'Fracción “display” (grande), aun en línea.' },
            { cmd: '\\intertext{...}', desc: 'Una línea de texto entre ecuaciones alineadas.' },
          ],
        },
        {
          kind: 'code',
          caption: 'align: alinear por el = (cada renglón termina en \\\\, menos el último)',
          latex: ['\\begin{align}', '  (a+b)^2 &= a^2 + 2ab + b^2 \\\\', '          &= a^2 + b^2 + 2ab', '\\end{align}'].join('\n'),
        },
        {
          kind: 'code',
          caption: 'gather (centradas) y cases (por tramos)',
          latex: ['\\begin{gather}', '  a = b + c \\\\', '  x = y', '\\end{gather}', '', '\\[ |x| = \\begin{cases} x & \\text{si } x \\ge 0 \\\\ -x & \\text{si } x < 0 \\end{cases} \\]'].join('\n'),
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Errores comunes: usar `$$...$$` (obsoleto, rompe el espaciado); poner `&` en `equation` (el `&` es solo de `align`); y olvidar que **cada renglón** de un `align` termina en `\\\\` **salvo el último**.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Buenas prácticas: usá `\\text{...}` para palabras dentro de una fórmula (si no, salen en cursiva como producto de variables); `\\dfrac` cuando querés la fracción grande; y para los pasos de una cuenta, `align*` (sin números que distraigan).',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{amsmath}',
        '',
        '\\begin{document}',
        '',
        '% (1) Una ecuación numerada',
        '\\begin{equation}',
        '  E = mc^2',
        '\\end{equation}',
        '',
        '% (2) Varias ecuaciones alineadas por el =',
        '\\begin{align}',
        '  (a+b)^2 &= a^2 + 2ab + b^2 \\\\',
        '          &= a^2 + b^2 + 2ab',
        '\\end{align}',
        '',
        '% (3) Pasos de una cuenta, sin numerar',
        '\\begin{align*}',
        '  f(x)  &= x^2 + 1 \\\\',
        '  f\'(x) &= 2x',
        '\\end{align*}',
        '',
        '% (4) Centradas, sin alinear',
        '\\begin{gather}',
        '  a = b + c \\\\',
        '  x = y',
        '\\end{gather}',
        '',
        '% (5) Por casos, con texto dentro del math',
        '\\[',
        '  |x| =',
        '  \\begin{cases}',
        '    x  & \\text{si } x \\ge 0 \\\\',
        '    -x & \\text{si } x < 0',
        '  \\end{cases}',
        '\\]',
        '',
        '% (6) Fracción grande e \\intertext entre ecuaciones',
        '\\begin{align*}',
        '  S  &= \\dfrac{n(n+1)}{2} \\\\',
        '  \\intertext{y por lo tanto}',
        '  2S &= n(n+1).',
        '\\end{align*}',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt:
          'Completá los dos huecos marcados con TODO: (1) agregá una segunda línea alineada en el align, y (2) definí el valor absoluto por casos con cases.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{amsmath}',
          '',
          '\\begin{document}',
          '% Completá donde dice TODO.',
          '',
          '% (1) Segunda línea de la cuenta, alineada por el =',
          '\\begin{align*}',
          '  (x+1)^2 &= x^2 + 2x + 1 \\\\',
          '          % TODO: otra línea alineada, p. ej.  &= x^2 + 1 + 2x',
          '\\end{align*}',
          '',
          '% (2) Valor absoluto por casos',
          '\\[',
          '  |x| =  % TODO: usá \\begin{cases} ... \\end{cases}',
          '\\]',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\begin{cases}', '\\end{cases}'],
        hints: [
          'La segunda línea del align también empieza con &= y va después de \\\\.',
          'cases: \\begin{cases} x & \\text{si } x \\ge 0 \\\\ -x & \\text{si } x < 0 \\end{cases}.',
        ],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{amsmath}',
          '',
          '\\begin{document}',
          '\\begin{align*}',
          '  (x+1)^2 &= x^2 + 2x + 1 \\\\',
          '          &= x^2 + 1 + 2x',
          '\\end{align*}',
          '',
          '\\[',
          '  |x| =',
          '  \\begin{cases}',
          '    x  & \\text{si } x \\ge 0 \\\\',
          '    -x & \\text{si } x < 0',
          '  \\end{cases}',
          '\\]',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Símbolos, alfabetos y operadores', 'Teoremas y demostraciones'],
    },
    {
      id: 'l1-simbolos-operadores',
      level: 1,
      title: 'Símbolos, alfabetos y operadores',
      capa: 'semantica',
      module: 'Matemática',
      objective: 'usar alfabetos especiales y operadores con nombre correctamente.',
      prerequisites: ['l1-amsmath'],
      content: [
        {
          kind: 'prose',
          markdown:
            'La matemática tiene **alfabetos especiales** (conjuntos como ℝ con `\\mathbb`, letras caligráficas con `\\mathcal`) y **operadores con nombre** (`\\sin`, `\\lim`, `\\log`) que se componen distinto del texto en cursiva. Para un operador propio que no exista, está `\\operatorname{...}`.',
        },
        {
          kind: 'prose',
          markdown:
            'En **español** muchos nombres no existen como comando: `sen`, `tg`, `arcsen`. La forma correcta es **declararlos una vez** en el preámbulo con `\\DeclareMathOperator{\\sen}{sen}` (de `amsmath`): salen en redonda y con el espaciado bien. Es una macro semántica más, como las del Nivel 2.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\mathbb{R}', desc: 'Conjuntos “de pizarra” ℝ, ℕ, ℤ (paquete amssymb).' },
            { cmd: '\\mathcal{F}', desc: 'Letras caligráficas.' },
            { cmd: '\\sin \\cos \\log \\lim', desc: 'Operadores con nombre (en redonda, bien espaciados).' },
            { cmd: '\\DeclareMathOperator{\\sen}{sen}', desc: 'Define operadores en redonda (en el preámbulo).' },
            { cmd: '\\operatorname{sinc}', desc: 'Operador con nombre propio al vuelo (uso puntual).' },
            { cmd: '\\mathbf{v} vs \\bm{v}', desc: 'Vector en negrita: \\bm respeta la cursiva matemática.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'No escribas `sin` o `lim` como texto en modo math: sale en cursiva, como producto de variables ($s\\cdot i\\cdot n$). Usá `\\sin`, `\\lim`. Y `\\mathbb` necesita `\\usepackage{amssymb}`.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Los grandes operadores ponen sus límites con `_` (abajo) y `^` (arriba): `\\sum_{k=1}^{n}`. En modo display salen arriba y abajo; en línea, al costado.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{amsmath}',
        '\\usepackage{amssymb}',
        '',
        '\\begin{document}',
        '',
        '% Operadores con nombre, gran operador y conjunto:',
        '\\[ \\lim_{n \\to \\infty} \\sum_{k=1}^{n} \\frac{1}{k^2} = \\frac{\\pi^2}{6}, \\qquad x \\in \\mathbb{R}. \\]',
        '',
        '% Letra caligráfica y un operador propio con \\operatorname:',
        '\\[ \\mathcal{F}(f)(\\xi) = \\int_{-\\infty}^{\\infty} f(x)\\, e^{-2\\pi i x \\xi}\\, dx, \\qquad \\operatorname{sinc}(x) = \\frac{\\sin x}{x}. \\]',
        '',
        '% Relaciones y una función entre conjuntos:',
        '\\[ a \\leq b \\neq c \\geq d, \\qquad f \\colon \\mathbb{N} \\to \\mathbb{R}. \\]',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Escribí una fórmula que use \\mathbb (un conjunto) y un gran operador como \\sum.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{amsmath}',
          '\\usepackage{amssymb}',
          '',
          '\\begin{document}',
          '% TODO: una fórmula en bloque con \\sum_{k=1}^{n} y un conjunto \\mathbb{R}.',
          '\\[  \\]',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\mathbb', '\\sum'],
        hints: ['\\mathbb{R} para los reales; \\sum_{k=1}^{n} para una sumatoria.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{amsmath}',
          '\\usepackage{amssymb}',
          '',
          '\\begin{document}',
          '\\[ \\sum_{k=1}^{n} k = \\frac{n(n+1)}{2}, \\qquad n \\in \\mathbb{N} \\subset \\mathbb{R}. \\]',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Matemática avanzada', 'Teoremas y demostraciones'],
    },
    {
      id: 'l1-siunitx',
      level: 1,
      title: 'Números y unidades (siunitx)',
      capa: 'semantica',
      module: 'Matemática',
      objective:
        'escribir números, cantidades físicas y unidades de forma consistente, y alinear columnas de números por el decimal.',
      prerequisites: ['l1-amsmath'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Escribir `10 m/s` a mano trae problemas: espaciado inconsistente, el número pegado a la unidad, y la coma vs. el punto decimal según el idioma. **siunitx** lo resuelve: vos declarás *el número* y *la unidad* por separado y el paquete los compone bien. Es el estándar para cualquier TP de física o cálculo numérico.',
        },
        {
          kind: 'commands',
          title: 'Comandos clave (siunitx v3)',
          items: [
            { cmd: '\\num{1234567}', desc: 'Número con separador de miles automático.' },
            { cmd: '\\num{6.022e23}', desc: 'Notación científica → 6,022 × 10²³.' },
            { cmd: '\\qty{10}{\\metre\\per\\second}', desc: 'Cantidad: número + unidad (antes era \\SI).' },
            { cmd: '\\unit{\\kilo\\gram}', desc: 'Solo la unidad, bien compuesta.' },
            { cmd: '\\sisetup{output-decimal-marker={,}}', desc: 'Coma decimal (configurá una vez).' },
            { cmd: 'columna S', desc: 'En tablas, alinea los números por el punto decimal.' },
          ],
        },
        {
          kind: 'code',
          caption: 'Tabla con la columna S: los números se alinean por el decimal',
          latex: [
            '\\begin{tabular}{l S}',
            '  \\toprule',
            '  Medición & {Valor (\\unit{\\metre})} \\\\',
            '  \\midrule',
            '  A & 1.5   \\\\',
            '  B & 12.42 \\\\',
            '  C & 305.1 \\\\',
            '  \\bottomrule',
            '\\end{tabular}',
          ].join('\n'),
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'En **siunitx v3** los comandos viejos `\\SI{...}{...}` y `\\si{...}` están **desaconsejados**: usá `\\qty` y `\\unit`. Y la unidad se arma con **macros** (`\\metre\\per\\second`), no escribiendo `m/s` como texto: así el espaciado y el formato salen siempre bien.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'En español, configurá la **coma decimal** una sola vez con `\\sisetup{output-decimal-marker={,}}`. En el encabezado de una columna `S`, poné el texto entre llaves (`{Valor}`) para que no intente alinearlo como número.',
        },
      ],
      example: [
        '\\documentclass[11pt,a4paper]{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{amsmath}',
        '\\usepackage{siunitx}',
        '\\usepackage{booktabs}',
        '\\sisetup{output-decimal-marker={,}}   % coma decimal (español)',
        '',
        '\\begin{document}',
        '',
        '\\section{Números}',
        'Separador de miles automático: \\num{1234567}.',
        'Notación científica: \\num{6.022e23}.',
        '',
        '\\section{Cantidades con unidad}',
        'La velocidad de la luz es \\qty{299792458}{\\metre\\per\\second}.',
        'El caudal medido fue de \\qty{250}{\\litre\\per\\minute} a \\qty{20}{\\celsius}.',
        '',
        '\\section{Tabla alineada por el decimal}',
        '\\begin{table}[h]',
        '  \\centering',
        '  \\begin{tabular}{l S}',
        '    \\toprule',
        '    Medición & {Valor (\\unit{\\metre})} \\\\',
        '    \\midrule',
        '    A & 1.5   \\\\',
        '    B & 12.42 \\\\',
        '    C & 305.1 \\\\',
        '    \\bottomrule',
        '  \\end{tabular}',
        '\\end{table}',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt:
          'Completá los dos TODO: (1) escribí una cantidad con \\qty (p. ej. 9,8 m/s²), y (2) formateá un número grande con \\num.',
        starter: [
          '\\documentclass[11pt,a4paper]{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{siunitx}',
          '\\sisetup{output-decimal-marker={,}}',
          '',
          '\\begin{document}',
          '',
          '% (1) TODO: la aceleración de la gravedad, con \\qty{...}{\\metre\\per\\second\\squared}',
          'La gravedad vale ',
          '',
          '% (2) TODO: un millón, con \\num{...}',
          'La población es de ',
          '',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\usepackage{siunitx}', '\\qty{', '\\num{'],
        hints: [
          'Cantidad: \\qty{9.8}{\\metre\\per\\second\\squared}.',
          'Número: \\num{1000000} sale con separador de miles.',
        ],
        solution: [
          '\\documentclass[11pt,a4paper]{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{siunitx}',
          '\\sisetup{output-decimal-marker={,}}',
          '',
          '\\begin{document}',
          '',
          'La gravedad vale \\qty{9.8}{\\metre\\per\\second\\squared}.',
          '',
          'La población es de \\num{1000000} habitantes.',
          '',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Tablas con booktabs', 'Matemática avanzada'],
    },
    // ── Módulo: Elementos ─────────────────────────────────────────────────
    {
      id: 'l1-tablas',
      level: 1,
      title: 'Tablas con booktabs',
      capa: 'semantica',
      module: 'Elementos',
      objective: 'armar tablas legibles con tabular y reglas profesionales.',
      prerequisites: ['l0-listas'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Las tablas van en `tabular`, que recibe una **especificación de columnas**: `l` (izquierda), `c` (centrada), `r` (derecha). El `&` separa **celdas** y `\\\\` separa **filas**. Para que se vean profesionales, usá **booktabs** y sus tres reglas.',
        },
        {
          kind: 'prose',
          markdown:
            'Tres tipos de columna más, muy útiles: `p{3cm}` hace una columna de ancho fijo donde el **texto se acomoda en varias líneas** (las `l/c/r` no parten el texto); `@{}` al principio o final **quita el espacio sobrante** del borde; y para repetir, `*{3}{c}` equivale a `ccc`. La filosofía de booktabs es “tabla de libro”: aire y reglas horizontales finas, **nunca** una grilla.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\begin{tabular}{lrr}', desc: 'Tres columnas: una a la izquierda y dos a la derecha.' },
            { cmd: '\\toprule / \\midrule / \\bottomrule', desc: 'Reglas horizontales de booktabs (arriba, medio, abajo).' },
            { cmd: '&  y  \\\\', desc: 'Separan celdas (&) y filas (\\\\).' },
            { cmd: '\\multicolumn{2}{c}{...}', desc: 'Una celda que abarca varias columnas.' },
            { cmd: 'p{3cm}', desc: 'Columna de ancho fijo, con texto que se acomoda en varias líneas.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Regla de oro: **nunca líneas verticales** ni `\\hline`, solo las horizontales de booktabs. Si una tabla “pide” verticales, casi siempre necesita más aire o menos columnas.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Alineá los números a la **derecha** (`r`), o mejor por el **decimal** con la columna `S` de `siunitx`. Si la tabla es muy ancha, que las columnas se ajusten solas con `tabularx` (próxima lección). Una tabla con datos va dentro de un flotante `table` con `\\caption` y `\\label`.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{booktabs}',
        '',
        '\\begin{document}',
        '\\begin{tabular}{lrr}',
        '  \\toprule',
        '  Producto & Cantidad & Precio \\\\',
        '  \\midrule',
        '  Café  & 12 & 100 \\\\',
        '  Té    &  8 &  80 \\\\',
        '  Agua  & 20 &  50 \\\\',
        '  \\midrule',
        '  Total & 40 & 230 \\\\',
        '  \\bottomrule',
        '\\end{tabular}',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá la tabla: agregá las filas de datos y las tres reglas de booktabs (\\toprule, \\midrule, \\bottomrule).',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{booktabs}',
          '',
          '\\begin{document}',
          '\\begin{tabular}{lr}',
          '  % TODO: \\toprule, una fila de encabezado, \\midrule, dos filas y \\bottomrule.',
          '\\end{tabular}',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\begin{tabular}', '\\toprule', '\\midrule', '\\bottomrule'],
        hints: ['{lr} crea dos columnas. Separá celdas con & y filas con \\\\.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{booktabs}',
          '',
          '\\begin{document}',
          '\\begin{tabular}{lr}',
          '  \\toprule',
          '  Ítem & Precio \\\\',
          '  \\midrule',
          '  Café & 100 \\\\',
          '  Té   & 80 \\\\',
          '  \\bottomrule',
          '\\end{tabular}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Tablas que se adaptan'],
    },
    {
      id: 'l1-tablas-adaptables',
      level: 1,
      title: 'Tablas que se adaptan',
      capa: 'carpinteria',
      module: 'Elementos',
      objective: 'hacer tablas que ajustan el ancho, combinan celdas o cruzan páginas.',
      prerequisites: ['l1-tablas'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Tres herramientas según el problema: **tabularx** (una columna `X` que se estira al ancho disponible, ideal para texto largo), **multirow** (combinar varias filas en una celda) y **longtable** (tablas que cruzan páginas).',
        },
        {
          kind: 'prose',
          markdown:
            'La columna `X` queda justificada por defecto; para alinearla distinto usás `>{\\raggedright\\arraybackslash}X` (texto a la izquierda sin justificar). En una `longtable`, marcás la fila de encabezado con `\\endhead` para que **se repita en cada página**. Y si querés filas alternadas (cebra), `\\rowcolors{2}{gray!10}{white}` (paquete `xcolor` con `[table]`).',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\begin{tabularx}{\\linewidth}{lX}', desc: 'La columna X absorbe el ancho sobrante.' },
            { cmd: '>{\\raggedright\\arraybackslash}X', desc: 'Columna X alineada a la izquierda.' },
            { cmd: '\\multirow{2}{*}{texto}', desc: 'Combina 2 filas en una celda (paquete multirow).' },
            { cmd: '\\begin{longtable}{...} ... \\endhead', desc: 'Tabla multipágina; \\endhead repite el encabezado.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'En `tabularx`, el ancho total (`\\linewidth`) es obligatorio, y necesitás **al menos una** columna `X` para que haya algo que estirar. Sin `X`, usá `tabular` normal.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Combiná siempre con `booktabs`. Para texto largo que no entra, `tabularx` con una columna `X` evita que la tabla se desborde de la página.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{tabularx}',
        '\\usepackage{multirow}',
        '\\usepackage{booktabs}',
        '',
        '\\begin{document}',
        '\\begin{tabularx}{\\linewidth}{l l X}',
        '  \\toprule',
        '  Grupo & Campo & Descripción \\\\',
        '  \\midrule',
        '  \\multirow{2}{*}{Datos} & Nombre & Texto largo que se ajusta solo al ancho disponible de la página. \\\\',
        '                         & Fecha  & Segunda fila del mismo grupo, combinado en la primera columna. \\\\',
        '  \\bottomrule',
        '\\end{tabularx}',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Hacé una tabla con tabularx que tenga una columna X (la que se estira).',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{tabularx}',
          '\\usepackage{booktabs}',
          '',
          '\\begin{document}',
          '% TODO: \\begin{tabularx}{\\linewidth}{l X} con un encabezado y una fila.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\begin{tabularx}', 'X'],
        hints: ['\\begin{tabularx}{\\linewidth}{l X} crea una columna fija y una elástica.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{tabularx}',
          '\\usepackage{booktabs}',
          '',
          '\\begin{document}',
          '\\begin{tabularx}{\\linewidth}{l X}',
          '  \\toprule',
          '  Campo & Descripción \\\\',
          '  \\midrule',
          '  Nombre & Texto que se ajusta al ancho disponible de la página. \\\\',
          '  \\bottomrule',
          '\\end{tabularx}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Tablas con booktabs', 'Tabla de datos agrupados'],
    },
    {
      id: 'l1-figuras',
      level: 1,
      title: 'Figuras e imágenes',
      capa: 'semantica',
      module: 'Elementos',
      objective: 'insertar una figura centrada y con leyenda.',
      prerequisites: ['l1-preambulo'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Una figura es un **objeto flotante**: va en el entorno `figure` y LaTeX la ubica donde quede mejor. La imagen se inserta con `\\includegraphics` (paquete **graphicx**) y la leyenda con `\\caption`. El `\\label` (después del caption) permite referenciarla por número.',
        },
        {
          kind: 'prose',
          markdown:
            'Elegí bien el **formato**: lo **vectorial** (un PDF exportado, o un gráfico TikZ/pgfplots) no se pixela al hacer zoom —ideal para diagramas y funciones—; lo **raster** (PNG, JPG) es solo para **fotos**. `\\includegraphics` acepta opciones como `width=0.6\\linewidth`, `scale=0.5` o `angle=90`; lo más robusto es dar el **ancho relativo a `\\linewidth`** para que la figura se adapte al texto.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\usepackage{graphicx}', desc: 'Habilita \\includegraphics.' },
            { cmd: '\\begin{figure}[htbp]', desc: 'Entorno flotante; las letras sugieren ubicaciones.' },
            { cmd: '\\centering', desc: 'Centra el contenido.' },
            { cmd: '\\includegraphics[width=0.6\\linewidth]{archivo}', desc: 'Inserta una imagen escalada.' },
            { cmd: '\\caption{...}', desc: 'Leyenda numerada (va antes del \\label).' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'El `\\label` de una figura debe ir **después** del `\\caption`; si no, referenciará el número equivocado. Y `\\includegraphics` necesita un **archivo de imagen** presente (graphicx lo busca por nombre, incluso sin extensión).',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'El `[htbp]` (here/top/bottom/page) es una **sugerencia** de ubicación: no pelees moviendo la figura a mano, dejá que flote y referenciala con `\\cref`. Si de verdad necesitás “exactamente acá”, `\\begin{figure}[H]` (paquete `float`) lo fuerza —pero usalo con moderación.',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            'Este ejemplo trae una **imagen de verdad** (`grafico.png`, en el panel de Archivos) y la inserta con `\\includegraphics`. En tus proyectos podés **subir tus propias imágenes** desde Mis Proyectos y usarlas igual.',
        },
      ],
      mainFile: 'main.tex',
      files: [{ path: 'grafico.png', content: FIGURA_PNG, encoding: 'base64' }],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{graphicx}',
        '',
        '\\begin{document}',
        '\\begin{figure}[h]',
        '  \\centering',
        '  \\includegraphics[width=0.6\\linewidth]{grafico.png}',
        '  \\caption{Una figura de ejemplo (imagen real), centrada y con leyenda.}',
        '  \\label{fig:demo}',
        '\\end{figure}',
        '',
        'El texto sigue normalmente; LaTeX ubicó la figura donde mejor cae.',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Insertá la imagen grafico.png (ya está en el proyecto) en una figure centrada y con \\caption.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{graphicx}',
          '',
          '\\begin{document}',
          '% El archivo grafico.png ya está en el proyecto.',
          '% TODO: una figure[h] con \\centering, \\includegraphics{grafico.png} y \\caption.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\begin{figure}', '\\centering', '\\includegraphics', '\\caption'],
        hints: ['\\includegraphics[width=0.6\\linewidth]{grafico.png} dentro de la figure.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{graphicx}',
          '',
          '\\begin{document}',
          '\\begin{figure}[h]',
          '  \\centering',
          '  \\includegraphics[width=0.6\\linewidth]{grafico.png}',
          '  \\caption{Figura de ejemplo.}',
          '\\end{figure}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Flotantes y subfiguras', 'Graficar funciones (pgfplots)'],
    },
    {
      id: 'l1-flotantes-subfiguras',
      level: 1,
      title: 'Flotantes y subfiguras',
      capa: 'carpinteria',
      module: 'Elementos',
      objective: 'controlar dónde van las figuras y poner varias subfiguras juntas.',
      prerequisites: ['l1-figuras'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Los **flotantes** (`figure`, `table`) los ubica LaTeX; con `[htbp]` sugerís *here/top/bottom/page* y con `[H]` (paquete **float**) los forzás “acá”. Con **subcaption** ponés varias **subfiguras**, cada una con su letra (a), (b), separadas por `\\hfill`.',
        },
        {
          kind: 'prose',
          markdown:
            'Existen porque mover una figura un poco arriba o abajo evita **huecos** y figuras huérfanas: el texto fluye mejor. Si se te **acumulan** flotantes (aparecen todos juntos más adelante), forzá su salida con `\\clearpage` o, más fino, `\\FloatBarrier` (paquete `placeins`). Para darle estilo a las leyendas (negrita, más chicas) está el paquete `caption`.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\usepackage{float}  →  [H]', desc: 'Forzar la posición exacta del flotante.' },
            { cmd: '\\usepackage{subcaption}', desc: 'Habilita el entorno subfigure.' },
            { cmd: '\\begin{subfigure}{0.45\\linewidth}', desc: 'Una subfigura con su \\caption.' },
            { cmd: '\\hfill', desc: 'Empuja las subfiguras a los extremos (las separa).' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'No abuses de `[H]`: suele dejar huecos feos. Dejá que LaTeX ubique los flotantes salvo que de verdad necesites una posición. Y la suma de anchos de las subfiguras debe ser menor que `\\linewidth`.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Cada subfigura puede tener su propio `\\label` para referenciar “Figura 1a”. El `\\caption` general (de toda la `figure`) va al final, después de las subfiguras.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{graphicx}',
        '\\usepackage{float}',
        '\\usepackage{subcaption}',
        '',
        '\\begin{document}',
        '\\begin{figure}[H]   % H: justo acá (paquete float)',
        '  \\centering',
        '  \\begin{subfigure}{0.45\\linewidth}',
        '    \\centering \\fbox{\\rule{0pt}{2.5cm}\\rule{3cm}{0pt}}',
        '    \\caption{Primera}',
        '  \\end{subfigure}',
        '  \\hfill',
        '  \\begin{subfigure}{0.45\\linewidth}',
        '    \\centering \\fbox{\\rule{0pt}{2.5cm}\\rule{3cm}{0pt}}',
        '    \\caption{Segunda}',
        '  \\end{subfigure}',
        '  \\caption{Dos subfiguras lado a lado.}',
        '\\end{figure}',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Poné dos subfiguras dentro de una figure usando subcaption.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{subcaption}',
          '',
          '\\begin{document}',
          '\\begin{figure}[h]',
          '  \\centering',
          '  % TODO: dos \\begin{subfigure}{0.45\\linewidth} ... \\end{subfigure}, cada una con \\caption.',
          '  \\caption{Dos subfiguras.}',
          '\\end{figure}',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\begin{subfigure}', '\\caption'],
        hints: ['Cada subfigure lleva un ancho, por ej. {0.45\\linewidth}, y su propio \\caption.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{subcaption}',
          '',
          '\\begin{document}',
          '\\begin{figure}[h]',
          '  \\centering',
          '  \\begin{subfigure}{0.45\\linewidth}',
          '    \\centering \\fbox{\\rule{0pt}{2.5cm}\\rule{3cm}{0pt}}',
          '    \\caption{Primera}',
          '  \\end{subfigure}',
          '  \\hfill',
          '  \\begin{subfigure}{0.45\\linewidth}',
          '    \\centering \\fbox{\\rule{0pt}{2.5cm}\\rule{3cm}{0pt}}',
          '    \\caption{Segunda}',
          '  \\end{subfigure}',
          '  \\caption{Dos subfiguras.}',
          '\\end{figure}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Figuras e imágenes', 'Referencias cruzadas'],
    },
    // ── Módulo: Navegación ────────────────────────────────────────────────
    {
      id: 'l1-referencias',
      level: 1,
      title: 'Referencias cruzadas',
      capa: 'semantica',
      module: 'Navegación',
      objective: 'referenciar secciones o figuras por su número, sin escribirlo a mano.',
      prerequisites: ['l0-estructura-texto'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Nunca escribas “ver la Sección 2” a mano. Marcá con `\\label{clave}` y referenciá con `\\ref{clave}`: LaTeX pone el número correcto aunque reordenes. Con **cleveref** y `\\cref`, además agrega la palabra (“Sección 2”, “Figura 3”) sola.',
        },
        {
          kind: 'prose',
          markdown:
            '¿Por qué dos pasadas? En la primera, LaTeX **anota** en un archivo auxiliar (`.aux`) qué número le tocó a cada `\\label`; en la segunda, **lee** esos números y los inserta. Por eso, hasta la segunda, podés ver `??`. `latexmk` repite solo hasta que se estabiliza. Detalle útil: `\\Cref` (con mayúscula) va al **principio de una oración** (“La figura” → “Figura”), y `\\crefrange{a}{b}` arma rangos.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\label{sec:metodos}', desc: 'Marca el elemento anterior (sección, ecuación, figura).' },
            { cmd: '\\ref{sec:metodos}', desc: 'Inserta su número.' },
            { cmd: '\\cref{sec:metodos}', desc: 'Inserta tipo + número (paquete cleveref).' },
            { cmd: '\\Cref{...}', desc: 'Igual, pero con mayúscula (inicio de oración).' },
            { cmd: '\\eqref{eq:clave}', desc: 'Referencia a una ecuación, con paréntesis (amsmath).' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Las referencias necesitan **dos pasadas**: la primera vez podés ver `??`. Acá el backend ya hace las pasadas. Convención de prefijos: `sec:`, `fig:`, `tab:`, `eq:`, para saber a qué apunta cada clave.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Cargá `cleveref` **después** de `hyperref`. Y usá `~` (espacio duro) antes de un `\\ref` manual —`Sección~\\ref{...}`— para que el número no quede solo al inicio de un renglón.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{amsmath}',
        '\\usepackage{hyperref}',
        '\\usepackage{cleveref}',
        '',
        '\\begin{document}',
        '\\section{Métodos}\\label{sec:metodos}',
        'El procedimiento se detalla en esta sección.',
        '',
        '\\begin{equation}\\label{eq:clave}',
        '  E = mc^2',
        '\\end{equation}',
        '',
        'Como se ve en \\cref{sec:metodos} y por \\cref{eq:clave}, todo queda',
        'referenciado por número, sin escribirlo a mano.',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Poné un \\label en una \\section y referencialo con \\ref (o \\cref).',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{hyperref}',
          '',
          '\\begin{document}',
          '\\section{Métodos}% TODO: agregá \\label{sec:metodos} acá',
          'En la Sección~% TODO: referenciá con \\ref{sec:metodos}',
          ' explicamos el método.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\label', '\\ref'],
        hints: ['El \\label va pegado a la \\section que querés referenciar. \\cref también cuenta.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{hyperref}',
          '',
          '\\begin{document}',
          '\\section{Métodos}\\label{sec:metodos}',
          'En la Sección~\\ref{sec:metodos} explicamos el método.',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Enlaces y metadatos (hyperref)', 'Bibliografía y citas'],
    },
    {
      id: 'l1-hyperref',
      level: 1,
      title: 'Enlaces y metadatos (hyperref)',
      capa: 'infraestructura',
      module: 'Navegación',
      objective: 'volver el PDF navegable: enlaces, marcadores y metadatos.',
      prerequisites: ['l1-referencias'],
      content: [
        {
          kind: 'prose',
          markdown:
            '**hyperref** convierte referencias, citas y URLs en **enlaces clicables**, genera los **marcadores** (bookmarks) del PDF y define sus **metadatos** (título, autor). Es lo que hace que el PDF se navegue.',
        },
        {
          kind: 'prose',
          markdown:
            '¿Por qué casi al final? hyperref **redefine** muchos comandos internos (referencias, índice, citas) para hacerlos clicables; tiene que cargarse **después** de los paquetes que también los tocan, así los “parchea” bien. La excepción es `cleveref`, que va **después** de hyperref. Y en español, `\\hypersetup{unicode}` hace que los marcadores muestren bien los acentos y la “¿”.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\usepackage{hyperref}', desc: 'Activa enlaces, marcadores y metadatos.' },
            { cmd: '\\href{https://...}{texto}', desc: 'Enlace con texto visible.' },
            { cmd: '\\url{https://...}', desc: 'Muestra la URL como enlace.' },
            { cmd: '\\hypersetup{colorlinks, unicode, pdftitle=...}', desc: 'Estilo de enlaces y metadatos del PDF.' },
            { cmd: '\\autoref{clave}', desc: 'Referencia con tipo (alternativa simple a cleveref).' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Cargá `hyperref` **casi al final** del preámbulo (después de la mayoría de los paquetes); y `cleveref` después de `hyperref`. Cargarlo en mal orden causa errores raros.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Para que los enlaces no salgan con un recuadro de color (feo al imprimir), usá `colorlinks=true` o `hidelinks`. Y completá `pdftitle`/`pdfauthor`: son los metadatos que ve quien abre el PDF.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{xcolor}        % nombres de color extra (teal, etc.)',
        '\\usepackage{hyperref}',
        '\\hypersetup{',
        '  colorlinks=true,',
        '  linkcolor=blue,',
        '  urlcolor=teal,',
        '  pdftitle={Documento de ejemplo},',
        '  pdfauthor={Estudiante}',
        '}',
        '',
        '\\begin{document}',
        '\\section{Enlaces}',
        'Más info en \\href{https://www.latex-project.org}{el sitio de LaTeX}',
        'o directamente en \\url{https://ctan.org}.',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Cargá hyperref y poné un enlace con \\href (y, si querés, \\url).',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '% TODO: cargá \\usepackage{hyperref}.',
          '',
          '\\begin{document}',
          'Más info en % TODO: \\href{https://ctan.org}{CTAN}.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['{hyperref}', '\\href'],
        hints: ['\\href{url}{texto visible} o \\url{url}.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{hyperref}',
          '',
          '\\begin{document}',
          'Más info en \\href{https://ctan.org}{CTAN}.',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Referencias cruzadas', 'Índices, glosarios y nomenclatura'],
    },
  ],
} satisfies LevelInput
