import type { LevelInput } from '../types'

/** Nivel 4 · Avanzado — programación, flujo y entorno, salida, documentos especiales. */
export const nivel4 = {
  level: 4,
  title: 'Avanzado',
  summary: 'LaTeX como lenguaje (condicionales, expl3, otros lenguajes), flujo reproducible, accesibilidad y clases especiales.',
  lessons: [
    // ── Módulo: Programación ──────────────────────────────────────────────
    {
      id: 'l4-condicionales',
      level: 4,
      title: 'Compilación condicional',
      capa: 'infraestructura',
      module: 'Programación',
      objective: 'generar dos versiones (p. ej. con y sin soluciones) desde un mismo fuente.',
      prerequisites: ['l2-macros'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Un uso muy práctico: **una sola fuente, dos salidas**. Con `\\newif` creás una **bandera** (por ejemplo `\\ifsoluciones`) y mostrás u ocultás partes según su valor. Cambiás una línea y generás el examen del alumno o la versión con respuestas.',
        },
        {
          kind: 'prose',
          markdown:
            'El mismo patrón sirve para **borrador vs. final**, **pantalla vs. impresión** o variantes de un TP. La clave: poné la línea que fija la bandera (`\\solucionestrue`) **una sola vez, arriba del todo**, así cambiar de versión es tocar un carácter. Para ocultar **bloques grandes** enteros conviene el paquete `comment` (`\\begin{comment}...\\end{comment}`), y para condiciones más ricas, `\\ifthenelse` del paquete `ifthen`.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\newif\\ifsoluciones', desc: 'Crea la bandera (arranca en falso).' },
            { cmd: '\\solucionestrue / \\solucionesfalse', desc: 'La activa / desactiva.' },
            { cmd: '\\ifsoluciones ... \\fi', desc: 'Incluye el contenido solo si está activa.' },
            { cmd: '\\ifsoluciones ... \\else ... \\fi', desc: 'Una cosa u otra según el valor.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'El nombre de la bandera y el del condicional están ligados: `\\newif\\ifsoluciones` crea `\\soluciones`**true**/`\\soluciones`**false** (sin el `if`). Todo bloque condicional se cierra con `\\fi`; olvidarlo deja el documento “abierto” y da error al final.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Para algo más cómodo y legible, `etoolbox` ofrece `\\newtoggle{soluciones}`, `\\toggletrue{...}` y `\\iftoggle{soluciones}{sí}{no}`, sin la gimnasia de nombres de `\\newif`.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '',
        '\\newif\\ifsoluciones',
        '\\solucionestrue   % poné \\solucionesfalse para la versión del alumno',
        '',
        '\\begin{document}',
        '',
        '\\section*{Práctica 1}',
        '\\textbf{Ejercicio 1.} Calcular $2 + 2$.',
        '\\ifsoluciones',
        '  \\par\\textbf{Solución:} $2 + 2 = 4$.',
        '\\fi',
        '',
        '\\textbf{Ejercicio 2.} Derivar $f(x) = x^2$.',
        '\\ifsoluciones',
        '  \\par\\textbf{Solución:} $f\'(x) = 2x$.',
        '\\else',
        '  \\par\\textit{(Resolver.)}',
        '\\fi',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: definí una bandera con \\newif y mostrá una solución solo cuando esté activa, con \\ifsoluciones ... \\fi.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '% TODO (1): creá la bandera con \\newif\\ifsoluciones y activala con \\solucionestrue',
          '',
          '\\begin{document}',
          'Ejercicio: calcular $3 \\times 3$.',
          '% TODO (2): mostrá la solución (9) solo dentro de \\ifsoluciones ... \\fi',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\newif', '\\fi'],
        hints: ['Todo bloque condicional se cierra con \\fi.', '\\newif\\ifsoluciones en el preámbulo; \\solucionestrue lo activa.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\newif\\ifsoluciones',
          '\\solucionestrue',
          '',
          '\\begin{document}',
          'Ejercicio: calcular $3 \\times 3$.',
          '\\ifsoluciones',
          '  \\par\\textbf{Solución:} $9$.',
          '\\fi',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Programación: lógica y bucles'],
    },
    {
      id: 'l4-programacion',
      level: 4,
      title: 'Programación: lógica y bucles',
      capa: 'infraestructura',
      module: 'Programación',
      objective: 'automatizar contenido repetitivo con bucles.',
      prerequisites: ['l2-macros'],
      content: [
        {
          kind: 'prose',
          markdown:
            'LaTeX es **Turing-completo**: además de componer, *programa*. Para repetir contenido, `\\foreach` (del paquete `pgffor`, incluido con TikZ) recorre una lista o un rango. Es la forma más cómoda de generar tablas, grillas o figuras repetitivas sin copiar y pegar.',
        },
        {
          kind: 'prose',
          markdown:
            'Para **cuentas** hay dos vías: `\\the\\numexpr 3*4\\relax` (enteros) y, para decimales, `\\pgfmathparse{sqrt(2)}` con el resultado en `\\pgfmathresult`. Sirve para etiquetas calculadas o coordenadas. Pero ojo: TeX **no** es una calculadora científica; si necesitás procesar datos o cálculos serios, conviene **delegar** en Python o Lua (lo vemos en *Inyectar otros lenguajes*) y traer solo el resultado.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\usepackage{pgffor}', desc: 'Provee \\foreach (TikZ ya lo carga).' },
            { cmd: '\\foreach \\n in {1,...,5}{...}', desc: 'Bucle sobre un rango.' },
            { cmd: '\\foreach \\x in {a,b,c}{...}', desc: 'Bucle sobre una lista explícita.' },
            { cmd: '\\foreach \\i/\\v in {1/uno,2/dos}{...}', desc: 'Dos variables por iteración.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'La variable del bucle (`\\n`) **solo vive dentro** de las llaves del `\\foreach`. Afuera no existe. Y los rangos con `...` infieren el paso de los dos primeros valores: `{0,2,...,10}` va de a 2.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Dentro de `tikzpicture`, `\\foreach` es ideal para dibujar grillas, ejes o repetir nodos. Para lógica más estructurada (tipos, secuencias) está **expl3** (próxima lección).',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{pgffor}',
        '',
        '\\begin{document}',
        '',
        '% (1) Rango simple:',
        'Cuadrados: \\foreach \\n in {1,...,5}{$\\n^2=\\the\\numexpr\\n*\\n\\relax$\\quad}',
        '',
        '% (2) Dos variables por iteración (índice/valor):',
        '\\begin{itemize}',
        '  \\foreach \\i/\\v in {1/uno, 2/dos, 3/tres}{\\item Paso \\i: \\v.}',
        '\\end{itemize}',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: usá \\foreach para repetir algo sobre un rango de números (p. ej. del 1 al 5).',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{pgffor}',
          '',
          '\\begin{document}',
          'Números: % TODO: \\foreach \\n in {1,...,5}{$\\n$\\quad}',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\foreach'],
        hints: ['Ejemplo: \\foreach \\n in {1,...,5}{$\\n$ }.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{pgffor}',
          '',
          '\\begin{document}',
          'Números: \\foreach \\n in {1,...,5}{$\\n$\\quad}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['expl3: el LaTeX moderno', 'Compilación condicional'],
    },
    {
      id: 'l4-expl3',
      level: 4,
      title: 'expl3: el LaTeX moderno',
      capa: 'infraestructura',
      module: 'Programación',
      objective: 'escribir lógica con la capa de programación moderna de LaTeX.',
      prerequisites: ['l4-programacion'],
      content: [
        {
          kind: 'prose',
          markdown:
            '**expl3** (LaTeX3) es el lenguaje de programación moderno de LaTeX: variables **tipadas** (`\\tl` listas de tokens, `\\int` enteros, `\\seq` secuencias, `\\prop` diccionarios) y funciones con nombres **consistentes** (`\\modulo_accion:tipos`). El código va entre `\\ExplSyntaxOn` y `\\ExplSyntaxOff`.',
        },
        {
          kind: 'prose',
          markdown:
            'El sufijo `:tipos` de cada función describe **qué argumentos** toma: `N` un token suelto, `n` un grupo entre llaves, `V` el valor de una variable, `x` un argumento que se expande. Suena críptico, pero le da a expl3 una **expansión predecible** que evita los viejos “fragile commands”. Para exponer tus funciones como comandos de usuario, `\\NewDocumentCommand` con especificadores legibles: `m` (obligatorio), `O{def}` (opcional con default), `s` (estrella `*`). Paquetes modernos como `siunitx` están escritos así.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\ExplSyntaxOn ... \\ExplSyntaxOff', desc: 'Delimitan el código expl3 (el _ y : son parte de los nombres).' },
            { cmd: '\\int_eval:n { 2 * 3 }', desc: 'Evalúa una expresión entera.' },
            { cmd: '\\cs_new:Npn \\mi_func:n #1 {...}', desc: 'Define una función nueva.' },
            { cmd: '\\tl_set:Nn \\l_tmpa_tl { texto }', desc: 'Asigna a una variable “token list”.' },
            { cmd: '\\NewDocumentCommand', desc: 'Expone una función como comando de usuario.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Dentro de `\\ExplSyntaxOn`, el **espacio se ignora** (por eso el código respira) y `_`/`:` son letras válidas de nombres. Si querés un espacio literal en la salida, usás `~`. Olvidar `\\ExplSyntaxOff` rompe el texto normal que sigue.',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            'No necesitás cargar ningún paquete: expl3 ya es parte del núcleo del LaTeX moderno. La convención de nombres (`:n`, `:N`, `:Nn`) describe qué tipo de argumento espera cada función.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '',
        '\\ExplSyntaxOn',
        '% Una función que duplica un entero:',
        '\\NewDocumentCommand{\\doble}{m}{ \\int_eval:n { 2 * #1 } }',
        '% Una que suma dos enteros:',
        '\\NewDocumentCommand{\\suma}{mm}{ \\int_eval:n { #1 + #2 } }',
        '\\ExplSyntaxOff',
        '',
        '\\begin{document}',
        '',
        'El doble de 21 es \\doble{21}.',
        '',
        'Y $7 + 35 = \\suma{7}{35}$.',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: definí un comando con expl3 (entre \\ExplSyntaxOn y \\ExplSyntaxOff) que evalúe una cuenta con \\int_eval:n.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\ExplSyntaxOn',
          '% TODO: \\NewDocumentCommand{\\doble}{m}{ \\int_eval:n { 2 * #1 } }',
          '\\ExplSyntaxOff',
          '',
          '\\begin{document}',
          'El doble de 21 es % TODO: \\doble{21}.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\ExplSyntaxOn', '\\ExplSyntaxOff'],
        hints: ['Dentro podés usar \\int_eval:n y \\NewDocumentCommand.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\ExplSyntaxOn',
          '\\NewDocumentCommand{\\doble}{m}{ \\int_eval:n { 2 * #1 } }',
          '\\ExplSyntaxOff',
          '',
          '\\begin{document}',
          'El doble de 21 es \\doble{21}.',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Programación: lógica y bucles', 'Paquetes propios'],
    },
    {
      id: 'l4-inyectar',
      level: 4,
      title: 'Inyectar otros lenguajes',
      capa: 'infraestructura',
      module: 'Programación',
      objective: 'entender cómo ejecutar Python o Lua durante la compilación.',
      prerequisites: ['l4-programacion'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Para cálculos serios o gráficos generados, se puede **ejecutar código durante la compilación**: `pythontex` corre **Python** (ideal con SymPy/NumPy/Matplotlib) y **LuaLaTeX** trae **Lua** completo vía `\\directlua`. Así, un resultado numérico o una figura se generan en el momento, sin pegar valores a mano.',
        },
        {
          kind: 'prose',
          markdown:
            'La idea de fondo es la **programación literata** / investigación reproducible: el documento *es* la computación, así el texto y los números **no pueden desincronizarse** (si cambian los datos, recompilás y todo se actualiza). En el mismo ecosistema están `sagetex` (Sage), `knitr`/R con archivos `.Rnw`, y `gnuplottex`. El costo es más complejidad de compilación y necesitar `-shell-escape`, con su riesgo de seguridad —por eso acá está deshabilitado.',
        },
        {
          kind: 'code',
          caption: 'pythontex: corre Python y captura el resultado',
          latex: ['\\usepackage{pythontex}', '% ...', '\\py{2 + 2}              % imprime 4', '\\begin{pycode}', 'import sympy as sp', 'x = sp.symbols("x")', 'print(sp.integrate(x**2, x))', '\\end{pycode}'].join('\n'),
        },
        {
          kind: 'code',
          caption: 'Lua embebido, con el motor LuaLaTeX',
          latex: ['\\directlua{ tex.print(2 + 2) }'].join('\n'),
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Estas opciones **no compilan en este editor**: `pythontex` requiere `-shell-escape` y un Python instalado, y `\\directlua` requiere el motor **LuaLaTeX**. Por seguridad, el backend de la plataforma deshabilita `shell-escape`. El ejemplo cargable es, por eso, un documento normal.',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            'Cuándo conviene cada uno: `pythontex` si ya trabajás en Python (reusás tu código y librerías); `LuaLaTeX` si querés lógica embebida sin dependencias externas y un motor más moderno por defecto.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '',
        '\\begin{document}',
        '\\section{Calcular durante la compilación}',
        '',
        'Con \\texttt{pythontex} o \\texttt{LuaLaTeX} se ejecuta código y se capturan',
        'resultados o figuras \\emph{al compilar}: el documento y el cálculo viven juntos.',
        '',
        'Mirá los fragmentos de la lección para la sintaxis (requieren',
        '\\texttt{shell-escape} o el motor LuaLaTeX, no disponibles en este editor).',
        '\\end{document}',
        '',
      ].join('\n'),
      seeAlso: ['Graficar funciones (pgfplots)', 'Flujo reproducible'],
    },
    {
      id: 'l4-paquetes-propios',
      level: 4,
      title: 'Paquetes propios',
      capa: 'infraestructura',
      module: 'Programación',
      objective: 'empaquetar tu configuración para reutilizarla en todos tus documentos.',
      prerequisites: ['l2-macros'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Cuando repetís el mismo preámbulo en cada trabajo, **empaquetalo**. Agrupás tus definiciones en un archivo `.sty` propio y lo cargás con `\\usepackage{mi-paquete}`: es la base de un “estilo de cátedra” consistente, que cambiás en un solo lugar.',
        },
        {
          kind: 'prose',
          markdown:
            'Hay dos tipos de archivo: un **`.sty`** (paquete: *agrega* cosas, se carga con `\\usepackage` sobre una clase existente) y una **`.cls`** (clase: *define* un tipo de documento entero, se usa con `\\documentclass`). Empezá siempre por un `.sty`. Puede recibir **opciones** (con `\\DeclareOption`/`\\ProcessOptions`, o mejor `l3keys` en LaTeX moderno). Para usarlo solo en el proyecto, dejá el `.sty` **junto al `main.tex`**; para tenerlo en todos, va en tu árbol `texmf`.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\ProvidesPackage{mipaquete}[fecha desc]', desc: 'Cabecera de un archivo .sty propio.' },
            { cmd: '\\RequirePackage{...}', desc: 'Carga otros paquetes desde dentro del .sty.' },
            { cmd: '\\providecommand{\\x}{...}', desc: 'Define \\x solo si no existía (evita choques).' },
            { cmd: '\\NewDocumentCommand', desc: 'Comandos con argumentos ricos (LaTeX moderno).' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Dentro de un `.sty` se usa `\\RequirePackage` (no `\\usepackage`) para cargar dependencias. Y conviene `\\providecommand` sobre `\\newcommand`: si el comando ya existía, no rompe.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Acá `mipaquete.sty` es un **archivo real del proyecto** (panel de Archivos) que el documento carga con `\\usepackage{mipaquete}`. El paso previo es definir todo inline en el preámbulo; cuando se estabiliza, lo movés al `.sty` y queda reutilizable en todos tus documentos.',
        },
      ],
      mainFile: 'main.tex',
      files: [
        {
          path: 'mipaquete.sty',
          content: [
            '\\ProvidesPackage{mipaquete}[2024/01/01 Estilo de catedra]',
            '\\RequirePackage{xcolor}',
            '\\providecommand{\\firma}{--- Cátedra de Laboratorio}',
            '\\newcommand{\\destacar}[1]{\\textbf{\\color{blue!60!black}#1}}',
            '',
          ].join('\n'),
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{mipaquete}   % nuestro paquete propio (mipaquete.sty, panel de Archivos)',
        '',
        '\\begin{document}',
        '',
        'Texto del práctico, con una idea \\destacar{destacada}.',
        '',
        '\\bigskip',
        '\\firma',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: cargá el paquete propio mipaquete (ya está en el proyecto) y usá su comando \\firma.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '% El paquete mipaquete.sty ya está en el proyecto.',
          '% TODO (1): cargalo con \\usepackage{mipaquete}',
          '',
          '\\begin{document}',
          'Texto del práctico.',
          '% TODO (2): usá \\firma al final.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\usepackage{mipaquete}', '\\firma'],
        hints: ['Se carga como cualquier paquete: \\usepackage{mipaquete}. Después tenés \\firma y \\destacar.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{mipaquete}',
          '',
          '\\begin{document}',
          'Texto del práctico.',
          '',
          '\\firma',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Macros y comandos propios', 'expl3: el LaTeX moderno'],
    },
    // ── Módulo: Flujo y entorno ───────────────────────────────────────────
    {
      id: 'l4-flujo',
      level: 4,
      title: 'Flujo reproducible',
      capa: 'infraestructura',
      module: 'Flujo y entorno',
      objective: 'organizar la compilación, los comentarios y el versionado del proyecto.',
      prerequisites: ['l0-compilar-errores'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Tres hábitos clave para un proyecto sano: usar **latexmk** (corre todas las pasadas necesarias —biber, makeindex, referencias— solo), **comentar** con `%` lo no obvio, y **versionar con git** ignorando los archivos intermedios (`.aux`, `.log`, `.out`, `.pdf`).',
        },
        {
          kind: 'prose',
          markdown:
            'Dos comodidades de latexmk: `-pvc` (**preview continuo**: recompila y refresca el visor cada vez que guardás) y `-outdir=build` (deja los intermedios en una carpeta aparte, así el proyecto queda limpio). Podés fijar el motor y las opciones en un archivo `.latexmkrc` para no repetir flags. Y para dejar el `.tex` prolijo automáticamente, `latexindent -w archivo.tex`.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '% comentario', desc: 'Todo lo que sigue al % en la línea se ignora.' },
            { cmd: 'latexmk -pdf archivo.tex', desc: 'Compila con las pasadas necesarias (terminal).' },
            { cmd: 'latexmk -c', desc: 'Limpia los archivos auxiliares.' },
            { cmd: '.gitignore', desc: 'Excluí *.aux, *.log, *.out, *.pdf del repositorio.' },
            { cmd: 'latexdiff v1.tex v2.tex', desc: 'Marca los cambios entre dos versiones.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'No subas al repositorio los archivos generados (`.aux`, `.pdf`…): cambian en cada compilación y ensucian el historial. Versioná **solo las fuentes** (`.tex`, `.bib`, imágenes).',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Para algo 100% reproducible, una imagen Docker `texlive/texlive` o un workflow de GitHub Actions compila el documento igual en cualquier máquina (próxima lección).',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '',
        '\\begin{document}',
        '',
        '% --- Este es un comentario: no aparece en el PDF. ---',
        '% Útil para dejar notas, desactivar una línea o explicar una decisión.',
        '',
        '\\section{Texto visible}',
        'Solo el texto fuera de los comentarios llega al PDF.',
        '% \\section{Sección desactivada}  <- comentada: no se compila',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: agregá un comentario con % (no debe aparecer en el PDF) y dejá texto visible.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '% TODO: agregá acá una línea de comentario que empiece con %',
          'Texto visible del documento.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['%'],
        hints: ['Cualquier línea que empiece con % es un comentario.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '% Esto es un comentario y no aparece en el PDF.',
          'Texto visible del documento.',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Distribuciones e instalación', 'Anti-patrones y log limpio'],
    },
    {
      id: 'l4-antipatrones',
      level: 4,
      title: 'Anti-patrones y log limpio',
      capa: 'infraestructura',
      module: 'Flujo y entorno',
      objective:
        'reconocer los comandos obsoletos (l2tabu) y sus reemplazos, y leer el log para dejar el documento sin warnings.',
      prerequisites: ['l4-flujo'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Un documento de primer nivel **compila limpio**: cero errores y, idealmente, **cero warnings**. Un `Overfull \\hbox`, un `Font shape undefined` o un `Reference undefined` no son ruido: son señales de algo a corregir. La otra mitad de la calidad es **no usar comandos obsoletos** (la lista se llama `l2tabu`): muchos rompen el sistema de fuentes moderno o tienen bugs.',
        },
        {
          kind: 'commands',
          title: 'Anti-patrón → reemplazo (l2tabu)',
          items: [
            { cmd: '\\bf \\it \\rm', desc: '→ \\textbf{...} \\textit{...} o \\bfseries (los viejos son obsoletos).' },
            { cmd: '$$ ... $$', desc: '→ \\[ ... \\] o equation (el $$ es TeX plano: rompe el espaciado).' },
            { cmd: 'eqnarray', desc: '→ align (eqnarray tiene el espaciado roto).' },
            { cmd: 'a \\over b', desc: '→ \\frac{a}{b}.' },
            { cmd: '\\hline y |c|c|', desc: '→ booktabs (\\toprule/\\midrule/\\bottomrule, sin verticales).' },
            { cmd: '\\centerline{...}', desc: '→ \\centering o el entorno center.' },
          ],
        },
        {
          kind: 'commands',
          title: 'Herramientas de diagnóstico (quitar en la versión final)',
          items: [
            { cmd: '\\usepackage[l2tabu,orthodox]{nag}', desc: 'Avisa en el log si usás comandos obsoletos.' },
            { cmd: '\\usepackage[notref,notcite]{showkeys}', desc: 'Muestra los \\label en el PDF (borrador).' },
            { cmd: '\\overfullrule=2cm', desc: 'Marca con una barra negra los Overfull \\hbox.' },
            { cmd: '\\usepackage{todonotes}', desc: '\\todo{...} y \\listoftodos para pendientes.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Cómo leer el log: buscá las palabras `Error`, `Overfull`, `Undefined`. El **primer** error suele causar los siguientes, así que arreglá de arriba hacia abajo. Un `??` en el PDF o `Reference undefined` significa que falta **otra pasada** (o que un `\\label` está mal escrito) — por eso usamos `latexmk`, que repite hasta estabilizar.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Dejá `nag` cargado mientras escribís: convierte la lista de anti-patrones en **avisos automáticos** al compilar. Es el mejor profesor de buenas prácticas. Acordate de sacar los paquetes de diagnóstico antes de entregar.',
        },
      ],
      example: [
        '\\documentclass[11pt,a4paper]{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{amsmath}',
        '\\usepackage{booktabs}',
        '% Mientras escribís, agregá \\usepackage[l2tabu,orthodox]{nag} como PRIMER',
        '% paquete: avisa de comandos obsoletos. Se quita en la versión final (como acá).',
        '',
        '\\begin{document}',
        '',
        '\\section{Compilar limpio}',
        'Este documento usa solo comandos actuales, así que el log queda sin warnings.',
        'Énfasis con \\textbf{negrita} y \\emph{cursiva}, no con los viejos comandos',
        'de fuente; ecuaciones con equation, no con el doble signo de peso obsoleto.',
        '',
        '\\begin{equation}\\label{eq:euler}',
        '  e^{i\\pi} + 1 = 0',
        '\\end{equation}',
        '',
        'La identidad de la \\eqref{eq:euler} se escribe con un entorno equation.',
        '',
        '\\begin{table}[h]',
        '  \\centering',
        '  \\begin{tabular}{lr}',
        '    \\toprule',
        '    Símbolo & Significado \\\\',
        '    \\midrule',
        '    $e$   & número de Euler \\\\',
        '    $\\pi$ & relación entre circunferencia y diámetro \\\\',
        '    \\bottomrule',
        '  \\end{tabular}',
        '\\end{table}',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt:
          'Reescribí el cuerpo evitando los anti-patrones: cambiá {\\bf ...} por \\textbf{...} y la eqnarray por un align.',
        starter: [
          '\\documentclass[11pt,a4paper]{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{amsmath}',
          '',
          '\\begin{document}',
          '',
          '% TODO: esto está con anti-patrones. Reescribilo bien:',
          '% - {\\bf importante}  -> \\textbf{importante}',
          '% - eqnarray          -> align',
          'Algo {\\bf importante}.',
          '',
          '\\begin{eqnarray}',
          '  a &=& b + c',
          '\\end{eqnarray}',
          '',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\textbf{', '\\begin{align}'],
        hints: [
          'Negrita semántica: \\textbf{importante}.',
          'align reemplaza a eqnarray; alinea por el & antes del =.',
        ],
        solution: [
          '\\documentclass[11pt,a4paper]{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{amsmath}',
          '',
          '\\begin{document}',
          '',
          'Algo \\textbf{importante}.',
          '',
          '\\begin{align}',
          '  a &= b + c',
          '\\end{align}',
          '',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Flujo reproducible', 'El canon del preámbulo'],
    },
    {
      id: 'l4-instalacion',
      level: 4,
      title: 'Distribuciones e instalación',
      capa: 'infraestructura',
      module: 'Flujo y entorno',
      objective: 'conocer las distribuciones de TeX y cómo lograr un entorno reproducible.',
      prerequisites: ['l4-flujo'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Hay varias formas de tener LaTeX instalado: **MiKTeX** (Windows; instala paquetes al vuelo cuando un documento los pide), **TeX Live** (multiplataforma, el estándar; en macOS se llama MacTeX) y **Overleaf** (en la nube, cero instalación, ideal para colaborar).',
        },
        {
          kind: 'prose',
          markdown:
            'TeX Live viene en **esquemas**: `scheme-full` (todo, varios GB) o `scheme-basic` + instalar lo que falte con `tlmgr`. Tus paquetes y configuraciones personales van en el árbol `TEXMFHOME` (`~/texmf`), separado de la instalación del sistema. Overleaf te deja **fijar la versión** de TeX Live del proyecto: clave para que una tesis compile igual dentro de dos años. La regla de oro sigue siendo **fijar versiones** (Docker/CI) para reproducibilidad.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: 'tlmgr install <paquete>', desc: 'Instalar paquetes en TeX Live.' },
            { cmd: 'tlmgr update --self --all', desc: 'Actualizar TeX Live y sus paquetes.' },
            { cmd: 'MiKTeX Console / mpm', desc: 'Gestor de paquetes de MiKTeX.' },
            { cmd: 'texlive/texlive (Docker)', desc: 'Imagen con TeX Live completo (reproducible).' },
            { cmd: 'GitHub Actions', desc: 'Compilar el documento automáticamente en CI.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Problemáticas típicas: un paquete faltante, una **versión desfasada** (p. ej. `siunitx` nuevo con un kernel viejo) o archivos `.fndb` bloqueados en Windows. La causa casi siempre es mezclar versiones; fijarlas (Docker/CI) lo evita.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Para una entrega importante, compilá una vez en un entorno **limpio y fijo** (Docker o CI) antes de mandarla: así te asegurás de que no dependés de algo instalado solo en tu máquina.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '',
        '\\begin{document}',
        '\\section{Un entorno reproducible}',
        '',
        '% Compilar localmente:   latexmk -pdf documento.tex',
        '% Reproducible:          imagen Docker texlive/texlive o GitHub Actions.',
        '',
        'La distribución (MiKTeX, TeX Live, Overleaf) decide qué paquetes tenés y',
        'cómo se actualizan. Fijar versiones hace que compile igual en cualquier lado.',
        '\\end{document}',
        '',
      ].join('\n'),
      seeAlso: ['Flujo reproducible'],
    },
    // ── Módulo: Salida y accesibilidad ────────────────────────────────────
    {
      id: 'l4-publicacion',
      level: 4,
      title: 'Publicación e interoperabilidad',
      capa: 'infraestructura',
      module: 'Salida y accesibilidad',
      objective: 'entender cómo convertir el documento a otros formatos (Word, HTML).',
      prerequisites: ['l0-pensar-documento'],
      content: [
        {
          kind: 'prose',
          markdown:
            '**pandoc** convierte entre LaTeX, Markdown, HTML, **Word (docx)** y EPUB. La clave: cuanto más **semántico** sea tu documento (marcás *qué es* cada cosa, no su formato), mejor convierte; el formateo manual (espacios, saltos, cajas) se pierde en la conversión.',
        },
        {
          kind: 'prose',
          markdown:
            'pandoc tiene opciones útiles: `--citeproc` convierte también la **bibliografía** desde un `.bib`, `--template` aplica una plantilla de salida, y `--pdf-engine=lualatex` elige el motor. Va en la misma familia que **Quarto** y **MyST**: escribís una vez en un formato semántico y publicás en PDF **y** HTML. Y sirve al revés: `pandoc informe.docx -o informe.tex` te da un punto de partida cuando alguien te manda un Word.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: 'pandoc doc.tex -o doc.docx', desc: 'Convierte a Word (terminal).' },
            { cmd: 'pandoc doc.tex -o doc.html', desc: 'Convierte a HTML.' },
            { cmd: 'pandoc doc.tex -o doc.epub', desc: 'Convierte a EPUB (libro electrónico).' },
            { cmd: 'make4ht / LaTeXML', desc: 'LaTeX → HTML/MathML (lo que usa arXiv).' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Lo que **no** sobrevive a la conversión: trucos visuales (`\\vspace`, `\\hfill`), TikZ complejo, macros muy específicas. Si necesitás convertir, escribí lo más estándar y semántico posible.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Esto cierra el círculo del curso: lo que aprendiste a expresar como **significado** es justo lo que viaja bien a cualquier formato. Esa es la idea detrás de Matex.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '',
        '\\begin{document}',
        '',
        '\\section{Documento semántico}',
        'Marcado con \\emph{significado} —secciones, énfasis, listas— en lugar de',
        'formato manual: así convierte bien a Word, HTML o EPUB con pandoc.',
        '',
        '\\subsection{Por qué importa}',
        'Una \\texttt{\\textbackslash section} viaja como un encabezado; un espacio',
        'forzado a mano, no viaja a ningún lado.',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: escribí un documento bien semántico (con \\section y \\emph): es lo que mejor se convierte a otros formatos.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '% TODO: una \\section{...} y un párrafo que use \\emph{...}',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\section', '\\emph'],
        hints: ['No hace falta formato manual: solo marcá el significado.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '\\section{Introducción}',
          'Lo que marcamos con \\emph{significado} se convierte bien a otros formatos.',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Accesibilidad y PDF', 'Cómo pensar un documento'],
    },
    {
      id: 'l4-accesibilidad',
      level: 4,
      title: 'Accesibilidad y PDF',
      capa: 'carpinteria',
      module: 'Salida y accesibilidad',
      objective: 'declarar idioma y metadatos para un PDF más accesible y archivable.',
      prerequisites: ['l1-hyperref'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Un PDF accesible declara su **idioma** y sus **metadatos**, lleva **texto alternativo** en las figuras y no codifica información **solo** por color. El LaTeX moderno avanza fuerte en **PDF etiquetado** (PDF/UA) con `tagpdf` y `\\DocumentMetadata`.',
        },
        {
          kind: 'prose',
          markdown:
            'Un PDF **etiquetado** guarda la estructura (qué es título, párrafo, figura, tabla) y el **orden de lectura**, que es lo que usa un lector de pantalla. Por eso vuelve a pagar marcar la **semántica** (`\\section`, `figure`, `table`) en vez de imitarla a mano. Sumá **texto alternativo** en las imágenes (`\\includegraphics[alt={descripción}]{...}`). Importa por accesibilidad real, por requisitos legales y para el archivado a largo plazo (PDF/A). El punto de entrada moderno es `\\DocumentMetadata{}` **antes** de `\\documentclass`.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\hypersetup{pdflang=es-AR}', desc: 'Declara el idioma del PDF (hyperref).' },
            { cmd: '\\hypersetup{pdftitle={...}, pdfauthor={...}}', desc: 'Metadatos del documento.' },
            { cmd: '\\DocumentMetadata{lang=es-AR}', desc: 'Etiquetado moderno (va ANTES de \\documentclass).' },
            { cmd: '\\usepackage{pdfx}', desc: 'Genera PDF/A para archivado a largo plazo.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'No transmitas información **solo** con el color (“lo rojo está mal”): mucha gente no lo distingue. Acompañá el color con una forma, una etiqueta o un símbolo. Y cuidá el contraste texto/fondo.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Lo mínimo que suma mucho: declarar el idioma (`pdflang`) y completar `pdftitle`/`pdfauthor`. Un lector de pantalla y los buscadores lo agradecen, y es una sola línea.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage[hidelinks]{hyperref}',
        '\\hypersetup{',
        '  pdftitle={Documento accesible},',
        '  pdfauthor={Estudiante},',
        '  pdflang={es-AR},',
        '}',
        '',
        '\\begin{document}',
        '\\section{Accesibilidad}',
        'Declarar el idioma y los metadatos ayuda a los lectores de pantalla y al',
        'archivado. La opción \\texttt{hidelinks} evita los recuadros de color en los',
        'enlaces, más prolijo al imprimir.',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: declará el idioma del PDF con \\hypersetup{pdflang=es-AR}.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage[hidelinks]{hyperref}',
          '% TODO: declará el idioma con \\hypersetup{pdflang=es-AR}',
          '',
          '\\begin{document}',
          'Un documento con idioma declarado.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\hypersetup', 'pdflang'],
        hints: ['\\hypersetup{pdflang=es-AR} en el preámbulo.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage[hidelinks]{hyperref}',
          '\\hypersetup{pdflang=es-AR}',
          '',
          '\\begin{document}',
          'Un documento con idioma declarado.',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Enlaces y metadatos (hyperref)'],
    },
    // ── Módulo: Documentos especiales ─────────────────────────────────────
    {
      id: 'l4-documentos-especiales',
      level: 4,
      title: 'Documentos especiales',
      capa: 'semantica',
      module: 'Documentos especiales',
      objective: 'conocer las clases dedicadas a exámenes, CV, pósters y cartas.',
      prerequisites: ['l3-clases'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Cada tipo de documento tiene su **clase**, que ya trae la estructura adecuada. Elegir la correcta ahorra muchísimo trabajo de carpintería: en vez de imitar un CV con un `article`, usás una clase que ya sabe qué es un CV.',
        },
        {
          kind: 'prose',
          markdown:
            'Elegí siempre por la **estructura** que necesitás (¿preguntas con puntaje? → `exam`; ¿charla? → `beamer`; ¿póster? → `tikzposter`), no por la apariencia. Para libros largos, las clases “todo en uno” `memoir` o KOMA (`scrbook`) dan más control. Y la mejor forma de ver cada una en acción es la **Galería** de esta plataforma: tiene un ejemplar real, completo y compilable por cada tipo (article, report, book, beamer, KOMA, letter, exam, moderncv, tikzposter).',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\documentclass{exam}', desc: 'Exámenes: preguntas, puntajes, claves, casillas.' },
            { cmd: '\\documentclass{moderncv}', desc: 'CV (también altacv).' },
            { cmd: '\\documentclass{tikzposter}', desc: 'Pósters (también beamerposter).' },
            { cmd: '\\documentclass{scrlttr2}', desc: 'Cartas (KOMA); la básica es letter.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Estas clases pueden no estar instaladas por defecto (la distribución las baja al vuelo o con `tlmgr`). Por eso el ejemplo cargable es un `article` que las describe; en tu máquina, probá cada clase en un documento aparte.',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            'En la sección **Documentos** de esta plataforma tenés plantillas listas para varios de estos casos (examen, informe de laboratorio, CV, carta), ya armadas y compilables.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '',
        '\\begin{document}',
        '\\section{Una clase para cada caso}',
        '',
        '\\begin{itemize}',
        '  \\item \\textbf{Exámenes}: \\texttt{exam} (puntajes, claves, casillas).',
        '  \\item \\textbf{CV}: \\texttt{moderncv} o \\texttt{altacv}.',
        '  \\item \\textbf{Pósters}: \\texttt{tikzposter} o \\texttt{beamerposter}.',
        '  \\item \\textbf{Cartas}: \\texttt{scrlttr2} (KOMA) o la básica \\texttt{letter}.',
        '\\end{itemize}',
        '',
        'Elegir la clase correcta te da la estructura gratis; el contenido es lo tuyo.',
        '\\end{document}',
        '',
      ].join('\n'),
      seeAlso: ['Clases y opciones'],
    },
  ],
} satisfies LevelInput
