import type { LevelInput } from '../types'

/** Nivel 3 · Tipos de documento, gráficos y presentaciones. */
export const nivel3 = {
  level: 3,
  title: 'Documentos, gráficos y presentaciones',
  summary: 'Clases y documentos largos, gráficos y diagramas, código y pseudocódigo, y presentaciones con Beamer.',
  lessons: [
    // ── Módulo: Tipos de documento ────────────────────────────────────────
    {
      id: 'l3-clases',
      level: 3,
      title: 'Clases y opciones',
      capa: 'semantica',
      module: 'Tipos de documento',
      objective: 'elegir la clase adecuada y configurar sus opciones globales.',
      prerequisites: ['l0-primer-documento'],
      content: [
        {
          kind: 'prose',
          markdown:
            'La **clase** (primer argumento de `\\documentclass`) define la estructura: `article` (TPs, papers), `report` (con capítulos), `book` (libros, con páginas a doble cara), `beamer` (presentaciones). Las **opciones** entre `[ ]` ajustan cosas globales: tamaño de letra, papel, columnas.',
        },
        {
          kind: 'prose',
          markdown:
            'Las **clases KOMA-Script** (`scrartcl`, `scrreprt`, `scrbook`) son alternativas con un diseño más cuidado por defecto y muchas opciones propias (`DIV` para márgenes, `headings` para los títulos). Para un documento serio, valen la pena.',
        },
        {
          kind: 'prose',
          markdown:
            'Más allá de las generales, hay clases **especializadas**: `beamer` (presentaciones), `letter`/`scrlttr2` (cartas), `exam` (parciales con puntaje), `moderncv` (CV), `tikzposter` (pósters) y `standalone` (una sola figura, que después podés `\\includegraphics` en otro documento). Y un detalle: las opciones de `\\documentclass` son **globales** y se pasan a los paquetes (p. ej. `[svgnames]` llega a xcolor). En la **Galería** tenés un ejemplar real de cada una.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\documentclass[12pt,a4paper]{article}', desc: 'Letra de 12 pt en papel A4.' },
            { cmd: '\\documentclass[twocolumn]{article}', desc: 'Texto a dos columnas.' },
            { cmd: '\\documentclass{report}', desc: 'Habilita \\chapter.' },
            { cmd: '\\documentclass[landscape]{article}', desc: 'Página apaisada.' },
            { cmd: '\\documentclass{scrartcl}', desc: 'KOMA-Script: mejor diseño por defecto.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Las opciones de clase son **globales**: afectan todo el documento. No mezcles opciones de una clase con otra (p. ej. `twocolumn` no tiene sentido en `beamer`). Y `\\chapter` solo existe en `report`/`book`, no en `article`.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Elegí la clase por la **estructura** que necesitás (¿hay capítulos? → report), no por el aspecto: el aspecto se ajusta después con paquetes y opciones.',
        },
      ],
      example: [
        '\\documentclass[12pt,a4paper,twocolumn]{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '',
        '\\begin{document}',
        '',
        '\\section{Opciones de clase}',
        'Este documento usa 12\\,pt, papel A4 y dos columnas, todo declarado en',
        '\\texttt{documentclass}. Pasar a una sola columna o a 11\\,pt es cambiar una',
        'opción, no el contenido.',
        '',
        '\\section{El texto fluye solo}',
        'A medida que se llena la página, el texto pasa de una columna a la otra sin',
        'que toques nada. Las clases \\texttt{report} y \\texttt{book} agregarían',
        '\\texttt{chapter}; las clases KOMA (\\texttt{scrartcl}) mejoran el diseño general.',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá las opciones de clase para usar 12pt y dos columnas (twocolumn).',
        starter: [
          '\\documentclass{article}  % TODO: agregá las opciones [12pt,twocolumn]',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '\\section{Una sección}',
          'Texto de ejemplo para ver el efecto de las opciones de clase.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['12pt', 'twocolumn'],
        hints: ['Las opciones van entre [ ]: \\documentclass[12pt,twocolumn]{article}.'],
        solution: [
          '\\documentclass[12pt,twocolumn]{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '\\section{Una sección}',
          'Texto de ejemplo para ver el efecto de las opciones de clase.',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Documentos largos'],
    },
    {
      id: 'l3-documentos-largos',
      level: 3,
      title: 'Documentos largos',
      capa: 'semantica',
      module: 'Tipos de documento',
      objective: 'estructurar un informe con capítulos, índice y apéndices.',
      prerequisites: ['l3-clases'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Para informes o tesinas usá `report` (o `book`): habilitan `\\chapter`. Con `\\tableofcontents` se genera el índice **automáticamente** a partir de los títulos, y con `\\appendix` los capítulos siguientes pasan a numerarse A, B, C.',
        },
        {
          kind: 'prose',
          markdown:
            'La clase `book` divide el documento en tres “materias”: `\\frontmatter` (portada, índice, prólogo: páginas en números romanos i, ii, iii y capítulos **sin numerar**), `\\mainmatter` (el cuerpo: números arábigos desde 1) y `\\backmatter` (bibliografía, índices: sin numerar). Arriba de `\\chapter` está `\\part`, y un `\\chapter*{...}` queda sin número pero podés sumarlo al índice con `\\addcontentsline`.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\documentclass{report}', desc: 'Clase con capítulos.' },
            { cmd: '\\chapter{...}', desc: 'Capítulo (por encima de \\section).' },
            { cmd: '\\tableofcontents', desc: 'Índice general (a partir de los títulos).' },
            { cmd: '\\include{capitulos/intro}', desc: 'Incluye un capítulo desde su archivo (con salto de página).' },
            { cmd: '\\listoffigures / \\listoftables', desc: 'Índices de figuras y de tablas.' },
            { cmd: '\\appendix', desc: 'A partir de acá, capítulos A, B, C…' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'El índice necesita **dos pasadas**: en la primera, LaTeX escribe los números en un archivo auxiliar; en la segunda, los lee. El backend ya hace las dos. Si ves un índice vacío o desactualizado, falta recompilar.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'En documentos grandes conviene separar **cada capítulo en su propio archivo** y unirlos con `\\include` (como en este ejemplo): compila más rápido, podés usar `\\includeonly` para ver solo algunos, y es más fácil de mantener. El detalle de `\\input` vs `\\include` está en *Modularizar el proyecto*.',
        },
      ],
      mainFile: 'main.tex',
      files: [
        {
          path: 'capitulos/introduccion.tex',
          content: [
            '\\chapter{Introducción}',
            'El primer capítulo presenta el problema.',
            '\\section{Contexto}',
            'Una sección dentro del capítulo (será 1.1).',
            '',
          ].join('\n'),
        },
        {
          path: 'capitulos/desarrollo.tex',
          content: ['\\chapter{Desarrollo}', 'El segundo capítulo desarrolla la solución.', ''].join('\n'),
        },
        {
          path: 'capitulos/datos.tex',
          content: ['\\chapter{Datos complementarios}', 'Este apéndice se numera como Apéndice A.', ''].join('\n'),
        },
      ],
      example: [
        '\\documentclass{report}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '',
        '\\begin{document}',
        '',
        '\\tableofcontents   % índice general, generado de los títulos',
        '',
        '% Cada capítulo vive en su propio archivo (mirá el panel de Archivos):',
        '\\include{capitulos/introduccion}',
        '\\include{capitulos/desarrollo}',
        '',
        '\\appendix          % de acá en más, los capítulos son A, B, C…',
        '\\include{capitulos/datos}',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: usá la clase report, agregá \\tableofcontents y al menos un \\chapter.',
        starter: [
          '\\documentclass{report}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '% TODO (1): agregá el índice con \\tableofcontents',
          '% TODO (2): agregá un \\chapter{Introducción} con un párrafo',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\documentclass{report}', '\\tableofcontents', '\\chapter'],
        hints: ['La clase report habilita \\chapter; el índice se arma con \\tableofcontents.'],
        solution: [
          '\\documentclass{report}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '\\tableofcontents',
          '\\chapter{Introducción}',
          'Contenido del primer capítulo.',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Modularizar el proyecto', 'Numeración y contadores'],
    },
    {
      id: 'l3-modularizar',
      level: 3,
      title: 'Modularizar el proyecto',
      capa: 'infraestructura',
      module: 'Tipos de documento',
      objective: 'dividir un documento grande en varios archivos.',
      prerequisites: ['l3-documentos-largos'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Un documento grande se mantiene mejor en **varios archivos**. `\\input{archivo}` pega el contenido tal cual, en cualquier punto; `\\include{cap}` es para capítulos (empieza página nueva y permite `\\includeonly`); el paquete `subfiles` deja además **compilar cada parte por separado**.',
        },
        {
          kind: 'prose',
          markdown:
            'Un layout que escala: `main.tex` (clase + `\\input{preambulo}` + el cuerpo), un `preambulo.tex` con los paquetes y macros (**reutilizable** entre proyectos), y una carpeta `capitulos/` con un archivo por capítulo. Ventajas: trabajás en paralelo, los **diffs de git** quedan acotados a un capítulo, y compilás solo lo que tocás con `\\includeonly`. Las rutas de `\\input` son **relativas al main**, así que usá `/` (no `\\`).',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\input{seccion}', desc: 'Inserta seccion.tex en ese punto (sin salto de página).' },
            { cmd: '\\include{capitulo}', desc: 'Incluye un capítulo (con salto de página y .aux propio).' },
            { cmd: '\\includeonly{cap1,cap3}', desc: 'Compila solo esos \\include (más rápido al revisar).' },
            { cmd: '\\usepackage{subfiles}', desc: 'Permite compilar cada subarchivo solo.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'No anides `\\include` dentro de otro `\\include` (LaTeX lo prohíbe). Usá `\\input` para fragmentos sueltos e `\\include` solo para los capítulos de nivel superior.',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            'Acá el ejemplo es un **proyecto multi-archivo real**: el principal incluye con `\\input` los archivos `secciones/intro.tex` y `secciones/metodos.tex` (los ves más abajo). En **Mis Proyectos** podés crear varios archivos del mismo modo.',
        },
      ],
      mainFile: 'main.tex',
      files: [
        {
          path: 'secciones/intro.tex',
          content: ['\\section{Introducción}', 'Esta sección vive en \\texttt{secciones/intro.tex}.', ''].join('\n'),
        },
        {
          path: 'secciones/metodos.tex',
          content: ['\\section{Métodos}', 'Y esta otra, en \\texttt{secciones/metodos.tex}.', ''].join('\n'),
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '',
        '\\begin{document}',
        '',
        '% El documento principal solo ensambla las partes;',
        '% cada sección vive en su propio archivo (mirá el panel de Archivos).',
        '\\input{secciones/intro}',
        '\\input{secciones/metodos}',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: incluí el contenido de secciones/intro.tex con \\input (el archivo ya existe en el proyecto).',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage{microtype}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '',
          '\\begin{document}',
          '% El archivo secciones/intro.tex ya existe en el proyecto.',
          '% TODO: insertalo acá con \\input{secciones/intro}',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\input'],
        hints: ['\\input{secciones/intro} pega el contenido de secciones/intro.tex (sin la extensión).'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage{microtype}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '',
          '\\begin{document}',
          '\\input{secciones/intro}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Flujo reproducible'],
    },
    // ── Módulo: Gráficos ──────────────────────────────────────────────────
    {
      id: 'l3-tikz',
      level: 3,
      title: 'Dibujar con TikZ',
      capa: 'carpinteria',
      module: 'Gráficos',
      objective: 'dibujar gráficos vectoriales describiéndolos con comandos.',
      prerequisites: ['l1-figuras'],
      content: [
        {
          kind: 'prose',
          markdown:
            '**TikZ** dibuja describiendo, no arrastrando: dentro de `tikzpicture`, `\\draw` traza líneas y formas entre **coordenadas** `(x,y)`, `\\node` coloca texto y `\\fill` rellena. Es la base de diagramas, ejes y figuras geométricas, y todo escala sin perder calidad.',
        },
        {
          kind: 'prose',
          markdown:
            'Un `\\draw` es un **camino** que podés encadenar: `(0,0) -- (1,0) -- (1,1) -- cycle` cierra un triángulo. Las coordenadas pueden ser **relativas** (`++(1,0)` = “un paso a la derecha”) o **polares** (`(30:2)` = ángulo 30°, radio 2). Para repetir hay `\\foreach \\x in {1,...,5} { ... }`. Y definir **estilos** (`every node/.style={...}`) mantiene el dibujo consistente.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\usepackage{tikz}', desc: 'Carga TikZ.' },
            { cmd: '\\draw (0,0) -- (2,2);', desc: 'Línea entre dos puntos.' },
            { cmd: '\\draw[->,thick] ...', desc: 'Opciones: [->] flecha, [thick] grosor, color…' },
            { cmd: '\\draw (1,1) circle (0.5);', desc: 'Círculo de radio 0.5.' },
            { cmd: '\\draw (0,0) rectangle (2,1);', desc: 'Rectángulo entre dos esquinas.' },
            { cmd: '\\node at (1,1) {texto};', desc: 'Coloca texto en una coordenada.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Cada instrucción de dibujo termina en **punto y coma** (`;`). Olvidarlo es el error más común de TikZ: LaTeX se “come” la línea siguiente y el mensaje resulta confuso.',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            'TikZ es enorme (librerías para árboles, autómatas, circuitos, grafos…). Para empezar alcanza con `\\draw` y `\\node`; las librerías se cargan con `\\usetikzlibrary{...}`.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{tikz}',
        '',
        '\\begin{document}',
        '\\begin{tikzpicture}',
        '  % Ejes con flechas y etiquetas:',
        '  \\draw[->] (-0.3,0) -- (3,0) node[right] {$x$};',
        '  \\draw[->] (0,-0.3) -- (0,3) node[above] {$y$};',
        '  % Una recta, un círculo y un rectángulo:',
        '  \\draw[thick, blue] (0,0) -- (2.5,2.5);',
        '  \\draw[red] (1,1) circle (0.6);',
        '  \\draw[fill=green!20] (1.8,0.2) rectangle (2.6,0.8);',
        '  % Texto en una coordenada:',
        '  \\node at (1.5,2.2) {recta $y=x$};',
        '\\end{tikzpicture}',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: cargá tikz y dibujá una línea y un círculo con \\draw dentro de un tikzpicture.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '% TODO (1): cargá \\usepackage{tikz}',
          '',
          '\\begin{document}',
          '\\begin{tikzpicture}',
          '  % TODO (2): una línea  \\draw (0,0) -- (2,2);',
          '  % TODO (3): un círculo \\draw (1,1) circle (0.5);',
          '\\end{tikzpicture}',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\usepackage{tikz}', '\\begin{tikzpicture}', '\\draw'],
        hints: ['Una línea simple: \\draw (0,0) -- (2,2);  Cada \\draw termina en ;'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{tikz}',
          '',
          '\\begin{document}',
          '\\begin{tikzpicture}',
          '  \\draw (0,0) -- (2,2);',
          '  \\draw (1,1) circle (0.5);',
          '\\end{tikzpicture}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Graficar funciones (pgfplots)', 'Diagramas (autómatas y árboles)'],
    },
    {
      id: 'l3-pgfplots',
      level: 3,
      title: 'Graficar funciones (pgfplots)',
      capa: 'semantica',
      module: 'Gráficos',
      objective: 'graficar funciones matemáticas con ejes, dominio y varias curvas.',
      prerequisites: ['l0-matematica-basica'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Para **graficar funciones** la herramienta cómoda es **pgfplots** (construida sobre TikZ). Dentro de un entorno `axis`, `\\addplot` dibuja una expresión en un `domain`. Sirve para curvas, áreas, leyendas, grillas y ejes logarítmicos.',
        },
        {
          kind: 'prose',
          markdown:
            'El entorno `axis` se configura con opciones: `xlabel`/`ylabel`, `title`, `axis lines=middle` (ejes cruzados en el origen, estilo matemático), `xmin/xmax`. Y `\\addplot` tiene variantes: `[smooth]` para curvas suaves, `[only marks]` para una nube de puntos, y `\\addplot fill between` para sombrear el área entre dos curvas. Además de expresiones, podés graficar **datos** desde una tabla o archivo (lo vemos en la próxima lección).',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\usepackage{pgfplots}', desc: 'Carga pgfplots (y TikZ).' },
            { cmd: '\\pgfplotsset{compat=1.18}', desc: 'Fija el comportamiento (evita warnings).' },
            { cmd: '\\begin{axis}[opciones] ... \\end{axis}', desc: 'Sistema de ejes (dentro de tikzpicture).' },
            { cmd: '\\addplot[domain=-3:3,samples=100]{x^2};', desc: 'Grafica una expresión.' },
            { cmd: '\\legend{$f$, $g$}', desc: 'Leyenda para varias curvas.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Poné siempre `\\pgfplotsset{compat=1.18}` (o la versión que uses) en el preámbulo: sin eso, pgfplots avisa que el comportamiento puede cambiar entre versiones.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Subí `samples` (p. ej. a 100) para curvas suaves, usá `grid=major` para una grilla de referencia y `legend pos=north west` para ubicar la leyenda donde no tape las curvas.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{pgfplots}',
        '\\pgfplotsset{compat=1.18}',
        '',
        '\\begin{document}',
        '\\begin{tikzpicture}',
        '\\begin{axis}[',
        '    xlabel=$x$, ylabel=$y$,',
        '    grid=major, legend pos=north west,',
        '    samples=100,',
        ']',
        '  \\addplot[blue, domain=-3:3]{x^2};',
        '  \\addplot[red, domain=-3:3]{2*x + 1};',
        '  \\legend{$x^2$, $2x+1$}',
        '\\end{axis}',
        '\\end{tikzpicture}',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: graficá una función con \\addplot dentro de un entorno axis.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{pgfplots}',
          '\\pgfplotsset{compat=1.18}',
          '',
          '\\begin{document}',
          '\\begin{tikzpicture}',
          '% TODO: \\begin{axis} ... con un \\addplot[domain=-3:3]{x^2}; ... \\end{axis}',
          '\\end{tikzpicture}',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\begin{axis}', '\\addplot'],
        hints: ['El axis va dentro de un tikzpicture.', 'Ejemplo: \\addplot[domain=-3:3]{x^2};'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{pgfplots}',
          '\\pgfplotsset{compat=1.18}',
          '',
          '\\begin{document}',
          '\\begin{tikzpicture}',
          '\\begin{axis}[xlabel=$x$, ylabel=$y$]',
          '  \\addplot[domain=-3:3, samples=100]{x^2};',
          '\\end{axis}',
          '\\end{tikzpicture}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Datos a gráfico y tabla', 'Dibujar con TikZ'],
    },
    {
      id: 'l3-datos',
      level: 3,
      title: 'Datos a gráfico y tabla',
      capa: 'semantica',
      module: 'Gráficos',
      objective: 'graficar mediciones a partir de datos, no solo de fórmulas.',
      prerequisites: ['l3-pgfplots'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Además de fórmulas, `\\addplot table` grafica **datos** (mediciones) desde un archivo `.dat`/`.csv`: una columna por variable, con sus **nombres en la primera fila**. Sobre los datos podés superponer una curva teórica para comparar.',
        },
        {
          kind: 'prose',
          markdown:
            'Podés **elegir columnas** por nombre (`table[x=temp, y=pres]`), calcular una al vuelo (`y expr=\\thisrow{y}*2`) y agregar **barras de error** (`error bars/.cd, y dir=both, y explicit`) leyendo una columna de incertidumbre. Para volcar el mismo `.csv` como una **tabla** (con booktabs), `pgfplotstable` con `\\pgfplotstabletypeset`. Así el dato vive en un solo lugar y alimenta gráfico y tabla.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\addplot table {datos.dat};', desc: 'Grafica desde un archivo de datos.' },
            { cmd: '\\addplot table { x y ... };', desc: 'O desde datos en línea (con encabezados).' },
            { cmd: '\\addplot[only marks] ...', desc: 'Solo puntos (dispersión de mediciones).' },
            { cmd: '\\usepackage{pgfplotstable}', desc: 'Volcar un .csv como tabla LaTeX.' },
            { cmd: '\\usepackage{csvsimple}', desc: 'Recorrer filas de un .csv.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'La **primera fila del archivo son los nombres de las columnas** (`x y`), y `\\addplot table` los usa. Si la grilla queda corrida, suele faltar el encabezado o sobrar una columna.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Tener los datos en un archivo separado te deja regenerar el gráfico sin tocar el documento: ideal para mediciones de laboratorio que se actualizan.',
        },
      ],
      mainFile: 'main.tex',
      files: [
        {
          path: 'datos.dat',
          content: ['x   y', '0   0.1', '1   0.9', '2   4.2', '3   8.9', ''].join('\n'),
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{pgfplots}',
        '\\pgfplotsset{compat=1.18}',
        '',
        '\\begin{document}',
        '\\begin{tikzpicture}',
        '\\begin{axis}[xlabel=$x$, ylabel=$y$, legend pos=north west]',
        '  % Mediciones leídas del archivo datos.dat (mirá el panel de Archivos):',
        '  \\addplot[only marks, blue] table {datos.dat};',
        '  % Curva teórica para comparar:',
        '  \\addplot[red, domain=0:3, samples=50]{x^2};',
        '  \\legend{medición, $x^2$}',
        '\\end{axis}',
        '\\end{tikzpicture}',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: graficá los datos del archivo datos.dat con \\addplot table.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{pgfplots}',
          '\\pgfplotsset{compat=1.18}',
          '',
          '\\begin{document}',
          '\\begin{tikzpicture}',
          '\\begin{axis}',
          '  % El archivo datos.dat ya está en el proyecto (columnas x e y).',
          '  % TODO: \\addplot[only marks] table {datos.dat};',
          '\\end{axis}',
          '\\end{tikzpicture}',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\addplot', 'table'],
        hints: ['\\addplot[only marks] table {datos.dat}; lee las columnas del archivo.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{pgfplots}',
          '\\pgfplotsset{compat=1.18}',
          '',
          '\\begin{document}',
          '\\begin{tikzpicture}',
          '\\begin{axis}',
          '  \\addplot[only marks] table {datos.dat};',
          '\\end{axis}',
          '\\end{tikzpicture}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Tablas que se adaptan'],
    },
    {
      id: 'l3-diagramas',
      level: 3,
      title: 'Diagramas (autómatas y árboles)',
      capa: 'semantica',
      module: 'Gráficos',
      objective: 'dibujar un autómata con estados y transiciones usando librerías de TikZ.',
      prerequisites: ['l3-tikz'],
      content: [
        {
          kind: 'prose',
          markdown:
            'TikZ tiene **librerías** para diagramas: `automata` (estados y transiciones), `positioning` (ubicar un nodo *relativo* a otro, con `right=of`) y, para **árboles**, el paquete `forest`. Se cargan con `\\usetikzlibrary{...}`.',
        },
        {
          kind: 'prose',
          markdown:
            'Para **diagramas de flujo**, la librería `shapes.geometric` da nodos con forma (rectángulo = proceso, rombo = decisión) y `arrows.meta` mejora las puntas de flecha (`-{Stiletto}`). Y muy útil en matemática: `tikz-cd` arma **diagramas conmutativos** (objetos y morfismos) con una sintaxis de matriz, como `A \\arrow{r}{f} & B`.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\usetikzlibrary{automata, positioning}', desc: 'Habilita estados y posicionamiento relativo.' },
            { cmd: '\\node[state, initial] (q0) {...};', desc: 'Un estado inicial.' },
            { cmd: '\\node[state, accepting] (q1) {...};', desc: 'Un estado de aceptación.' },
            { cmd: 'right=of q0', desc: 'Posiciona un nodo a la derecha de q0.' },
            { cmd: '(q0) edge node {a} (q1)', desc: 'Una transición etiquetada con “a”.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            '`right=of q0` (de la librería `positioning`) lleva la palabra `of`. Sin cargar `positioning`, solo funciona `right=q0`, que coloca el nodo pegado y suele quedar mal.',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            'Para **árboles** (sintácticos, de decisión) el paquete `forest` es el más cómodo; para diagramas de flujo, `\\node` con formas + flechas de `arrows.meta`.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{tikz}',
        '\\usetikzlibrary{automata, positioning}',
        '',
        '\\begin{document}',
        '\\begin{tikzpicture}[->, node distance=2.8cm, auto]',
        '  \\node[state, initial]            (q0) {$q_0$};',
        '  \\node[state, accepting, right=of q0] (q1) {$q_1$};',
        '  \\draw (q0) edge[bend left]  node {a} (q1)',
        '        (q1) edge[bend left]  node {b} (q0)',
        '        (q0) edge[loop above] node {c} (q0);',
        '\\end{tikzpicture}',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: dibujá un autómata con dos estados (uno inicial) usando la librería automata.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{tikz}',
          '\\usetikzlibrary{automata, positioning}',
          '',
          '\\begin{document}',
          '\\begin{tikzpicture}[->, node distance=2.8cm, auto]',
          '  % TODO (1): \\node[state, initial] (q0) {$q_0$};',
          '  % TODO (2): \\node[state, accepting, right=of q0] (q1) {$q_1$};',
          '  % TODO (3): \\draw (q0) edge node {a} (q1);',
          '\\end{tikzpicture}',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['automata', 'state'],
        hints: ['\\node[state, initial] (q0) {$q_0$}; crea el estado inicial.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{tikz}',
          '\\usetikzlibrary{automata, positioning}',
          '',
          '\\begin{document}',
          '\\begin{tikzpicture}[->, node distance=2.8cm, auto]',
          '  \\node[state, initial]                (q0) {$q_0$};',
          '  \\node[state, accepting, right=of q0] (q1) {$q_1$};',
          '  \\draw (q0) edge node {a} (q1);',
          '\\end{tikzpicture}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Dibujar con TikZ'],
    },
    // ── Módulo: Código ────────────────────────────────────────────────────
    {
      id: 'l3-codigo',
      level: 3,
      title: 'Mostrar código',
      capa: 'carpinteria',
      module: 'Código',
      objective: 'incluir fragmentos de código fuente con formato y resaltado.',
      prerequisites: ['l0-primer-documento'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Para mostrar **código fuente** literal (sin que LaTeX interprete sus símbolos `\\`, `{`, `_`…) está **listings**: el entorno `lstlisting` para un bloque escrito a mano, o `\\lstinputlisting{archivo}` para **insertar un archivo de código completo** (el flujo habitual). La configuración global va con `\\lstset` en el preámbulo, y resalta palabras clave según el lenguaje.',
        },
        {
          kind: 'prose',
          markdown:
            'El estilo se arma en `\\lstset`: `basicstyle=\\ttfamily\\small`, `keywordstyle`/`commentstyle` (colores), `numbers=left` (numerar líneas), `frame=single` (recuadro) y `breaklines` (partir líneas largas). Si le ponés `caption=` y `label=`, el listado se vuelve un **flotante** referenciable con `\\cref`. Definí **un** estilo con `\\lstdefinestyle{mio}{...}` y reutilizalo —igual que con todo lo demás.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\usepackage{listings}', desc: 'Habilita el formateo de código.' },
            { cmd: '\\lstset{language=Python, ...}', desc: 'Configura lenguaje y estilo (preámbulo).' },
            { cmd: '\\begin{lstlisting} ... \\end{lstlisting}', desc: 'Bloque de código literal escrito a mano.' },
            { cmd: '\\lstinputlisting{archivo}', desc: 'Inserta un archivo de código completo.' },
            { cmd: '\\lstinline|código|', desc: 'Código en línea, entre delimitadores.' },
            { cmd: '\\usepackage{xcolor}', desc: 'Para colorear palabras clave y comentarios.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Si ponés un `lstlisting` **dentro de otro entorno** (una caja, un `frame` de beamer), suele hacer falta marcarlo como `fragile`, porque listings necesita leer el código verbatim.',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            '`minted` da un resaltado más lindo (usa Python y requiere `-shell-escape`, que acá está deshabilitado por seguridad). Para **pseudocódigo**, mejor `algorithm2e` (próxima lección).',
        },
      ],
      mainFile: 'main.tex',
      files: [
        {
          path: 'saludo.py',
          content: [
            '# devuelve un saludo personalizado',
            'def saludo(nombre):',
            '    return "Hola, " + nombre',
            '',
          ].join('\n'),
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{xcolor}',
        '\\usepackage{listings}',
        '',
        '% Estilo global del código:',
        '\\lstset{',
        '  language=Python,',
        '  basicstyle=\\ttfamily\\small,',
        '  keywordstyle=\\color{blue},',
        '  commentstyle=\\color{gray},',
        '  showstringspaces=false,',
        '}',
        '',
        '\\begin{document}',
        '',
        'La función \\lstinline|saludo| vive en su propio archivo, \\texttt{saludo.py},',
        'y lo insertamos completo, formateado:',
        '',
        '\\lstinputlisting{saludo.py}',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: insertá el archivo saludo.py (ya está en el proyecto) con \\lstinputlisting.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{listings}',
          '',
          '\\begin{document}',
          '% El archivo saludo.py ya está en el proyecto.',
          '% TODO: insertalo con \\lstinputlisting{saludo.py}',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\usepackage{listings}', '\\lstinputlisting'],
        hints: ['\\lstinputlisting{saludo.py} inserta el archivo completo, formateado.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{listings}',
          '',
          '\\begin{document}',
          '\\lstinputlisting[language=Python]{saludo.py}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Pseudocódigo (algorithm2e)'],
    },
    {
      id: 'l3-pseudocodigo',
      level: 3,
      title: 'Pseudocódigo (algorithm2e)',
      capa: 'semantica',
      module: 'Código',
      objective: 'escribir algoritmos en pseudocódigo con estructura clara.',
      prerequisites: ['l3-codigo'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Para **pseudocódigo** (no código real de un lenguaje) está **algorithm2e**: entornos con entrada/salida, bucles y condicionales bien tipografiados. A diferencia de `listings`, acá describís el *algoritmo* en abstracto, con notación matemática.',
        },
        {
          kind: 'prose',
          markdown:
            'El entorno `algorithm` lo vuelve un **flotante** con `\\caption` y `\\label` (para referenciarlo con `\\cref`) y `linesnumbered` numera las líneas. Podés poner las palabras clave **en español** con `\\SetKwInput{Entrada}{Entrada}` y definir funciones propias con `\\SetKwFunction`. Los comentarios van con `\\tcp{...}` (al costado) o `\\tcc{...}`. Ojo: dentro de `twocolumn`, usá `algorithm` flotante (no `[H]`).',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\usepackage[ruled,vlined]{algorithm2e}', desc: 'Carga el paquete con un estilo (líneas y barra).' },
            { cmd: '\\KwIn{...} / \\KwOut{...}', desc: 'Entrada y salida del algoritmo.' },
            { cmd: '\\For{...}{...}', desc: 'Bucle (también \\While, \\If, \\eIf).' },
            { cmd: '\\KwTo / \\leftarrow', desc: 'Palabra “hasta” / asignación en pseudocódigo.' },
            { cmd: '\\Return ...', desc: 'Devuelve un resultado.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Cada instrucción termina con `\\;` (no con punto y coma normal): es lo que marca el **fin de línea** del algoritmo y dibuja la sangría. Olvidarlo desalinea todo el bloque.',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            'Una alternativa muy usada es `algpseudocode` (del paquete `algorithmicx`), con palabras clave en inglés (`\\State`, `\\For`, `\\EndFor`). Elegí una y sé consistente.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage[ruled,vlined]{algorithm2e}',
        '',
        '\\begin{document}',
        '',
        '\\begin{algorithm}[H]',
        '\\caption{Factorial de $n$}',
        '\\KwIn{un entero $n \\ge 0$}',
        '\\KwOut{$n!$}',
        '$r \\leftarrow 1$\\;',
        '\\For{$i \\leftarrow 1$ \\KwTo $n$}{',
        '  $r \\leftarrow r \\times i$\\;',
        '}',
        '\\Return $r$\\;',
        '\\end{algorithm}',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: escribí un algoritmo con algorithm2e que use \\KwIn y un \\For.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage[ruled,vlined]{algorithm2e}',
          '',
          '\\begin{document}',
          '\\begin{algorithm}[H]',
          '  % TODO (1): \\KwIn{un entero n}',
          '  % TODO (2): un \\For{...}{...} con una asignación y su \\;',
          '\\end{algorithm}',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['{algorithm2e}', '\\begin{algorithm}'],
        hints: ['Cada línea termina en \\;. Ejemplo: $r \\leftarrow 1$\\;'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage[ruled,vlined]{algorithm2e}',
          '',
          '\\begin{document}',
          '\\begin{algorithm}[H]',
          '\\KwIn{un entero $n \\ge 0$}',
          '$r \\leftarrow 1$\\;',
          '\\For{$i \\leftarrow 1$ \\KwTo $n$}{',
          '  $r \\leftarrow r \\times i$\\;',
          '}',
          '\\Return $r$\\;',
          '\\end{algorithm}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Mostrar código'],
    },
    // ── Módulo: Presentaciones ────────────────────────────────────────────
    {
      id: 'l3-beamer',
      level: 3,
      title: 'Presentaciones con Beamer',
      capa: 'semantica',
      module: 'Presentaciones',
      objective: 'armar una presentación con diapositivas y portada.',
      prerequisites: ['l0-primer-documento'],
      content: [
        {
          kind: 'prose',
          markdown:
            'La clase **beamer** arma presentaciones: cada **diapositiva** es un entorno `frame` con su `\\frametitle` (o el título como argumento: `\\begin{frame}{Título}`). Todo lo que ya sabés (listas, matemática, figuras) funciona igual adentro.',
        },
        {
          kind: 'prose',
          markdown:
            'beamer **ya carga** amsmath, xcolor, hyperref y tikz: no los recargues. Estructurá con `\\section{...}` (aparecen en la barra de navegación y en `\\tableofcontents`), elegí la apariencia con `\\usetheme{...}` + `\\usecolortheme{...}`, y agrupá contenido en **bloques semánticos**: `block` (normal), `alertblock` (destacar) y `exampleblock` (ejemplo). Poné `\\hypersetup{unicode}` para que los marcadores muestren bien los acentos.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\documentclass{beamer}', desc: 'Activa el modo presentación.' },
            { cmd: '\\begin{frame}{Título} ... \\end{frame}', desc: 'Una diapositiva con su título.' },
            { cmd: '\\frametitle{...}', desc: 'Título de la diapositiva (forma alternativa).' },
            { cmd: '\\titlepage', desc: 'Portada (usa \\title, \\author, \\date).' },
            { cmd: '\\usetheme{Madrid}', desc: 'Tema visual de la presentación.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Si una diapositiva contiene **código verbatim** (`lstlisting`, `verbatim`), marcala como `\\begin{frame}[fragile]`; si no, beamer da un error al leer el contenido literal.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Una diapositiva = una idea. Evitá llenarla de texto: beamer es para apoyar lo que decís, no para que la audiencia lea párrafos.',
        },
      ],
      example: [
        '\\documentclass{beamer}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usetheme{Madrid}',
        '\\title{Mi presentación}',
        '\\author{Estudiante}',
        '\\date{\\today}',
        '',
        '\\begin{document}',
        '',
        '% Portada:',
        '\\begin{frame}',
        '  \\titlepage',
        '\\end{frame}',
        '',
        '% Diapositiva de contenido:',
        '\\begin{frame}{Puntos principales}',
        '  \\begin{itemize}',
        '    \\item Beamer reusa todo lo que ya sabés de LaTeX.',
        '    \\item Cada \\texttt{frame} es una diapositiva.',
        '    \\item La matemática funciona igual: $e^{i\\pi}+1=0$.',
        '  \\end{itemize}',
        '\\end{frame}',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: creá una presentación beamer con un frame y su \\frametitle (o título de frame).',
        starter: [
          '\\documentclass{beamer}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '% TODO: un \\begin{frame} con \\frametitle{...} y algo de contenido.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\documentclass{beamer}', '\\begin{frame}', '\\frametitle'],
        hints: ['El contenido va entre \\begin{frame} y \\end{frame}.'],
        solution: [
          '\\documentclass{beamer}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '\\begin{frame}',
          '  \\frametitle{Mi primera diapositiva}',
          '  Hola desde Beamer.',
          '\\end{frame}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Beamer a fondo'],
    },
    {
      id: 'l3-beamer-avanzado',
      level: 3,
      title: 'Beamer a fondo',
      capa: 'carpinteria',
      module: 'Presentaciones',
      objective: 'usar aparición por pasos (overlays), columnas y temas.',
      prerequisites: ['l3-beamer'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Lo que hace dinámica una charla: los **overlays** (el contenido aparece por pasos) y las **columnas**. Con `<2->` o `\\pause` controlás cuándo aparece cada cosa; con `columns`/`column` dividís la diapositiva en bloques lado a lado.',
        },
        {
          kind: 'prose',
          markdown:
            'La especificación `<...>` se puede aplicar a casi todo: `\\alert<2>{...}` resalta en el paso 2, `\\only<2>{...}` muestra y **no reserva lugar**, `\\uncover<2->{...}` lo reserva desde el arranque, y una lista con `[<+->]` revela un ítem por paso automáticamente. Para tus apuntes de orador está `\\note{...}` (con `\\setbeameroption{show notes}`), y las diapositivas de respaldo van tras `\\appendix` para no contar en la numeración.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\item<2->', desc: 'El ítem aparece a partir del paso 2.' },
            { cmd: '\\onslide<2->{...}', desc: 'Muestra el contenido desde el paso 2.' },
            { cmd: '\\pause', desc: 'Corta acá: lo de abajo aparece en el paso siguiente.' },
            { cmd: '\\begin{columns} ... \\begin{column}{0.5\\textwidth}', desc: 'Diapositiva en columnas.' },
            { cmd: '\\usetheme{...} / \\usecolortheme{...}', desc: 'Tema visual y de color.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'La especificación de overlay `<2->` significa “del paso 2 en adelante”; `<2>` es “solo en el paso 2”; `<-2>` es “hasta el 2”. Confundirlas hace que algo aparezca o desaparezca cuando no querés.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'La opción de clase `handout` (`\\documentclass[handout]{beamer}`) genera una versión **sin overlays** (todo visible de una), ideal para imprimir o repartir.',
        },
      ],
      example: [
        '\\documentclass{beamer}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usetheme{Madrid}',
        '\\usecolortheme{seahorse}',
        '',
        '\\begin{document}',
        '',
        '\\begin{frame}{Columnas y overlays}',
        '  \\begin{columns}',
        '    \\begin{column}{0.5\\textwidth}',
        '      Texto a la izquierda, siempre visible.',
        '    \\end{column}',
        '    \\begin{column}{0.5\\textwidth}',
        '      \\onslide<2->{Esto aparece recién en el paso 2.}',
        '    \\end{column}',
        '  \\end{columns}',
        '  \\bigskip',
        '  \\begin{itemize}',
        '    \\item<1-> Primer punto (paso 1).',
        '    \\item<2-> Segundo punto (paso 2).',
        '    \\item<3-> Tercer punto (paso 3).',
        '  \\end{itemize}',
        '\\end{frame}',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: en una diapositiva, usá columnas (\\begin{columns}) y un overlay (<2->).',
        starter: [
          '\\documentclass{beamer}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '\\begin{frame}{Demo}',
          '  % TODO (1): \\begin{columns} con dos \\begin{column}{0.5\\textwidth} ... \\end{column}',
          '  % TODO (2): que algo aparezca con \\onslide<2->{...} o un \\item<2->',
          '\\end{frame}',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\begin{columns}', '<2->'],
        hints: ['Cada columna va en \\begin{column}{0.5\\textwidth} ... \\end{column}.'],
        solution: [
          '\\documentclass{beamer}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '\\begin{frame}{Demo}',
          '  \\begin{columns}',
          '    \\begin{column}{0.5\\textwidth}',
          '      Izquierda.',
          '    \\end{column}',
          '    \\begin{column}{0.5\\textwidth}',
          '      \\onslide<2->{Derecha, en el paso 2.}',
          '    \\end{column}',
          '  \\end{columns}',
          '\\end{frame}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Presentaciones con Beamer'],
    },
  ],
} satisfies LevelInput
