import type { LevelInput } from '../types'

/** Nivel 2 · Intermedio — matemática rica, aparato del documento, bibliografía y programación. */
export const nivel2 = {
  level: 2,
  title: 'Intermedio',
  summary: 'Teoremas y matemática avanzada, numeración y cajas, bibliografía clásica y moderna, índices y macros.',
  lessons: [
    // ── Módulo: Matemática ────────────────────────────────────────────────
    {
      id: 'l2-teoremas',
      level: 2,
      title: 'Teoremas y demostraciones',
      capa: 'semantica',
      module: 'Matemática',
      objective: 'definir entornos de teorema numerados y escribir demostraciones.',
      prerequisites: ['l1-amsmath'],
      content: [
        {
          kind: 'prose',
          markdown:
            'En matemática querés entornos como *Teorema*, *Definición* o *Lema*, numerados solos. **amsthm** te deja **definirlos** con `\\newtheorem` y trae el entorno `proof`, que agrega el símbolo de fin (∎).',
        },
        {
          kind: 'prose',
          markdown:
            'amsthm distingue **tres estilos** visuales: `plain` (enunciado en cursiva, para teoremas), `definition` (texto derecho, para definiciones y ejemplos) y `remark` (más tenue, para observaciones). Se eligen con `\\theoremstyle{...}` **antes** de cada `\\newtheorem`.',
        },
        {
          kind: 'prose',
          markdown:
            'Para que la numeración **reinicie por sección** (Teorema 1.1, 1.2, 2.1…), agregá el contador entre corchetes: `\\newtheorem{teorema}{Teorema}[section]`. En documentos largos es lo más cómodo. Y si referenciás un teorema con `\\cref` (cleveref), te escribe “Teorema 1.1” solo; el paquete `thmtools` permite estilos más elaborados si hace falta.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\usepackage{amsthm}', desc: 'Habilita \\newtheorem y proof.' },
            { cmd: '\\theoremstyle{plain|definition|remark}', desc: 'Elige el estilo de los entornos que siguen.' },
            { cmd: '\\newtheorem{teorema}{Teorema}', desc: 'Define el entorno “teorema”, numerado.' },
            { cmd: '\\newtheorem{lema}[teorema]{Lema}', desc: 'Lema que comparte numeración con teorema.' },
            { cmd: '\\newtheorem*{obs}{Observación}', desc: 'Versión sin numerar (asterisco).' },
            { cmd: '\\begin{proof} ... \\end{proof}', desc: 'Demostración con ∎ al final.' },
          ],
        },
        {
          kind: 'code',
          caption: 'Numeración compartida: Teorema 1, Lema 2, Teorema 3…',
          latex: ['\\newtheorem{teorema}{Teorema}', '\\newtheorem{lema}[teorema]{Lema}  % comparte contador'].join('\n'),
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Los `\\newtheorem` y `\\theoremstyle` van en el **preámbulo**, no dentro del documento. Y el `\\theoremstyle` afecta a los `\\newtheorem` que vienen **después**, no a los anteriores.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Para terminar una demostración con un cálculo o una ecuación, usá `\\qedhere` así el ∎ queda en la línea correcta y no salta solo al renglón siguiente.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{amsthm}',
        '',
        '% Definimos los entornos en el preámbulo, agrupados por estilo:',
        '\\theoremstyle{plain}',
        '\\newtheorem{teorema}{Teorema}',
        '\\newtheorem{lema}[teorema]{Lema}      % comparte numeración con Teorema',
        '\\theoremstyle{definition}',
        '\\newtheorem{definicion}{Definición}',
        '\\theoremstyle{remark}',
        '\\newtheorem*{obs}{Observación}        % sin numerar',
        '',
        '\\begin{document}',
        '',
        '\\begin{definicion}',
        '  Un número $p > 1$ es \\emph{primo} si sus únicos divisores son $1$ y $p$.',
        '\\end{definicion}',
        '',
        '\\begin{teorema}[Euclides]',
        '  No existe un mayor número primo.',
        '\\end{teorema}',
        '',
        '\\begin{proof}',
        '  Supongamos que hay finitos primos $p_1, \\dots, p_n$. El número',
        '  $N = p_1 \\cdots p_n + 1$ no es divisible por ninguno, contradicción.',
        '\\end{proof}',
        '',
        '\\begin{obs}',
        '  La idea de la prueba es constructiva: produce un primo nuevo.',
        '\\end{obs}',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt:
          'Completá los TODO: definí un entorno de teorema con \\newtheorem en el preámbulo y escribí un teorema con su demostración (proof).',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{amsthm}',
          '% TODO (1): definí \\newtheorem{teorema}{Teorema} acá, en el preámbulo.',
          '',
          '\\begin{document}',
          '% TODO (2): escribí un \\begin{teorema} ... \\end{teorema}',
          '% TODO (3): y a continuación un \\begin{proof} ... \\end{proof}',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\newtheorem', '\\begin{proof}'],
        hints: ['\\newtheorem{nombre}{Etiqueta} va en el preámbulo.', 'El entorno proof viene con amsthm; no hace falta definirlo.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{amsthm}',
          '\\newtheorem{teorema}{Teorema}',
          '',
          '\\begin{document}',
          '\\begin{teorema}',
          '  No existe un mayor número primo.',
          '\\end{teorema}',
          '\\begin{proof}',
          '  Supongamos que sí; se llega a una contradicción.',
          '\\end{proof}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Matemática avanzada', 'Numeración y contadores'],
    },
    {
      id: 'l2-matematica-avanzada',
      level: 2,
      title: 'Matemática avanzada',
      capa: 'semantica',
      module: 'Matemática',
      objective: 'escribir matrices, definiciones por casos y cantidades con unidades.',
      prerequisites: ['l1-amsmath'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Con **amsmath**: las **matrices** (`pmatrix` con paréntesis, `bmatrix` con corchetes, `vmatrix` para determinantes) y `cases` (por tramos) funcionan como mini-tablas (`&` separa columnas, `\\\\` filas). Para **números con unidades**, el estándar es **siunitx**.',
        },
        {
          kind: 'prose',
          markdown:
            'Más estructuras útiles: `\\binom{n}{k}` (números combinatorios), `\\overbrace{...}^{}` y `\\underbrace{...}_{}` (llaves anotadas), `\\dots` (elige `\\ldots`/`\\cdots` según el contexto) y, para **alinear dentro** de una fórmula más grande, el entorno `aligned` (como `align`, pero anidable en `equation`). Para una matriz chiquita en medio del texto, `smallmatrix`.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\begin{pmatrix}', desc: 'Matriz con paréntesis ( ).' },
            { cmd: '\\begin{bmatrix}', desc: 'Matriz con corchetes [ ].' },
            { cmd: '\\begin{vmatrix}', desc: 'Determinante (barras verticales).' },
            { cmd: '\\begin{cases}', desc: 'Definición por casos (la llave aparece sola).' },
            { cmd: '\\binom{n}{k}', desc: 'Número combinatorio.' },
            { cmd: '\\underbrace{...}_{texto}', desc: 'Llave inferior con anotación.' },
            { cmd: '\\begin{aligned}', desc: 'Alinear varias líneas dentro de otra fórmula.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Las matrices y `cases` solo viven en **modo math**: van dentro de `$...$`, `\\[ ... \\]` o un entorno como `equation`. Fuera de math, dan error.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'No escribas `9.81 m/s^2` a mano: `siunitx` cuida el espacio fino entre número y unidad, evita cortes de línea feos y te deja cambiar de notación decimal en un solo lugar.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{amsmath}',
        '\\usepackage{siunitx}',
        '',
        '\\begin{document}',
        '',
        '% (1) Tres tipos de matriz:',
        '\\[ I = \\begin{pmatrix} 1 & 0 \\\\ 0 & 1 \\end{pmatrix}, \\qquad',
        '   A = \\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}, \\qquad',
        '   \\det A = \\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix} = ad - bc. \\]',
        '',
        '% (2) Definición por tramos:',
        '\\[ \\operatorname{sgn}(x) = \\begin{cases}',
        '   \\phantom{-}1 & \\text{si } x > 0 \\\\',
        '   \\phantom{-}0 & \\text{si } x = 0 \\\\',
        '   -1 & \\text{si } x < 0',
        '\\end{cases} \\]',
        '',
        '% (3) Cantidades con unidades (siunitx):',
        'La gravedad es \\qty{9.81}{m/s^2} y la masa, \\qty{2.5}{kg}.',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: una matriz con pmatrix y una definición por casos con cases, ambas dentro de \\[ ... \\].',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{amsmath}',
          '',
          '\\begin{document}',
          '% (1) Matriz identidad 2x2:',
          '\\[ I =  \\]  % TODO: usá \\begin{pmatrix} 1 & 0 \\\\ 0 & 1 \\end{pmatrix}',
          '',
          '% (2) Valor absoluto por casos:',
          '\\[ |x| =  \\]  % TODO: usá \\begin{cases} ... \\end{cases}',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\begin{pmatrix}', '\\begin{cases}'],
        hints: ['Van en modo math: ponelos dentro de \\[ ... \\].', 'En pmatrix y cases, & separa columnas y \\\\ separa filas.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{amsmath}',
          '',
          '\\begin{document}',
          '\\[ I = \\begin{pmatrix} 1 & 0 \\\\ 0 & 1 \\end{pmatrix} \\]',
          '\\[ |x| = \\begin{cases} x & x \\ge 0 \\\\ -x & x < 0 \\end{cases} \\]',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Más matemática (mathtools)'],
    },
    {
      id: 'l2-mathtools',
      level: 2,
      title: 'Más matemática (mathtools)',
      capa: 'semantica',
      module: 'Matemática',
      objective: 'usar delimitadores que escalan y ecuaciones de varias líneas.',
      prerequisites: ['l2-matematica-avanzada'],
      content: [
        {
          kind: 'prose',
          markdown:
            '**mathtools** extiende amsmath (lo carga por vos). Con `\\DeclarePairedDelimiter` definís delimitadores que **escalan** solos (como el valor absoluto o la norma), y con `multline` o el entorno `split` partís una ecuación larga en varias líneas alineadas.',
        },
        {
          kind: 'prose',
          markdown:
            'Por eso el estándar de la plataforma es cargar **mathtools, no `amsmath` a secas**: trae además `\\coloneqq` (`:=`), `dcases` (un `cases` con fracciones en tamaño display), flechas con etiquetas `\\xrightarrow[abajo]{arriba}`, columnas alineadas en matrices (`pmatrix*[r]`) y arregla bugs de amsmath. Si ya cargaste mathtools, **no** vuelvas a cargar amsmath (sería redundante).',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\usepackage{mathtools}', desc: 'Carga mathtools (incluye amsmath).' },
            { cmd: '\\DeclarePairedDelimiter{\\abs}{\\lvert}{\\rvert}', desc: 'Define \\abs con delimitadores escalables.' },
            { cmd: '\\abs{x}  /  \\abs*{\\frac{a}{b}}', desc: 'Tamaño normal / con * escala al contenido.' },
            { cmd: '\\begin{multline}', desc: 'Ecuación larga: primera línea a la izq., última a la der.' },
            { cmd: '\\coloneqq', desc: 'El símbolo := para definiciones.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'No uses `\\left|...\\right|` para el valor absoluto: produce barras que pueden quedar demasiado altas y el espaciado no siempre es correcto. Un delimitador con `\\DeclarePairedDelimiter` es la forma robusta.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'La versión con `*` (p. ej. `\\abs*{...}`) hace que los delimitadores crezcan con el contenido. Sin `*`, quedan de tamaño normal: útil cuando no querés que una fracción agrande las barras.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{mathtools}',
        '\\DeclarePairedDelimiter{\\abs}{\\lvert}{\\rvert}',
        '\\DeclarePairedDelimiter{\\norm}{\\lVert}{\\rVert}',
        '',
        '\\begin{document}',
        '',
        '% Delimitadores: normal vs. escalado con *',
        'Normal: $\\abs{x}$. Escalado: $\\abs*{\\dfrac{a}{b}}$. Norma: $\\norm{v}$.',
        '',
        '% Una definición con := y una ecuación larga partida:',
        '\\[ \\norm{v} \\coloneqq \\sqrt{v_1^2 + v_2^2 + v_3^2}. \\]',
        '',
        '\\begin{multline}',
        '  (a+b+c+d)^2 = a^2+b^2+c^2+d^2 \\\\',
        '  + 2(ab+ac+ad+bc+bd+cd).',
        '\\end{multline}',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: cargá mathtools, definí \\abs con \\DeclarePairedDelimiter y usalo en una fórmula.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '% TODO (1): cargá mathtools y definí \\abs con \\DeclarePairedDelimiter.',
          '',
          '\\begin{document}',
          'El valor absoluto: % TODO (2): escribí $\\abs{x} \\ge 0$.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\usepackage{mathtools}', '\\DeclarePairedDelimiter'],
        hints: ['Sintaxis: \\DeclarePairedDelimiter{\\abs}{\\lvert}{\\rvert} en el preámbulo.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{mathtools}',
          '\\DeclarePairedDelimiter{\\abs}{\\lvert}{\\rvert}',
          '',
          '\\begin{document}',
          'El valor absoluto: $\\abs{x} \\ge 0$.',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Matemática avanzada'],
    },
    // ── Módulo: Aparato y estilo ──────────────────────────────────────────
    {
      id: 'l2-numeracion',
      level: 2,
      title: 'Numeración y contadores',
      capa: 'carpinteria',
      module: 'Aparato y estilo',
      objective: 'controlar cómo se numeran teoremas, ecuaciones y secciones.',
      prerequisites: ['l2-teoremas'],
      content: [
        {
          kind: 'prose',
          markdown:
            'El “cómo se numera” son decisiones de carpintería independientes del contenido: **reiniciar** un contador por sección, **ligar** las ecuaciones a la sección, o controlar **hasta qué nivel** se numera.',
        },
        {
          kind: 'prose',
          markdown:
            'Por debajo, cada cosa numerada (sección, ecuación, figura, teorema) tiene un **contador**. Podés crear el tuyo con `\\newcounter{...}`, moverlo con `\\stepcounter`/`\\setcounter`, leerlo con `\\thecontador`, y **cambiarle el formato**: `\\renewcommand{\\thesection}{\\Roman{section}}` numera I, II, III…; también `\\alph` (a, b, c), `\\roman` (i, ii) y `\\arabic` (1, 2). Como todo cuelga de contadores, `\\label`/`\\ref` funcionan con cualquiera.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\newtheorem{teo}{Teorema}[section]', desc: 'Reinicia el contador en cada sección (2.1, 2.2…).' },
            { cmd: '\\numberwithin{equation}{section}', desc: 'Ecuaciones numeradas por sección (amsmath).' },
            { cmd: '\\setcounter{secnumdepth}{2}', desc: 'Numera hasta subsección, no más.' },
            { cmd: '\\setcounter{tocdepth}{2}', desc: 'Hasta qué nivel aparece en el índice.' },
            { cmd: '\\renewcommand{\\thesection}{\\Roman{section}}', desc: 'Cambia el formato del número (I, II, III…).' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            '`secnumdepth` controla qué se **numera**; `tocdepth`, qué aparece en el **índice**. Son cosas distintas: podés numerar subsubsecciones pero no listarlas en el índice, o al revés.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Ligar las ecuaciones a la sección (`\\numberwithin`) ayuda en documentos largos: una referencia a la ecuación (3.5) te dice de entrada en qué sección está.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{amsmath, amsthm}',
        '',
        '\\newtheorem{teo}{Teorema}[section]    % reinicia por sección',
        '\\numberwithin{equation}{section}      % ecuaciones por sección',
        '',
        '\\begin{document}',
        '',
        '\\section{Resultados}',
        '\\begin{teo}',
        '  Enunciado del primer teorema (será 1.1).',
        '\\end{teo}',
        '\\begin{equation}',
        '  a^2 + b^2 = c^2',
        '\\end{equation}',
        '',
        '\\section{Más resultados}',
        '\\begin{teo}',
        '  Otro teorema (será 2.1: el contador se reinició).',
        '\\end{teo}',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: definí un teorema que reinicie su numeración por sección con el argumento opcional [section].',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{amsthm}',
          '% TODO: definí \\newtheorem{teo}{Teorema}[section]',
          '',
          '\\begin{document}',
          '\\section{Una sección}',
          '% TODO: agregá un \\begin{teo} ... \\end{teo}',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\newtheorem', '[section]'],
        hints: ['El argumento opcional [section] va al final del \\newtheorem.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{amsthm}',
          '\\newtheorem{teo}{Teorema}[section]',
          '',
          '\\begin{document}',
          '\\section{Una sección}',
          '\\begin{teo} Enunciado. \\end{teo}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Documentos largos'],
    },
    {
      id: 'l2-listas-enumitem',
      level: 2,
      title: 'Listas a medida (enumitem)',
      capa: 'carpinteria',
      module: 'Aparato y estilo',
      objective: 'personalizar viñetas, numeración y espaciado de las listas.',
      prerequisites: ['l0-listas'],
      content: [
        {
          kind: 'prose',
          markdown:
            'El paquete **enumitem** da control fino sobre las listas: cambiar la **etiqueta**, **compactar** el espaciado o **continuar** una numeración cortada. Las opciones van entre `[ ]` justo después del `\\begin`.',
        },
        {
          kind: 'prose',
          markdown:
            'Para no repetir las mismas opciones en cada lista, configurá **globalmente** con `\\setlist[enumerate]{...}` en el preámbulo (afecta a todas las de ese tipo) o creá un **entorno propio** con `\\newlist{pasos}{enumerate}{1}` + `\\setlist[pasos]{...}`. Es DRY: el estilo se cambia en un solo lugar.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '[label=(\\alph*)]', desc: 'Etiquetas (a), (b), (c)…  (\\arabic*, \\roman*, \\Alph*).' },
            { cmd: '[noitemsep] / [nosep]', desc: 'Sin espacio entre ítems / sin nada de espacio.' },
            { cmd: '[resume]', desc: 'Continúa la numeración de una lista anterior.' },
            { cmd: '[leftmargin=*]', desc: 'Ajusta la sangría izquierda.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'En la opción `label`, el `*` (como en `\\alph*`) es lo que inserta el **valor actual** del contador. Sin el `*`, ponés una etiqueta fija igual para todos los ítems.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Las opciones se combinan separadas por coma: `[label=\\arabic*., noitemsep]`. Para un examen, `[label=\\arabic*)]` numera las preguntas como 1), 2), 3).',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{enumitem}',
        '',
        '\\begin{document}',
        '',
        '% (1) Etiquetas a medida y sin espacio extra:',
        '\\begin{enumerate}[label=(\\alph*), noitemsep]',
        '  \\item Primer caso.',
        '  \\item Segundo caso.',
        '\\end{enumerate}',
        '',
        'Un párrafo intermedio corta la lista.',
        '',
        '% (2) Continuamos la numeración anterior con resume:',
        '\\begin{enumerate}[label=(\\alph*), resume]',
        '  \\item Tercer caso (sigue en c).',
        '\\end{enumerate}',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: hacé una enumerate con etiquetas a medida usando la opción label de enumitem.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{enumitem}',
          '',
          '\\begin{document}',
          '% TODO: \\begin{enumerate}[label=(\\alph*)] con dos \\item',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\usepackage{enumitem}', 'label='],
        hints: ['Ejemplo: \\begin{enumerate}[label=(\\alph*)].'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{enumitem}',
          '',
          '\\begin{document}',
          '\\begin{enumerate}[label=(\\alph*)]',
          '  \\item Primer caso.',
          '  \\item Segundo caso.',
          '\\end{enumerate}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Cajas y resaltado'],
    },
    {
      id: 'l2-cajas',
      level: 2,
      title: 'Cajas y resaltado',
      capa: 'carpinteria',
      module: 'Aparato y estilo',
      objective: 'destacar contenido en cajas con color, título y marco.',
      prerequisites: ['l1-preambulo'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Para destacar definiciones, avisos o resultados, **tcolorbox** crea cajas con **color, título y marco** (y hasta teoremas en caja). Es mucho más flexible que `\\fbox`. Cargá `\\usepackage[most]{tcolorbox}` para tener todas las opciones.',
        },
        {
          kind: 'prose',
          markdown:
            'Hay un abanico según lo que necesites: `\\fbox`/`\\colorbox`/`\\fcolorbox` para un recuadro simple (sin paquetes); `mdframed` para marcos livianos que **pueden cortar entre páginas**; y `tcolorbox`, el más completo. Una caja larga que cruza página necesita la opción `breakable`; y con `tcbtheorem` armás teoremas “en caja”.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\usepackage[most]{tcolorbox}', desc: 'Carga el paquete con la mayoría de librerías.' },
            { cmd: '[title=...]', desc: 'Título de la caja.' },
            { cmd: '[colback=blue!5, colframe=blue!50!black]', desc: 'Color de fondo y de marco.' },
            { cmd: '[sharp corners] / [rounded corners]', desc: 'Esquinas rectas o redondeadas.' },
            { cmd: '\\tcbox{...}', desc: 'Caja chica en línea, para una palabra o frase.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'tcolorbox usa colores de `xcolor` (la sintaxis `blue!5` = 5% azul). Cargá `[most]` para que estén disponibles las librerías de estilos; con la carga mínima, algunas opciones fallan.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Usá cajas con criterio: una o dos por página resaltan; demasiadas marean. Definí **un** estilo y reutilizalo (con `\\newtcolorbox` podés crear tu propia caja con nombre).',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage[most]{tcolorbox}',
        '',
        '% Definimos una caja con nombre, reutilizable:',
        '\\newtcolorbox{definicion}[1]{colback=blue!5, colframe=blue!50!black, title=#1}',
        '',
        '\\begin{document}',
        '',
        '\\begin{definicion}{Continuidad}',
        '  Una función es continua si a pequeños cambios en la entrada les',
        '  corresponden pequeños cambios en la salida.',
        '\\end{definicion}',
        '',
        '\\begin{tcolorbox}[title=Atención, colback=red!5, colframe=red!60!black]',
        '  Una caja de aviso, con su propio color.',
        '\\end{tcolorbox}',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: creá una tcolorbox con un título.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage[most]{tcolorbox}',
          '',
          '\\begin{document}',
          '% TODO: \\begin{tcolorbox}[title=Mi caja] ... \\end{tcolorbox}',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\usepackage[most]{tcolorbox}', '\\begin{tcolorbox}'],
        hints: ['\\begin{tcolorbox}[title=Mi caja] ... \\end{tcolorbox}.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage[most]{tcolorbox}',
          '',
          '\\begin{document}',
          '\\begin{tcolorbox}[title=Mi caja]',
          '  Contenido destacado.',
          '\\end{tcolorbox}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Listas a medida (enumitem)'],
    },
    // ── Módulo: Bibliografía e índices ────────────────────────────────────
    {
      id: 'l2-bibliografia',
      level: 2,
      title: 'Bibliografía clásica',
      capa: 'semantica',
      module: 'Bibliografía e índices',
      objective: 'citar fuentes y armar una lista de referencias autocontenida.',
      prerequisites: ['l1-referencias'],
      content: [
        {
          kind: 'prose',
          markdown:
            'La forma autocontenida de citar: declarás las fuentes en el entorno `thebibliography` (cada una con `\\bibitem{clave}`) y las referenciás con `\\cite{clave}`. LaTeX numera las entradas y enlaza las citas con su número.',
        },
        {
          kind: 'prose',
          markdown:
            'La idea de fondo —igual que en las referencias cruzadas— es **separar el contenido del estilo**: citás por una **clave estable** y el sistema decide cómo se ve (numérico `[1]` o autor-año `(Knuth, 1984)`). `thebibliography` lo hace a mano; el clásico **BibTeX** lee un archivo `.bib` y arma la lista solo (`\\bibliographystyle` + `\\bibliography`); y **biblatex** (la próxima lección) es la versión moderna y flexible. Poné `~\\cite` con tilde para que el número no quede colgando.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\cite{clave}', desc: 'Inserta la cita [1] en el texto.' },
            { cmd: '\\cite[p.~12]{clave}', desc: 'Cita con detalle de página: [1, p. 12].' },
            { cmd: '\\begin{thebibliography}{9}', desc: 'Lista de referencias (el 9 estima el ancho del número).' },
            { cmd: '\\bibitem{clave}', desc: 'Una entrada de la bibliografía.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'La clave de `\\cite{clave}` debe coincidir **exactamente** con la de algún `\\bibitem{clave}`. Si no, vas a ver `[?]` en el PDF. Y necesita dos pasadas (acá ya se hacen).',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            'Sirve para trabajos chicos. Para algo grande, reutilizable o con un estilo de cita preciso (APA, IEEE), conviene **biblatex** (próxima lección).',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '',
        '\\begin{document}',
        '',
        'El sistema TeX fue creado por Knuth~\\cite{texbook}, y LaTeX lo extendió',
        'con un lenguaje de marcado de alto nivel~\\cite[cap.~1]{latexcompanion}.',
        '',
        '\\begin{thebibliography}{9}',
        '  \\bibitem{texbook} D.~Knuth, \\emph{The \\TeX book}, Addison-Wesley, 1984.',
        '  \\bibitem{latexcompanion} F.~Mittelbach et al., \\emph{The \\LaTeX\\ Companion}, 2004.',
        '\\end{thebibliography}',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: citá una fuente con \\cite y declarala en thebibliography con \\bibitem (misma clave).',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          'Según Knuth~% TODO: \\cite{texbook}',
          ', TeX compone tipografía de calidad.',
          '',
          '% TODO: agregá un entorno thebibliography con un \\bibitem{texbook}.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\cite', '\\begin{thebibliography}', '\\bibitem'],
        hints: ['La clave de \\cite{clave} debe coincidir con la de \\bibitem{clave}.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          'Según Knuth~\\cite{texbook}, TeX compone tipografía de calidad.',
          '',
          '\\begin{thebibliography}{9}',
          '  \\bibitem{texbook} D.~Knuth, \\emph{The TeXbook}, 1984.',
          '\\end{thebibliography}',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Bibliografía moderna (biblatex)'],
    },
    {
      id: 'l2-bibliografia-moderna',
      level: 2,
      title: 'Bibliografía moderna (biblatex)',
      capa: 'semantica',
      module: 'Bibliografía e índices',
      objective: 'gestionar referencias desde un archivo .bib con biblatex y biber.',
      prerequisites: ['l2-bibliografia'],
      content: [
        {
          kind: 'prose',
          markdown:
            'En proyectos serios, las referencias viven en un archivo **`.bib`** (exportable desde Zotero/Mendeley) y se gestionan con **biblatex** + el programa **biber**. Citás con `\\textcite` (en el texto: “Knuth (1984)…”) o `\\parencite` (entre paréntesis) y la lista sale con `\\printbibliography`.',
        },
        {
          kind: 'prose',
          markdown:
            'Cada entrada del `.bib` tiene un **tipo** y campos: `@book{clave, author={...}, title={...}, year={...}}`, `@article{...}` (con `journal`, `volume`), `@inproceedings{...}` (con `booktitle`). La clave es lo que citás. biblatex se prefiere a BibTeX porque maneja **Unicode**, ordena e internacionaliza (estilos en español), y cambiar de estilo (numeric → authoryear → apa) es **una sola opción**. `\\nocite{*}` agrega a la lista entradas que no citaste.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\usepackage[backend=biber, style=numeric]{biblatex}', desc: 'Carga biblatex con motor y estilo.' },
            { cmd: '\\addbibresource{refs.bib}', desc: 'Indica el archivo de referencias.' },
            { cmd: '\\textcite{clave}', desc: 'Cita integrada en la oración.' },
            { cmd: '\\parencite{clave}', desc: 'Cita entre paréntesis.' },
            { cmd: '\\printbibliography', desc: 'Imprime la lista de referencias.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'biblatex requiere correr **biber** entre pasadas; `latexmk` (y este backend) lo hacen solos. Si cambiás el `.bib` y no se actualiza, suele faltar esa pasada de biber.',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            'El estilo (`style=numeric`, `authoryear`, `apa`…) decide cómo se ven las citas y la lista. Acá el `.bib` es un **archivo aparte del proyecto** (`refs.bib`, abajo) — así se trabaja en la práctica, exportándolo desde Zotero o Mendeley.',
        },
      ],
      mainFile: 'main.tex',
      files: [
        {
          path: 'refs.bib',
          content: [
            '@book{knuth1984, author={Knuth, Donald}, title={The TeXbook},',
            '  year={1984}, publisher={Addison-Wesley}}',
            '@book{mittelbach2004, author={Mittelbach, Frank}, title={The LaTeX Companion},',
            '  year={2004}, publisher={Addison-Wesley}}',
            '',
          ].join('\n'),
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage[backend=biber, style=authoryear]{biblatex}',
        '\\addbibresource{refs.bib}   % archivo aparte del proyecto (panel de Archivos)',
        '',
        '\\begin{document}',
        '',
        'Según \\textcite{knuth1984}, TeX produce tipografía de calidad, idea',
        'extendida luego por LaTeX \\parencite{mittelbach2004}.',
        '',
        '\\printbibliography',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: cargá biblatex, citá con \\textcite y mostrá la lista con \\printbibliography.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage[backend=biber]{biblatex}',
          '\\addbibresource{refs.bib}   % el archivo refs.bib ya está en el proyecto',
          '',
          '\\begin{document}',
          'Según % TODO: \\textcite{knuth1984}, TeX es un sistema de composición.',
          '% TODO: imprimí la lista con \\printbibliography',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['{biblatex}', '\\printbibliography'],
        hints: ['Las citas van con \\textcite o \\parencite; la lista, con \\printbibliography.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage[backend=biber]{biblatex}',
          '\\addbibresource{refs.bib}',
          '',
          '\\begin{document}',
          'Según \\textcite{knuth1984}, TeX es un sistema de composición.',
          '\\printbibliography',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Bibliografía clásica', 'Índices, glosarios y nomenclatura'],
    },
    {
      id: 'l2-indices',
      level: 2,
      title: 'Índices, glosarios y nomenclatura',
      capa: 'semantica',
      module: 'Bibliografía e índices',
      objective: 'generar un índice alfabético automático del documento.',
      prerequisites: ['l1-hyperref'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Un **índice alfabético** se arma marcando términos con `\\index{...}` y dejando que LaTeX (con el programa `makeindex`) los ordene. Se activa con `\\makeindex` en el preámbulo y se imprime con `\\printindex` al final.',
        },
        {
          kind: 'prose',
          markdown:
            'La sintaxis de `\\index` tiene tres operadores útiles: `!` arma **subniveles** (`tema!subtema`); `@` separa **cómo ordenar** de **cómo se ve** (`\\alpha@$\\alpha$` ordena por “alpha”); y `|` aplica **formato o referencias** (`término|textbf` para negrita, `término|see{otro}` para “véase”). Para que el orden respete acentos y la ñ del español, conviene `imakeidx` con `xindy` en vez del `makeindex` clásico.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\usepackage{makeidx}', desc: 'Habilita el índice alfabético.' },
            { cmd: '\\makeindex', desc: 'Activa la recolección de entradas (en el preámbulo).' },
            { cmd: '\\index{término}', desc: 'Marca un término para el índice.' },
            { cmd: '\\index{tema!subtema}', desc: 'Entrada con subnivel jerárquico.' },
            { cmd: '\\printindex', desc: 'Imprime el índice ordenado.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'El `\\index{...}` se pega **sin espacio** a la palabra que indexa (`derivada\\index{derivada}`), si no, la página puede quedar corrida. Necesita una pasada extra de `makeindex` que `latexmk` resuelve.',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            'Para listas de símbolos está `nomencl`, y para **glosarios/acrónimos**, el paquete `glossaries` (defina términos una vez y los reutiliza con su definición y su sigla).',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{makeidx}',
        '\\makeindex',
        '',
        '\\begin{document}',
        '',
        '\\section{Cálculo}',
        'La derivada\\index{derivada} mide la tasa de cambio, y la',
        'integral\\index{integral} acumula. La regla de la cadena',
        '\\index{derivada!regla de la cadena} es central.',
        '',
        '\\printindex',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: activá el índice con \\makeindex, marcá un término con \\index y mostralo con \\printindex.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{makeidx}',
          '% TODO (1): activá el índice con \\makeindex',
          '',
          '\\begin{document}',
          'La derivada% TODO (2): marcala con \\index{derivada}',
          ' mide la tasa de cambio.',
          '% TODO (3): imprimí el índice con \\printindex',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\makeindex', '\\index{', '\\printindex'],
        hints: ['\\index{término} se pega a la palabra que querés indexar.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{makeidx}',
          '\\makeindex',
          '',
          '\\begin{document}',
          'La derivada\\index{derivada} mide la tasa de cambio.',
          '\\printindex',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Documentos largos'],
    },
    // ── Módulo: Programación ──────────────────────────────────────────────
    {
      id: 'l2-macros',
      level: 2,
      title: 'Macros y comandos propios',
      capa: 'semantica',
      module: 'Programación',
      objective: 'definir comandos propios, con argumentos, para no repetir y ganar consistencia.',
      prerequisites: ['l1-amsmath'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Si escribís algo muchas veces, definí una **macro** con `\\newcommand`. Da **consistencia**: cambiás la notación en un solo lugar y se actualiza en todo el documento. Pueden tomar argumentos (`#1`, `#2`) y hasta uno **opcional** con valor por defecto.',
        },
        {
          kind: 'prose',
          markdown:
            'Acá se cruza con la idea central de LaTeX: definí macros **semánticas** (`\\conjunto{...}` en vez de poner las llaves a mano), así un cambio de estilo se hace en un solo lugar. Para bloques con apertura y cierre está `\\newenvironment`. Y si una macro matemática (`\\R`) se te puede colar en texto, envolvela en `\\ensuremath{\\mathbb{R}}` para que ande dentro y fuera del modo math.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\newcommand{\\R}{\\mathbb{R}}', desc: 'Macro sin argumentos: \\R → ℝ.' },
            { cmd: '\\newcommand{\\abs}[1]{\\lvert#1\\rvert}', desc: 'Con un argumento: \\abs{x} → |x|.' },
            { cmd: '\\newcommand{\\pot}[2][2]{#2^{#1}}', desc: 'Argumento opcional [2]: \\pot{x}=x^2, \\pot[3]{x}=x^3.' },
            { cmd: '\\renewcommand{\\x}{...}', desc: 'Redefine un comando existente, a propósito.' },
            { cmd: '\\NewDocumentCommand{\\v}{O{n} m}{...}', desc: 'Comando moderno (LaTeX3), más flexible.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Las definiciones van en el **preámbulo**. Si el nombre ya existe, `\\newcommand` da error (*command already defined*): ahí va `\\renewcommand`, y solo si de verdad querés pisarlo.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Usá nombres **claros** (`\\abs`, `\\norm`, `\\R`), no `\\a` ni `\\x`. Una buena macro documenta tu notación: quien lee tu `.tex` entiende la intención.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{amsmath}   % \\lvert, \\rvert',
        '\\usepackage{amssymb}   % \\mathbb',
        '',
        '% Macros propias, en el preámbulo:',
        '\\newcommand{\\R}{\\mathbb{R}}                 % sin argumentos',
        '\\newcommand{\\abs}[1]{\\lvert #1 \\rvert}      % un argumento',
        '\\newcommand{\\pot}[2][2]{#2^{#1}}            % argumento opcional (default 2)',
        '',
        '\\begin{document}',
        '',
        'Para todo $x \\in \\R$ vale $\\abs{x} \\ge 0$.',
        '',
        'Potencias con la misma macro: $\\pot{x}$ (cuadrado) y $\\pot[3]{x}$ (cubo).',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt: 'Completá: definí una macro con \\newcommand (con argumento) y usala en una fórmula.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{amsmath}',
          '% TODO (1): definí \\newcommand{\\abs}[1]{\\lvert #1 \\rvert}',
          '',
          '\\begin{document}',
          '% TODO (2): usala, por ejemplo $\\abs{x} \\ge 0$.',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\newcommand'],
        hints: ['Con argumentos: \\newcommand{\\nombre}[1]{... #1 ...}.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\usepackage{amsmath}',
          '\\newcommand{\\abs}[1]{\\lvert #1 \\rvert}',
          '',
          '\\begin{document}',
          '$\\abs{x} \\ge 0$ para todo $x$.',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Compilación condicional', 'Paquetes propios'],
    },
  ],
} satisfies LevelInput
