import type { LevelInput } from '../types'

/** Nivel 0 · Supervivencia — lo mínimo para producir un documento decente. */
export const nivel0 = {
  level: 0,
  title: 'Supervivencia',
  summary:
    'Lo mínimo para compilar un documento y obtener un PDF decente. Al terminar, ya podés producir solo.',
  lessons: [
    {
      id: 'l0-bienvenida',
      level: 0,
      title: 'Bienvenida: qué es esto y por qué LaTeX',
      capa: 'semantica',
      module: 'Empezar acá',
      objective: 'entender qué es esta plataforma, qué es LaTeX y por qué vale la pena aprenderlo.',
      content: [
        {
          kind: 'prose',
          markdown:
            'Te damos la **bienvenida**. Esta plataforma te acompaña a **aprender y usar LaTeX**, el sistema con el que se escriben los documentos científicos y técnicos del mundo. Tiene **dos mitades que se complementan: aprender y producir.**',
        },
        {
          kind: 'prose',
          markdown:
            'Las dos mitades:\n\n- **Curso** — la ruta de lecciones. Cada una tiene tres vistas: **Aprender** (la explicación), **Ejemplo** (un documento completo que compilás y explorás) y **Practicar** (completás código y se autocorrige), más un modo **Repasar** con preguntas espaciadas.\n- **Galería** — documentos modelo reales y completos, uno por cada tipo: monografía, tesina, *paper*, apunte, presentación *beamer*, libro, informe KOMA, carta, examen, CV y póster. Para ver cómo se arma cada uno con buenas prácticas y, con **“Usar como base”**, copiar cualquiera para arrancar un proyecto.\n- **Mis Proyectos** — tu **taller**: creás documentos desde cero o desde una plantilla, trabajás con **varios archivos** (e imágenes), compilás, y descargás el PDF o todo el proyecto en `.zip`. Todo se organiza en carpetas.',
        },
        {
          kind: 'prose',
          markdown:
            'En una frase: en el **Curso** aprendés, y en **Galería + Mis Proyectos** producís lo tuyo. No hace falta terminar el curso para empezar a escribir: podés ir y volver entre aprender y producir cuando quieras.',
        },
        {
          kind: 'prose',
          markdown:
            '**¿Qué es LaTeX?** Es un *sistema de composición de documentos*. En vez de acomodar todo a mano como en un procesador de texto, escribís **texto plano con marcas** (“esto es una sección”, “esto es una ecuación”) y un programa —el **compilador**— produce un PDF con calidad de imprenta.',
        },
        {
          kind: 'prose',
          markdown:
            'Nació de una frustración: en **1978**, el matemático **Donald Knuth** estaba tan disconforme con cómo se veían sus libros que creó **TeX**, un motor tipográfico obsesivamente cuidadoso. En **1984**, **Leslie Lamport** construyó **LaTeX** encima, con comandos de alto nivel (secciones, listas, referencias) para que cualquiera pudiera usarlo. Cuatro décadas después, sigue siendo el estándar.',
        },
        {
          kind: 'prose',
          markdown:
            '**¿Por qué aprenderlo?** Porque es el **estándar de facto** en matemática, física, computación e ingeniería. Las tesis, los *papers*, los libros de texto y repositorios como **arXiv** se escriben mayoritariamente en LaTeX, y muchas revistas lo piden como formato de envío. Es una herramienta profesional que probablemente te acompañe durante toda la carrera.',
        },
        {
          kind: 'prose',
          markdown:
            '**¿LaTeX o un procesador de texto?** No es una rivalidad: son herramientas pensadas para trabajos distintos, y elegir la adecuada es parte del oficio.\n\n- Un **procesador** (Word, Google Docs, LibreOffice) es excelente para escribir rápido viendo el resultado al instante, **colaborar en tiempo real**, y usar comentarios y control de cambios con personas no técnicas. Ideal para textos cortos y trabajo de oficina.\n- **LaTeX** se luce cuando el contenido pesa más que el maquetado: **matemática** con calidad editorial, **documentos largos y estructurados** (informes, tesis, libros) donde índices, numeración y referencias se mantienen solos, **reproducibilidad** (es texto plano: se versiona con `git` y compila igual en cualquier máquina y dentro de años) y un **control tipográfico** fino. Además es libre y gratuito.',
        },
        {
          kind: 'prose',
          markdown:
            'Para lo que vas a hacer en la carrera —resolver y comunicar matemática, escribir informes y, más adelante, una tesis o un *paper*— LaTeX es la opción más sólida, y de ahí que sea el estándar en las ciencias exactas. Como toda herramienta potente, tiene un **costo de entrada**: una curva de aprendizaje. Este curso existe para que esa curva sea corta. *(Si te interesa el panorama más amplio, **Typst** es una alternativa moderna que comparte la idea de “texto que se compila”; lo mencionamos para que sepas que el campo también evoluciona.)*',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'La filosofía del curso, en una frase: **primero el significado, después la forma, y la carpintería solo cuando hace falta**. Con el nivel básico (Niveles 0 y 1) ya vas a producir documentos de calidad por tu cuenta — a eso le llamamos *supervivencia*.',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            'Para empezar, tocá **Ver el ejemplo** acá abajo y mirá LaTeX en acción; después seguí con **Practicar**. Cuando quieras explorar documentos completos, pasá por la **Galería**, y cuando quieras escribir lo tuyo, andá a **Mis Proyectos**.',
        },
      ],
      example: [
        '\\documentclass[11pt,a4paper]{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '\\usepackage{amsmath}',
        '',
        '\\title{Esto es \\LaTeX}',
        '\\author{Tu nombre}',
        '\\date{\\today}',
        '',
        '\\begin{document}',
        '\\maketitle',
        '',
        '% Escribís el SIGNIFICADO; LaTeX se encarga del formato.',
        '\\section{Texto y estructura}',
        'Marcás \\emph{qué} es cada cosa y obtenés tipografía cuidada, secciones',
        'numeradas y un PDF prolijo, sin acomodar nada a mano.',
        '',
        '\\section{Matemática impecable}',
        'La identidad de Euler conecta cinco constantes fundamentales:',
        '\\[ e^{i\\pi} + 1 = 0. \\]',
        '',
        'Y una integral clásica, sin esfuerzo:',
        '\\[ \\int_0^{\\infty} e^{-x^2}\\,dx = \\frac{\\sqrt{\\pi}}{2}. \\]',
        '',
        '\\section{Listo para crecer}',
        'Con lo básico ya producís documentos de calidad. Después vienen tablas,',
        'figuras, bibliografía, presentaciones y mucho más.',
        '\\end{document}',
        '',
      ].join('\n'),
      seeAlso: ['Cómo pensar un documento'],
    },
    {
      id: 'l0-pensar-documento',
      level: 0,
      title: 'Cómo pensar un documento',
      capa: 'semantica',
      module: 'Fundamentos',
      objective:
        'distinguir las tres capas de un documento (significado, forma e infraestructura) para no mezclarlas.',
      content: [
        {
          kind: 'prose',
          markdown:
            'La clave para no sufrir LaTeX es separar **tres preguntas distintas** que solemos mezclar:\n\n1. **¿Qué estoy diciendo?** — el significado: una sección, un teorema, una cita. (*Semántica*.)\n2. **¿Cómo se ve?** — márgenes, espaciado, fuentes. (*Carpintería*.)\n3. **¿Con qué se produce?** — la clase, los paquetes, el compilador. (*Infraestructura*.)',
        },
        {
          kind: 'prose',
          markdown:
            'A diferencia de Word, LaTeX te empuja a escribir primero el **significado** (“esto es una sección”) y deja el **cómo se ve** en manos de la clase y los temas. Por eso un documento LaTeX se ve consistente sin que vos ajustes nada a mano.',
        },
        {
          kind: 'prose',
          markdown:
            'En el código, cada capa se reconoce por los comandos que usás:\n\n- **Semántica** — `\\section`, `\\emph`, `\\begin{theorem}`: declarás *qué es* cada cosa.\n- **Carpintería** — `geometry` (márgenes), `setspace` (interlineado): ajustás *cómo se ve*.\n- **Infraestructura** — `\\documentclass`, `\\usepackage`: elegís *con qué se produce*.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Regla de oro: **primero el significado, después la forma, y la carpintería solo cuando hace falta**. Si te encontrás ajustando espacios a mano al empezar, frená: casi siempre es señal de que falta pensar la estructura.',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            'En cada lección vas a ver una etiqueta de **capa** (Semántica · Carpintería · Infraestructura) para ubicar qué tipo de cosa estás aprendiendo. Este curso recorre las tres, en ese orden de prioridad.',
        },
      ],
      example: [
        '\\documentclass{article}        % INFRAESTRUCTURA: con qué se produce',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage{microtype}',
        '\\usepackage[spanish,es-noshorthands]{babel}    % INFRAESTRUCTURA: idioma del documento',
        '',
        '\\begin{document}',
        '',
        '% --- SEMÁNTICA: qué estoy diciendo ---',
        '\\section{Una idea}',
        'El contenido importa más que su formato: primero el \\emph{significado}.',
        '',
        'Una línea en blanco arriba empieza un párrafo nuevo. Eso también es',
        'semántica: estoy diciendo “acá arranca otra idea”.',
        '',
        '% --- CARPINTERÍA: cómo se ve (solo cuando de verdad hace falta) ---',
        '% Acá no tocamos nada: la clase article ya da un diseño consistente.',
        '% Recién en el Nivel 1 vamos a ajustar márgenes, interlineado, etc.',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt:
          'Completá los dos TODO: declará una sección (semántica) y marcá una palabra con énfasis (semántica). No toques formato: practicá pensar en el “qué”.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\begin{document}',
          '',
          '% (1) Semántica: declará el “qué” con una sección.',
          '% TODO: agregá una \\section{Una idea} debajo de esta línea.',
          '',
          'El contenido importa más que su formato.',
          '% (2) Semántica: marcá una palabra con énfasis.',
          '% TODO: reemplazá la palabra “formato” de arriba por \\emph{formato}.',
          '',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\section', '\\emph'],
        hints: [
          '\\section{título} declara una sección; LaTeX la numera y formatea sola.',
          '\\emph{palabra} marca énfasis (significado), no “cursiva” (formato).',
        ],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '\\begin{document}',
          '',
          '\\section{Una idea}',
          'El contenido importa más que su \\emph{formato}.',
          '',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Tu primer documento'],
    },
    {
      id: 'l0-primer-documento',
      level: 0,
      title: 'Tu primer documento',
      capa: 'semantica',
      module: 'Fundamentos',
      objective: 'crear, compilar y obtener el PDF de un documento mínimo en LaTeX.',
      prerequisites: ['l0-pensar-documento'],
      content: [
        {
          kind: 'prose',
          markdown:
            'En LaTeX escribís **texto plano con instrucciones**: los **comandos**, que empiezan con una barra invertida (`\\`). Después, un **compilador** transforma ese texto en un PDF. En esta plataforma, el botón **Compilar** hace ese paso.',
        },
        {
          kind: 'prose',
          markdown:
            'Todo documento tiene **dos partes obligatorias**:\n\n1. `\\documentclass{...}` declara el *tipo* de documento (acá, `article`).\n2. El contenido va **dentro** de `\\begin{document}` … `\\end{document}`.\n\nLo que va entre el `\\documentclass` y el `\\begin{document}` es el **preámbulo** (configuración); lo vemos en el Nivel 1.',
        },
        {
          kind: 'commands',
          title: 'Comandos clave',
          items: [
            { cmd: '\\documentclass{article}', desc: 'Tipo de documento. article sirve para TPs y papers.' },
            { cmd: '\\begin{document}', desc: 'Comienzo del contenido visible.' },
            { cmd: '\\end{document}', desc: 'Final. Todo lo posterior se ignora.' },
            { cmd: '\\section{...}', desc: 'Un título de sección (significado).' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Error típico: olvidar el `\\end{...}` de un entorno. Todo `\\begin{x}` necesita su `\\end{x}`, o el compilador corta.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Buena práctica: indentá el contenido dentro de los entornos. A LaTeX le da igual, pero a vos te ayuda a ver qué `\\begin` cierra cada `\\end`.',
        },
      ],
      example: [
        '\\documentclass{article}   % 1) el tipo de documento',
        '',
        '\\begin{document}          % 2) acá empieza el contenido visible',
        '',
        '\\section{Introducción}',
        'Este es mi primer documento en LaTeX. El texto se escribe normalmente,',
        'y LaTeX se encarga del formato.',
        '',
        'Una línea en blanco arriba empieza un párrafo nuevo: este es el segundo.',
        '',
        '\\end{document}           % todo lo que va después de esta línea se ignora',
        '',
      ].join('\n'),
      challenge: {
        prompt:
          'Completá el documento: agregá una \\section con un título y un párrafo debajo, de modo que compile.',
        starter: [
          '\\documentclass{article}',
          '',
          '\\begin{document}',
          '',
          '% TODO: agregá una \\section{Introducción} y, debajo, un párrafo.',
          '',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\documentclass', '\\begin{document}', '\\end{document}', '\\section'],
        hints: ['La \\section va dentro del entorno document, antes del \\end{document}.'],
        solution: [
          '\\documentclass{article}',
          '',
          '\\begin{document}',
          '',
          '\\section{Introducción}',
          'Hola, mundo. Este es mi primer documento en LaTeX.',
          '',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['La base de todo documento', 'Compilar, errores y el log', 'Estructura y texto'],
    },
    {
      id: 'l0-base-preambulo',
      level: 0,
      title: 'La base de todo documento',
      capa: 'infraestructura',
      module: 'Fundamentos',
      objective: 'reconocer el preámbulo base que se repite en casi todos los ejemplos y saber dónde se explica en detalle.',
      prerequisites: ['l0-primer-documento'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Cuando mires los **ejemplos**, las **prácticas**, las **plantillas** y la **Galería**, vas a notar que casi todos empiezan con las **mismas cuatro líneas** después de `\\documentclass`. No es casualidad ni relleno: es la **base** (le decimos el *piso*) que conviene tener en **todo** documento en español. Acá te la presentamos para que la reconozcas; enseguida ves qué hace cada una.',
        },
        {
          kind: 'commands',
          title: 'El piso: cuatro líneas que van casi siempre',
          items: [
            { cmd: '\\usepackage[T1]{fontenc}', desc: 'Acentos que se copian del PDF y palabras que se cortan bien.' },
            { cmd: '\\usepackage{lmodern}', desc: 'Fuentes vectoriales nítidas (no se pixelan al hacer zoom).' },
            { cmd: '\\usepackage[spanish,es-noshorthands]{babel}', desc: 'Idioma español; es-noshorthands evita bugs con URLs/tablas/gráficos.' },
            { cmd: '\\usepackage{microtype}', desc: 'Un pulido tipográfico casi gratis: la página se ve pareja.' },
          ],
        },
        {
          kind: 'code',
          caption: 'La base, lista para copiar al empezar cualquier documento en español',
          latex: [
            '\\documentclass[11pt,a4paper]{article}',
            '\\usepackage[T1]{fontenc}',
            '\\usepackage{lmodern}',
            '\\usepackage[spanish,es-noshorthands]{babel}',
            '\\usepackage{microtype}',
          ].join('\n'),
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            '**No hace falta que la memorices ahora.** En este nivel, copiala y seguí con el contenido. El **detalle completo** —qué hace exactamente cada paquete, por qué en ese orden, y qué se agrega según lo que el documento tenga (matemática, tablas, gráficos)— está en la lección **El canon del preámbulo** (Nivel 1), y con más profundidad todavía en la guía de *Estándares y buenas prácticas*.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'La regla en una frase: hay un **piso** que va siempre (estas cuatro líneas) y lo **extra** se agrega solo si el contenido lo usa. Por eso un ejemplo de tablas carga `booktabs` y uno de gráficos `pgfplots`, pero **todos** comparten el piso.',
        },
      ],
      example: [
        '\\documentclass[11pt,a4paper]{article}',
        '',
        '% ── La base (el "piso"): se repite en casi todo documento en español ──',
        '\\usepackage[T1]{fontenc}                      % acentos que se copian bien',
        '\\usepackage{lmodern}                          % fuentes nítidas',
        '\\usepackage[spanish,es-noshorthands]{babel}   % idioma español',
        '\\usepackage{microtype}                        % pulido tipográfico',
        '',
        '\\begin{document}',
        '',
        'Este documento arranca con la base de siempre. Por eso los acentos',
        '(función, árbol, pingüino) y el guionado salen bien desde el principio,',
        'sin configurar nada más.',
        '',
        'En el Nivel 1, la lección \\emph{El canon del preámbulo} explica en detalle',
        'qué hace cada línea y qué conviene agregar según el contenido.',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      seeAlso: ['El canon del preámbulo', 'El preámbulo y los paquetes', 'Idioma y codificación'],
    },
    {
      id: 'l0-compilar-errores',
      level: 0,
      title: 'Compilar, errores y el log',
      capa: 'infraestructura',
      module: 'Fundamentos',
      objective: 'entender el ciclo de compilación y cómo leer un error de LaTeX.',
      prerequisites: ['l0-primer-documento'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Compilar es traducir tu `.tex` a PDF. La herramienta estándar es **latexmk**, que corre el motor las veces necesarias (por ejemplo, dos pasadas para resolver referencias e índices). Acá lo hace el botón **Compilar**.',
        },
        {
          kind: 'prose',
          markdown:
            'Cuando algo falla, LaTeX escribe un **log** y un mensaje que empieza con `!`. Lo más útil es la línea `l.N`, que indica **en qué línea** se rompió. Leé el **primer** error: los siguientes suelen ser consecuencia de ese.',
        },
        {
          kind: 'code',
          caption: 'Anatomía de un error: el ! y la línea l.N apuntan al problema',
          latex: ['! Undefined control sequence.', 'l.5 \\secton', '            {Introducción}'].join('\n'),
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Errores clásicos: olvidar un `\\end{...}`, una llave `{` sin cerrar, o usar `^`/`_` fuera del modo math. La causa real suele estar en **la línea anterior** a la que marca el log.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Estrategia ante un error: arreglá **solo el primero**, recompilá, y repetí. No intentes resolver toda la lista de una: la mayoría se desvanece al corregir el de arriba.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '',
        '\\begin{document}',
        '',
        '\\section{Prueba}',
        'Este documento compila. Para ver un error a propósito, borrá la llave de',
        'cierre de la sección de arriba y volvé a compilar.',
        '',
        'Cuando algo falla, mirá el mensaje que empieza con ``!\'\' y la línea',
        '\\texttt{l.N}: ahí está la pista de dónde se rompió.',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt:
          'A este documento le falta el cierre. Completá la línea que lo cierra para que compile sin errores.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '\\section{Listo}',
          'Completá el cierre del documento para que compile.',
          '% TODO: falta la línea que cierra el entorno document.',
          '',
        ].join('\n'),
        mustInclude: ['\\begin{document}', '\\end{document}'],
        hints: ['Todo \\begin{document} necesita su \\end{document} para cerrar.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '\\section{Listo}',
          'Ahora el documento cierra y compila.',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Flujo reproducible'],
    },
    {
      id: 'l0-estructura-texto',
      level: 0,
      title: 'Estructura y texto',
      capa: 'semantica',
      module: 'Escribir contenido',
      objective: 'organizar el documento en secciones y escribir párrafos correctamente.',
      prerequisites: ['l0-primer-documento'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Las **secciones** estructuran el documento, y LaTeX las **numera y formatea solo**. Vos decís *qué* es un título (semántica); el *cómo* se ve lo decide la clase. Hay una jerarquía: `\\section` → `\\subsection` → `\\subsubsection` (y, en clases con capítulos como `report`/`book`, arriba está `\\chapter`).',
        },
        {
          kind: 'prose',
          markdown:
            'La gran ventaja de declarar la estructura en vez de “poner un título en negrita grande”: **el índice se arma solo**. Como cada `\\section` queda registrada, `\\tableofcontents` genera el índice y la numeración se reacomoda si reordenás o insertás secciones. Por eso **nunca** numerás a mano: dejás que el sistema lo haga.',
        },
        {
          kind: 'commands',
          title: 'Estructura y títulos',
          items: [
            { cmd: '\\section{...}', desc: 'Título de primer nivel (1, 2, 3…).' },
            { cmd: '\\subsection{...}', desc: 'Subdivisión (1.1, 1.2…).' },
            { cmd: '\\subsubsection{...}', desc: 'Un nivel más de detalle (1.1.1).' },
            { cmd: '\\paragraph{...}', desc: 'Título chiquito, en la misma línea que el texto.' },
            { cmd: '\\section*{...}', desc: 'Versión sin número y fuera del índice (p. ej. Agradecimientos).' },
            { cmd: '\\tableofcontents', desc: 'Índice automático a partir de las secciones.' },
          ],
        },
        {
          kind: 'code',
          caption: 'La regla del párrafo: una línea en blanco, no un Enter simple',
          latex: ['Primer párrafo.', '', 'Segundo párrafo (lo separa la línea en blanco).'].join('\n'),
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'La regla que sorprende a todos: un salto de línea simple **no** crea un párrafo, y varios espacios o líneas en blanco seguidos cuentan como **uno solo** (LaTeX administra el espaciado). Para separar párrafos, dejá **una** línea en blanco.',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            'Dos detalles de texto útiles: `~` es un **espacio que no se parte** (usalo en `Fig.~1` o `Dr.~Pérez`, para que el número no quede colgando al inicio de un renglón); y `\\\\` fuerza un salto de línea *dentro* de un párrafo —es para casos puntuales, **no** para separar párrafos.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Buenas prácticas: una idea por párrafo (y, en el `.tex`, conviene **una oración por línea**: los diffs de git quedan limpios). Para títulos sin numerar y fuera del índice, `\\section*`. Y el índice (`\\tableofcontents`) necesita **compilar dos veces** para aparecer completo: `latexmk` lo hace solo.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '',
        '\\begin{document}',
        '',
        '\\tableofcontents   % índice automático (aparece tras compilar dos veces)',
        '',
        '\\section{Introducción}        % numerada: 1',
        'Primer párrafo de la introducción.',
        '',
        'Segundo párrafo: lo separa una línea en blanco, no un Enter simple.',
        'Esta oración va en una línea aparte en el .tex, pero el PDF la une al',
        'párrafo: el corte de línea del fuente no se ve en la salida.',
        '',
        '\\subsection{Contexto}         % 1.1',
        'Una subsección dentro de la introducción. Comparemos con la Fig.~1: el',
        '\\verb|~| evita que el “1” quede solo al empezar un renglón.',
        '',
        '\\subsubsection{Detalle fino}  % 1.1.1',
        'Un nivel más de detalle, también numerado solo.',
        '',
        '\\paragraph{Una nota al margen.} Un \\verb|\\paragraph| arranca en la misma',
        'línea que su texto, sin número.',
        '',
        '\\section*{Agradecimientos}    % con * : sin número y fuera del índice',
        'Texto de cierre, sin numerar.',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt:
          'Completá la estructura: agregá una \\subsection con su propio párrafo dentro de la sección que ya está.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '',
          '\\section{Introducción}',
          'Primer párrafo de la introducción.',
          '',
          '% TODO: agregá una \\subsection{Contexto} y, debajo, un párrafo nuevo.',
          '',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\section', '\\subsection'],
        hints: ['Para un párrafo nuevo, dejá una línea en blanco entre los textos.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '',
          '\\section{Introducción}',
          'Primer párrafo de la introducción.',
          '',
          '\\subsection{Contexto}',
          'Una subsección con su propio párrafo.',
          '',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Caracteres especiales', 'Documentos largos'],
    },
    {
      id: 'l0-caracteres-especiales',
      level: 0,
      title: 'Caracteres especiales',
      capa: 'semantica',
      module: 'Escribir contenido',
      objective: 'escribir los caracteres que LaTeX reserva, sin romper el documento.',
      prerequisites: ['l0-primer-documento'],
      content: [
        {
          kind: 'prose',
          markdown:
            'LaTeX reserva **diez caracteres** con significado propio: `% & _ # $ { } \\ ~ ^`. Para que aparezcan **literales** en el texto hay que “escaparlos”. Cinco se escapan con una barra adelante; los otros piden un comando.',
        },
        {
          kind: 'prose',
          markdown:
            'Cada uno está reservado **por una razón** (y entenderla ayuda a recordarlo): `%` inicia un comentario, `$` entra y sale del modo math, `&` separa columnas en tablas, `_` y `^` son sub/superíndice, `{ }` agrupan, `\\` empieza un comando, `#` es un parámetro de macro y `~` es un espacio que no se parte.',
        },
        {
          kind: 'commands',
          title: 'Cómo escribir cada uno',
          items: [
            { cmd: '\\% \\& \\_ \\# \\$', desc: 'Se escapan con una barra antes.' },
            { cmd: '\\{ \\}', desc: 'Llaves literales.' },
            { cmd: '\\textbackslash', desc: 'La barra invertida (¡no es \\\\, que es salto de línea!).' },
            { cmd: '\\textasciitilde, \\textasciicircum', desc: 'La virgulilla ~ y el circunflejo ^ fuera de math.' },
          ],
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'El más traicionero es `%`: todo lo que le sigue en la línea se **ignora** (es un comentario). Si “desaparece” texto —por ejemplo escribís `50% de descuento` y solo ves `50`—, casi siempre hay un `%` sin escapar.',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            'Dos detalles tipográficos que no son caracteres reservados pero se hacen mal seguido: las **comillas** correctas no son la tecla recta `"` (en español, mejor `\\enquote{...}` de csquotes); y hay **tres guiones** según el uso: `-` (palabra compuesta), `--` (rango: 10--20) y `---` (inciso, como un paréntesis).',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Para mostrar código o comandos literales (con sus barras y llaves) sin escapar uno por uno, usá `\\verb|...|` o el entorno `verbatim`. Lo vemos más adelante.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '',
        '\\begin{document}',
        '',
        '% Los reservados, escritos de forma literal en el texto:',
        'El 50\\% de aciertos; comparar A \\& B; el costo es \\$10.',
        '',
        'Un guion bajo literal: archivo\\_final. Una etiqueta \\#importante.',
        'Llaves literales: \\{ y \\}.',
        '',
        'La barra invertida: \\textbackslash{}. La virgulilla: \\textasciitilde{}.',
        '',
        '% En cambio, el subíndice matemático va en modo math:',
        'Variables $a_1$ y $a_2$.',
        '',
        '% Tres guiones según el uso: compuesto, de rango y de inciso:',
        'Teoría-práctica; páginas 10--20; un inciso ---como este--- con guion largo.',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt:
          'Escribí una oración con un porcentaje (\\%), un ampersand (\\&) y un guion bajo (\\_) literales, sin que rompa la compilación.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '',
          '% TODO: escribí una oración que incluya 50\\%, A \\& B y un\\_valor literales.',
          '',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\%', '\\&', '\\_'],
        hints: ['Cada uno lleva una barra invertida adelante: \\% \\& \\_.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '',
          'El 50\\% de los casos compara A \\& B sobre un\\_valor de referencia.',
          '',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Compilar, errores y el log'],
    },
    {
      id: 'l0-listas',
      level: 0,
      title: 'Listas',
      capa: 'semantica',
      module: 'Escribir contenido',
      objective: 'crear listas con viñetas, numeradas y de descripción, incluso anidadas.',
      prerequisites: ['l0-estructura-texto'],
      content: [
        {
          kind: 'prose',
          markdown:
            'Tres listas básicas: **itemize** (viñetas), **enumerate** (numeradas) y **description** (término + definición). Dentro de cualquiera, cada elemento empieza con `\\item`. Se pueden **anidar** poniendo una lista dentro de un `\\item`.',
        },
        {
          kind: 'prose',
          markdown:
            'Elegí la lista por el **significado**, no por cómo se ve: `itemize` cuando el orden **no importa**; `enumerate` cuando sí (pasos de un método, prioridades, ítems que vas a referenciar por número); `description` para **glosarios** o definiciones (término en negrita + explicación). Como en todo LaTeX: declarás *qué es*, y el formato lo pone la clase.',
        },
        {
          kind: 'commands',
          items: [
            { cmd: '\\begin{itemize}', desc: 'Lista con viñetas.' },
            { cmd: '\\begin{enumerate}', desc: 'Lista numerada (numera sola).' },
            { cmd: '\\begin{description}', desc: 'Lista de término → definición.' },
            { cmd: '\\item', desc: 'Empieza un elemento.' },
            { cmd: '\\item[etiqueta]', desc: 'Elemento con etiqueta propia (clave en description).' },
          ],
        },
        {
          kind: 'code',
          caption: 'Lista anidada: una lista dentro de un \\item',
          latex: [
            '\\begin{itemize}',
            '  \\item Frutas',
            '  \\begin{itemize}',
            '    \\item Manzana',
            '  \\end{itemize}',
            '\\end{itemize}',
          ].join('\n'),
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Cada `\\begin{...}` de lista necesita su `\\end{...}`, y los `\\item` van **dentro** (un `\\item` suelto da error). Y **no dejes líneas en blanco entre los ítems**: una línea en blanco empieza un párrafo nuevo y desordena la lista.',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            'La **anidación** llega hasta 4 niveles y las etiquetas cambian solas: en `itemize` van •, –, *, · ; en `enumerate`, 1. → (a) → i. → A. No hace falta elegir el símbolo a mano.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Para personalizar viñetas, numeración o el espaciado (listas más compactas), está el paquete `enumitem` (lo vemos en el Nivel 2). Evitá forzar espacios con `\\vspace`: para eso está `enumitem`.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '',
        '\\begin{document}',
        '',
        '% Viñetas, con una sublista numerada anidada:',
        '\\begin{itemize}',
        '  \\item Una viñeta.',
        '  \\item Otra, con pasos numerados adentro:',
        '  \\begin{enumerate}',
        '    \\item Paso uno.',
        '    \\item Paso dos.',
        '  \\end{enumerate}',
        '\\end{itemize}',
        '',
        '% Lista de descripción: término en negrita + definición.',
        '\\begin{description}',
        '  \\item[LaTeX] sistema de composición de textos.',
        '  \\item[PDF] el resultado compilado.',
        '\\end{description}',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt:
          'Completá: a la lista con viñetas que ya está, agregale una lista numerada (enumerate) con al menos dos \\item.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '',
          '\\begin{itemize}',
          '  \\item Primer punto.',
          '  \\item Segundo punto.',
          '\\end{itemize}',
          '',
          '% TODO: agregá debajo una lista \\begin{enumerate} ... \\end{enumerate}.',
          '',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['\\begin{itemize}', '\\begin{enumerate}', '\\item'],
        hints: ['Cerrá cada lista con su \\end{...}.'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '',
          '\\begin{itemize}',
          '  \\item Primer punto.',
          '  \\item Segundo punto.',
          '\\end{itemize}',
          '',
          '\\begin{enumerate}',
          '  \\item Paso uno.',
          '  \\item Paso dos.',
          '\\end{enumerate}',
          '',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Listas a medida (enumitem)'],
    },
    {
      id: 'l0-matematica-basica',
      level: 0,
      title: 'Matemática básica',
      capa: 'semantica',
      module: 'Escribir contenido',
      objective: 'escribir fórmulas en línea y en bloque, con potencias, subíndices, fracciones y raíces.',
      prerequisites: ['l0-estructura-texto'],
      content: [
        {
          kind: 'prose',
          markdown:
            'La matemática vive en un **modo aparte** (el *modo math*). Dos formas de entrar:\n\n- **En línea**, dentro del párrafo: `$ ... $`.\n- **En bloque**, centrada y en su renglón: `\\[ ... \\]`.',
        },
        {
          kind: 'prose',
          markdown:
            'En modo math, LaTeX cambia las reglas: las letras salen en **cursiva** (son variables), el espaciado es **matemático** (no el del texto) y hay comandos para todo lo que el teclado no tiene —letras griegas (`\\pi`, `\\alpha`), relaciones (`\\leq`, `\\neq`), operadores grandes (`\\sum`, `\\int`)—. La idea es siempre la misma: declarás *qué símbolo querés* y LaTeX lo compone bien.',
        },
        {
          kind: 'commands',
          title: 'Lo esencial del modo math',
          items: [
            { cmd: '$ ... $   /   \\[ ... \\]', desc: 'Fórmula en línea / en bloque centrada.' },
            { cmd: 'x^{2}   x_{i}', desc: 'Superíndice / subíndice (llaves si hay más de un carácter).' },
            { cmd: '\\frac{a}{b}   \\sqrt{a}', desc: 'Fracción y raíz (\\sqrt[n]{a} para índice n).' },
            { cmd: '\\pi  \\alpha  \\theta', desc: 'Letras griegas por su nombre.' },
            { cmd: '\\leq  \\geq  \\neq  \\cdot  \\times', desc: 'Relaciones y productos (≤ ≥ ≠ · ×).' },
            { cmd: '\\sum_{i=1}^{n}   \\int_a^b', desc: 'Operadores grandes con sus límites.' },
            { cmd: '\\,', desc: 'Espacio fino (p. ej. antes del dx en una integral).' },
          ],
        },
        {
          kind: 'code',
          caption: 'Llaves en exponentes: agrupan lo que es “de arriba”',
          latex: ['$x^2$      % un solo carácter: las llaves son opcionales', '$x^{10}$   % varios: las llaves son obligatorias'].join('\n'),
        },
        {
          kind: 'callout',
          tone: 'warning',
          markdown:
            'Fuera del modo math, `^` y `_` dan error (“Missing \\$ inserted”). Y los espacios que pongas **dentro** del modo math no cambian nada: `$x   +   y$` y `$x+y$` se ven igual; el espaciado lo decide LaTeX.',
        },
        {
          kind: 'callout',
          tone: 'note',
          markdown:
            '¿No sabés el comando de un símbolo? Dibujalo en **[Detexify](https://detexify.kirelabs.org)** y te dice el comando. Y para nombres de función (sen, log, lím) hay comandos propios (`\\sen` requiere definirlo; `\\log`, `\\lim` ya existen) que salen en redonda, no en cursiva.',
        },
        {
          kind: 'callout',
          tone: 'tip',
          markdown:
            'Para más de una ecuación, alinearlas o numerarlas, está el paquete `amsmath` (Nivel 1). Con lo básico de acá ya escribís cualquier fórmula suelta.',
        },
      ],
      example: [
        '\\documentclass{article}',
        '\\usepackage[T1]{fontenc}',
        '\\usepackage{lmodern}',
        '\\usepackage[spanish,es-noshorthands]{babel}',
        '\\usepackage{microtype}',
        '',
        '\\begin{document}',
        '',
        '% (1) En línea, dentro del párrafo:',
        'La identidad de Euler es $e^{i\\pi} + 1 = 0$, con subíndices $x_1, x_2$.',
        '',
        '% (2) En bloque, centrada:',
        '\\[ \\int_0^1 x^2 \\, dx = \\frac{1}{3} \\]',
        '',
        '% (3) Raíz, fracción y un gran operador juntos:',
        '\\[ \\sqrt{a^2 + b^2}, \\qquad \\sum_{i=1}^{n} \\frac{1}{i} \\]',
        '',
        '% (4) Relaciones, una griega y un producto:',
        'Para todo $n \\geq 1$ se cumple $0 \\leq \\frac{1}{n} \\leq 1$, y $2 \\cdot \\pi \\approx 6{,}28$.',
        '',
        '\\end{document}',
        '',
      ].join('\n'),
      challenge: {
        prompt:
          'Completá: una fórmula en línea con $...$ y otra en bloque con \\[ ... \\] que use \\frac.',
        starter: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '',
          '% (1) En línea:',
          'El cuadrado de la suma: % TODO: agregá $ (a+b)^2 = a^2 + 2ab + b^2 $',
          '',
          '% (2) En bloque, con una fracción:',
          '% TODO: agregá \\[ \\frac{1}{2} + \\frac{1}{3} = \\frac{5}{6} \\]',
          '',
          '\\end{document}',
          '',
        ].join('\n'),
        mustInclude: ['$', '\\[', '\\]', '\\frac'],
        hints: ['\\frac{numerador}{denominador}.', 'La fórmula en bloque va entre \\[ y \\].'],
        solution: [
          '\\documentclass{article}',
          '\\usepackage[T1]{fontenc}',
          '\\usepackage{lmodern}',
          '\\usepackage[spanish,es-noshorthands]{babel}',
          '\\usepackage{microtype}',
          '',
          '\\begin{document}',
          '',
          'El cuadrado de la suma: $ (a+b)^2 = a^2 + 2ab + b^2 $.',
          '',
          '\\[ \\frac{1}{2} + \\frac{1}{3} = \\frac{5}{6} \\]',
          '',
          '\\end{document}',
          '',
        ].join('\n'),
      },
      seeAlso: ['Matemática con amsmath', 'Símbolos, alfabetos y operadores'],
    },
  ],
} satisfies LevelInput
